from bollhav import Model, WriteMode
from bollhav.postgres import PostgresColumn, PostgresType
from bollhav.database import Database
from core import read, write
from roskarl.marshal import with_env_config, EnvConfig
from roskarl import env_var_dsn

config = Model(
    name="ar_dim_obj_kst",
    source_entity="AR_DIM_OBJ_KST",
    table="ar_dim_obj_kst",
    schema="raindance_raw_1210",
    write_mode=WriteMode.TRUNCATE_INSERT,
    columns=[
        PostgresColumn(name="_data_modified", data_type=PostgresType.DATE),
        PostgresColumn(name="_metadata_modified", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="DIV_GILTIG_FOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="DIV_GILTIG_TOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="DIV_ID", data_type=PostgresType.TEXT),
        PostgresColumn(name="DIV_ID_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="DIV_PASSIV", data_type=PostgresType.BOOLEAN),
        PostgresColumn(name="DIV_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="IRASN1_GILTIG_FOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="IRASN1_GILTIG_TOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="IRASN1_ID", data_type=PostgresType.TEXT),
        PostgresColumn(name="IRASN1_ID_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="IRASN1_PASSIV", data_type=PostgresType.BOOLEAN),
        PostgresColumn(name="IRASN1_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="IRASN2_GILTIG_FOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="IRASN2_GILTIG_TOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="IRASN2_ID", data_type=PostgresType.TEXT),
        PostgresColumn(name="IRASN2_ID_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="IRASN2_PASSIV", data_type=PostgresType.BOOLEAN),
        PostgresColumn(name="IRASN2_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="IRASN3_GILTIG_FOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="IRASN3_GILTIG_TOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="IRASN3_ID", data_type=PostgresType.TEXT),
        PostgresColumn(name="IRASN3_ID_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="IRASN3_PASSIV", data_type=PostgresType.BOOLEAN),
        PostgresColumn(name="IRASN3_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="KLINIK_GILTIG_FOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="KLINIK_GILTIG_TOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="KLINIK_ID", data_type=PostgresType.TEXT),
        PostgresColumn(name="KLINIK_ID_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="KLINIK_PASSIV", data_type=PostgresType.BOOLEAN),
        PostgresColumn(name="KLINIK_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="KST_GILTIG_FOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="KST_GILTIG_TOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="KST_ID", data_type=PostgresType.TEXT),
        PostgresColumn(name="KST_ID_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="KST_PASSIV", data_type=PostgresType.BOOLEAN),
        PostgresColumn(name="KST_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="SEKT_GILTIG_FOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="SEKT_GILTIG_TOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="SEKT_ID", data_type=PostgresType.TEXT),
        PostgresColumn(name="SEKT_ID_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="SEKT_PASSIV", data_type=PostgresType.BOOLEAN),
        PostgresColumn(name="SEKT_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="SJKGR_GILTIG_FOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="SJKGR_GILTIG_TOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="SJKGR_ID", data_type=PostgresType.TEXT),
        PostgresColumn(name="SJKGR_ID_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="SJKGR_PASSIV", data_type=PostgresType.BOOLEAN),
        PostgresColumn(name="SJKGR_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="VGREN_GILTIG_FOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="VGREN_GILTIG_TOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="VGREN_ID", data_type=PostgresType.TEXT),
        PostgresColumn(name="VGREN_ID_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="VGREN_PASSIV", data_type=PostgresType.BOOLEAN),
        PostgresColumn(name="VGREN_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="VOMR_GILTIG_FOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="VOMR_GILTIG_TOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="VOMR_ID", data_type=PostgresType.TEXT),
        PostgresColumn(name="VOMR_ID_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="VOMR_PASSIV", data_type=PostgresType.BOOLEAN),
        PostgresColumn(name="VOMR_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="VSJH_GILTIG_FOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="VSJH_GILTIG_TOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="VSJH_ID", data_type=PostgresType.TEXT),
        PostgresColumn(name="VSJH_ID_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="VSJH_PASSIV", data_type=PostgresType.BOOLEAN),
        PostgresColumn(name="VSJH_TEXT", data_type=PostgresType.TEXT),
    ],
    database=Database.POSTGRES,
    cron="0 6 * * *",
    tags=['kar', 'raindance', 'raw'],
)

@with_env_config
def execute(env: EnvConfig, cfg=config):
    dest_dsn = env_var_dsn("BIG_EKONOMI_EXECUTION_PROD")
    query = """
    SELECT
	CAST(GETDATE() AS DATE) as _data_modified,
	CAST(GETDATE() AS DATETIME2) as _metadata_modified,
	COALESCE([DIV_GILTIG_FOM], '1899-12-31 00:00:00') AS DIV_GILTIG_FOM,
	COALESCE([DIV_GILTIG_TOM], '1899-12-31 00:00:00') AS DIV_GILTIG_TOM,
	[DIV_ID] AS DIV_ID,
	[DIV_ID_TEXT] AS DIV_ID_TEXT,
	[DIV_PASSIV] AS DIV_PASSIV,
	[DIV_TEXT] AS DIV_TEXT,
	COALESCE([IRASN1_GILTIG_FOM], '1899-12-31 00:00:00') AS IRASN1_GILTIG_FOM,
	COALESCE([IRASN1_GILTIG_TOM], '1899-12-31 00:00:00') AS IRASN1_GILTIG_TOM,
	[IRASN1_ID] AS IRASN1_ID,
	[IRASN1_ID_TEXT] AS IRASN1_ID_TEXT,
	[IRASN1_PASSIV] AS IRASN1_PASSIV,
	[IRASN1_TEXT] AS IRASN1_TEXT,
	COALESCE([IRASN2_GILTIG_FOM], '1899-12-31 00:00:00') AS IRASN2_GILTIG_FOM,
	COALESCE([IRASN2_GILTIG_TOM], '1899-12-31 00:00:00') AS IRASN2_GILTIG_TOM,
	[IRASN2_ID] AS IRASN2_ID,
	[IRASN2_ID_TEXT] AS IRASN2_ID_TEXT,
	[IRASN2_PASSIV] AS IRASN2_PASSIV,
	[IRASN2_TEXT] AS IRASN2_TEXT,
	COALESCE([IRASN3_GILTIG_FOM], '1899-12-31 00:00:00') AS IRASN3_GILTIG_FOM,
	COALESCE([IRASN3_GILTIG_TOM], '1899-12-31 00:00:00') AS IRASN3_GILTIG_TOM,
	[IRASN3_ID] AS IRASN3_ID,
	[IRASN3_ID_TEXT] AS IRASN3_ID_TEXT,
	[IRASN3_PASSIV] AS IRASN3_PASSIV,
	[IRASN3_TEXT] AS IRASN3_TEXT,
	COALESCE([KLINIK_GILTIG_FOM], '1899-12-31 00:00:00') AS KLINIK_GILTIG_FOM,
	COALESCE([KLINIK_GILTIG_TOM], '1899-12-31 00:00:00') AS KLINIK_GILTIG_TOM,
	[KLINIK_ID] AS KLINIK_ID,
	[KLINIK_ID_TEXT] AS KLINIK_ID_TEXT,
	[KLINIK_PASSIV] AS KLINIK_PASSIV,
	[KLINIK_TEXT] AS KLINIK_TEXT,
	COALESCE([KST_GILTIG_FOM], '1899-12-31 00:00:00') AS KST_GILTIG_FOM,
	COALESCE([KST_GILTIG_TOM], '1899-12-31 00:00:00') AS KST_GILTIG_TOM,
	[KST_ID] AS KST_ID,
	[KST_ID_TEXT] AS KST_ID_TEXT,
	[KST_PASSIV] AS KST_PASSIV,
	[KST_TEXT] AS KST_TEXT,
	COALESCE([SEKT_GILTIG_FOM], '1899-12-31 00:00:00') AS SEKT_GILTIG_FOM,
	COALESCE([SEKT_GILTIG_TOM], '1899-12-31 00:00:00') AS SEKT_GILTIG_TOM,
	[SEKT_ID] AS SEKT_ID,
	[SEKT_ID_TEXT] AS SEKT_ID_TEXT,
	[SEKT_PASSIV] AS SEKT_PASSIV,
	[SEKT_TEXT] AS SEKT_TEXT,
	COALESCE([SJKGR_GILTIG_FOM], '1899-12-31 00:00:00') AS SJKGR_GILTIG_FOM,
	COALESCE([SJKGR_GILTIG_TOM], '1899-12-31 00:00:00') AS SJKGR_GILTIG_TOM,
	[SJKGR_ID] AS SJKGR_ID,
	[SJKGR_ID_TEXT] AS SJKGR_ID_TEXT,
	[SJKGR_PASSIV] AS SJKGR_PASSIV,
	[SJKGR_TEXT] AS SJKGR_TEXT,
	COALESCE([VGREN_GILTIG_FOM], '1899-12-31 00:00:00') AS VGREN_GILTIG_FOM,
	COALESCE([VGREN_GILTIG_TOM], '1899-12-31 00:00:00') AS VGREN_GILTIG_TOM,
	[VGREN_ID] AS VGREN_ID,
	[VGREN_ID_TEXT] AS VGREN_ID_TEXT,
	[VGREN_PASSIV] AS VGREN_PASSIV,
	[VGREN_TEXT] AS VGREN_TEXT,
	COALESCE([VOMR_GILTIG_FOM], '1899-12-31 00:00:00') AS VOMR_GILTIG_FOM,
	COALESCE([VOMR_GILTIG_TOM], '1899-12-31 00:00:00') AS VOMR_GILTIG_TOM,
	[VOMR_ID] AS VOMR_ID,
	[VOMR_ID_TEXT] AS VOMR_ID_TEXT,
	[VOMR_PASSIV] AS VOMR_PASSIV,
	[VOMR_TEXT] AS VOMR_TEXT,
	COALESCE([VSJH_GILTIG_FOM], '1899-12-31 00:00:00') AS VSJH_GILTIG_FOM,
	COALESCE([VSJH_GILTIG_TOM], '1899-12-31 00:00:00') AS VSJH_GILTIG_TOM,
	[VSJH_ID] AS VSJH_ID,
	[VSJH_ID_TEXT] AS VSJH_ID_TEXT,
	[VSJH_PASSIV] AS VSJH_PASSIV,
	[VSJH_TEXT] AS VSJH_TEXT
    FROM [Utdata].[udp_100].[AR_DIM_OBJ_KST]

    """
    total_rows = 0
    first_batch = True
    for df in read("RAINDANCE_1210", query):
        if len(df) == 0:
            continue
        write(cfg, df, dest_dsn)
        if first_batch:
            cfg.write_mode = WriteMode.APPEND
            first_batch = False
        total_rows += len(df)
    print(f"  ✓ {cfg.name}: {total_rows:,} rows written" if total_rows else f"  ⏭ {cfg.name}: no data, skipping")