from bollhav import Model, WriteMode
from bollhav.postgres import PostgresColumn, PostgresType
from bollhav.database import Database
from core import read, write
from roskarl.marshal import with_env_config, EnvConfig
from roskarl import env_var_dsn

config = Model(
    name="ek_dim_obj_proj",
    source_entity="EK_DIM_OBJ_PROJ",
    table="ek_dim_obj_proj",
    schema="raindance_raw_1210",
    write_mode=WriteMode.TRUNCATE_INSERT,
    columns=[
        PostgresColumn(name="_data_modified", data_type=PostgresType.DATE),
        PostgresColumn(name="_metadata_modified", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="FAKINT_GILTIG_FOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="FAKINT_GILTIG_TOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="FAKINT_ID", data_type=PostgresType.TEXT),
        PostgresColumn(name="FAKINT_ID_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="FAKINT_PASSIV", data_type=PostgresType.BOOLEAN),
        PostgresColumn(name="FAKINT_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="PANM_GILTIG_FOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="PANM_GILTIG_TOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="PANM_ID", data_type=PostgresType.TEXT),
        PostgresColumn(name="PANM_ID_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="PANM_PASSIV", data_type=PostgresType.BOOLEAN),
        PostgresColumn(name="PANM_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="PDIARI_GILTIG_FOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="PDIARI_GILTIG_TOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="PDIARI_ID", data_type=PostgresType.TEXT),
        PostgresColumn(name="PDIARI_ID_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="PDIARI_PASSIV", data_type=PostgresType.BOOLEAN),
        PostgresColumn(name="PDIARI_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="PHSAID_GILTIG_FOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="PHSAID_GILTIG_TOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="PHSAID_ID", data_type=PostgresType.TEXT),
        PostgresColumn(name="PHSAID_ID_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="PHSAID_PASSIV", data_type=PostgresType.BOOLEAN),
        PostgresColumn(name="PHSAID_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="PKLINI_GILTIG_FOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="PKLINI_GILTIG_TOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="PKLINI_ID", data_type=PostgresType.TEXT),
        PostgresColumn(name="PKLINI_ID_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="PKLINI_PASSIV", data_type=PostgresType.BOOLEAN),
        PostgresColumn(name="PKLINI_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="PLED_GILTIG_FOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="PLED_GILTIG_TOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="PLED_ID", data_type=PostgresType.TEXT),
        PostgresColumn(name="PLED_ID_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="PLED_PASSIV", data_type=PostgresType.BOOLEAN),
        PostgresColumn(name="PLED_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="POH_GILTIG_FOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="POH_GILTIG_TOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="POH_ID", data_type=PostgresType.TEXT),
        PostgresColumn(name="POH_ID_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="POH_PASSIV", data_type=PostgresType.BOOLEAN),
        PostgresColumn(name="POH_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="PORGNR_GILTIG_FOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="PORGNR_GILTIG_TOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="PORGNR_ID", data_type=PostgresType.TEXT),
        PostgresColumn(name="PORGNR_ID_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="PORGNR_PASSIV", data_type=PostgresType.BOOLEAN),
        PostgresColumn(name="PORGNR_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="PROHUV_GILTIG_FOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="PROHUV_GILTIG_TOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="PROHUV_ID", data_type=PostgresType.TEXT),
        PostgresColumn(name="PROHUV_ID_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="PROHUV_PASSIV", data_type=PostgresType.BOOLEAN),
        PostgresColumn(name="PROHUV_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="PROJ_GILTIG_FOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="PROJ_GILTIG_TOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="PROJ_ID", data_type=PostgresType.TEXT),
        PostgresColumn(name="PROJ_ID_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="PROJ_PASSIV", data_type=PostgresType.BOOLEAN),
        PostgresColumn(name="PROJ_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="PROSTA_GILTIG_FOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="PROSTA_GILTIG_TOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="PROSTA_ID", data_type=PostgresType.TEXT),
        PostgresColumn(name="PROSTA_ID_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="PROSTA_PASSIV", data_type=PostgresType.BOOLEAN),
        PostgresColumn(name="PROSTA_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="PTYP_GILTIG_FOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="PTYP_GILTIG_TOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="PTYP_ID", data_type=PostgresType.TEXT),
        PostgresColumn(name="PTYP_ID_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="PTYP_PASSIV", data_type=PostgresType.BOOLEAN),
        PostgresColumn(name="PTYP_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="PÅTBET_GILTIG_FOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="PÅTBET_GILTIG_TOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="PÅTBET_ID", data_type=PostgresType.TEXT),
        PostgresColumn(name="PÅTBET_ID_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="PÅTBET_PASSIV", data_type=PostgresType.BOOLEAN),
        PostgresColumn(name="PÅTBET_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="PÅTRAP_GILTIG_FOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="PÅTRAP_GILTIG_TOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="PÅTRAP_ID", data_type=PostgresType.TEXT),
        PostgresColumn(name="PÅTRAP_ID_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="PÅTRAP_PASSIV", data_type=PostgresType.BOOLEAN),
        PostgresColumn(name="PÅTRAP_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="XPLED_GILTIG_FOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="XPLED_GILTIG_TOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="XPLED_ID", data_type=PostgresType.TEXT),
        PostgresColumn(name="XPLED_ID_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="XPLED_PASSIV", data_type=PostgresType.BOOLEAN),
        PostgresColumn(name="XPLED_TEXT", data_type=PostgresType.TEXT),
    ],
    database=Database.POSTGRES,
    cron="0 6 * * *",
    tags=['kar', 'raindance', 'raw'],
)

@with_env_config
def execute(env: EnvConfig, cfg=config):
    dest_dsn = env_var_dsn("BIG_EKONOMI_EXECUTION_PROD")
    query = """
    SELECT
	CAST(GETDATE() AS DATE) as _data_modified,
	CAST(GETDATE() AS DATETIME2) as _metadata_modified,
	COALESCE([FAKINT_GILTIG_FOM], '1899-12-31 00:00:00') AS FAKINT_GILTIG_FOM,
	COALESCE([FAKINT_GILTIG_TOM], '1899-12-31 00:00:00') AS FAKINT_GILTIG_TOM,
	[FAKINT_ID] AS FAKINT_ID,
	[FAKINT_ID_TEXT] AS FAKINT_ID_TEXT,
	[FAKINT_PASSIV] AS FAKINT_PASSIV,
	[FAKINT_TEXT] AS FAKINT_TEXT,
	COALESCE([PANM_GILTIG_FOM], '1899-12-31 00:00:00') AS PANM_GILTIG_FOM,
	COALESCE([PANM_GILTIG_TOM], '1899-12-31 00:00:00') AS PANM_GILTIG_TOM,
	[PANM_ID] AS PANM_ID,
	[PANM_ID_TEXT] AS PANM_ID_TEXT,
	[PANM_PASSIV] AS PANM_PASSIV,
	[PANM_TEXT] AS PANM_TEXT,
	COALESCE([PDIARI_GILTIG_FOM], '1899-12-31 00:00:00') AS PDIARI_GILTIG_FOM,
	COALESCE([PDIARI_GILTIG_TOM], '1899-12-31 00:00:00') AS PDIARI_GILTIG_TOM,
	[PDIARI_ID] AS PDIARI_ID,
	[PDIARI_ID_TEXT] AS PDIARI_ID_TEXT,
	[PDIARI_PASSIV] AS PDIARI_PASSIV,
	[PDIARI_TEXT] AS PDIARI_TEXT,
	COALESCE([PHSAID_GILTIG_FOM], '1899-12-31 00:00:00') AS PHSAID_GILTIG_FOM,
	COALESCE([PHSAID_GILTIG_TOM], '1899-12-31 00:00:00') AS PHSAID_GILTIG_TOM,
	[PHSAID_ID] AS PHSAID_ID,
	[PHSAID_ID_TEXT] AS PHSAID_ID_TEXT,
	[PHSAID_PASSIV] AS PHSAID_PASSIV,
	[PHSAID_TEXT] AS PHSAID_TEXT,
	COALESCE([PKLINI_GILTIG_FOM], '1899-12-31 00:00:00') AS PKLINI_GILTIG_FOM,
	COALESCE([PKLINI_GILTIG_TOM], '1899-12-31 00:00:00') AS PKLINI_GILTIG_TOM,
	[PKLINI_ID] AS PKLINI_ID,
	[PKLINI_ID_TEXT] AS PKLINI_ID_TEXT,
	[PKLINI_PASSIV] AS PKLINI_PASSIV,
	[PKLINI_TEXT] AS PKLINI_TEXT,
	COALESCE([PLED_GILTIG_FOM], '1899-12-31 00:00:00') AS PLED_GILTIG_FOM,
	COALESCE([PLED_GILTIG_TOM], '1899-12-31 00:00:00') AS PLED_GILTIG_TOM,
	[PLED_ID] AS PLED_ID,
	[PLED_ID_TEXT] AS PLED_ID_TEXT,
	[PLED_PASSIV] AS PLED_PASSIV,
	[PLED_TEXT] AS PLED_TEXT,
	COALESCE([POH_GILTIG_FOM], '1899-12-31 00:00:00') AS POH_GILTIG_FOM,
	COALESCE([POH_GILTIG_TOM], '1899-12-31 00:00:00') AS POH_GILTIG_TOM,
	[POH_ID] AS POH_ID,
	[POH_ID_TEXT] AS POH_ID_TEXT,
	[POH_PASSIV] AS POH_PASSIV,
	[POH_TEXT] AS POH_TEXT,
	COALESCE([PORGNR_GILTIG_FOM], '1899-12-31 00:00:00') AS PORGNR_GILTIG_FOM,
	COALESCE([PORGNR_GILTIG_TOM], '1899-12-31 00:00:00') AS PORGNR_GILTIG_TOM,
	[PORGNR_ID] AS PORGNR_ID,
	[PORGNR_ID_TEXT] AS PORGNR_ID_TEXT,
	[PORGNR_PASSIV] AS PORGNR_PASSIV,
	[PORGNR_TEXT] AS PORGNR_TEXT,
	COALESCE([PROHUV_GILTIG_FOM], '1899-12-31 00:00:00') AS PROHUV_GILTIG_FOM,
	COALESCE([PROHUV_GILTIG_TOM], '1899-12-31 00:00:00') AS PROHUV_GILTIG_TOM,
	[PROHUV_ID] AS PROHUV_ID,
	[PROHUV_ID_TEXT] AS PROHUV_ID_TEXT,
	[PROHUV_PASSIV] AS PROHUV_PASSIV,
	[PROHUV_TEXT] AS PROHUV_TEXT,
	COALESCE([PROJ_GILTIG_FOM], '1899-12-31 00:00:00') AS PROJ_GILTIG_FOM,
	COALESCE([PROJ_GILTIG_TOM], '1899-12-31 00:00:00') AS PROJ_GILTIG_TOM,
	[PROJ_ID] AS PROJ_ID,
	[PROJ_ID_TEXT] AS PROJ_ID_TEXT,
	[PROJ_PASSIV] AS PROJ_PASSIV,
	[PROJ_TEXT] AS PROJ_TEXT,
	COALESCE([PROSTA_GILTIG_FOM], '1899-12-31 00:00:00') AS PROSTA_GILTIG_FOM,
	COALESCE([PROSTA_GILTIG_TOM], '1899-12-31 00:00:00') AS PROSTA_GILTIG_TOM,
	[PROSTA_ID] AS PROSTA_ID,
	[PROSTA_ID_TEXT] AS PROSTA_ID_TEXT,
	[PROSTA_PASSIV] AS PROSTA_PASSIV,
	[PROSTA_TEXT] AS PROSTA_TEXT,
	COALESCE([PTYP_GILTIG_FOM], '1899-12-31 00:00:00') AS PTYP_GILTIG_FOM,
	COALESCE([PTYP_GILTIG_TOM], '1899-12-31 00:00:00') AS PTYP_GILTIG_TOM,
	[PTYP_ID] AS PTYP_ID,
	[PTYP_ID_TEXT] AS PTYP_ID_TEXT,
	[PTYP_PASSIV] AS PTYP_PASSIV,
	[PTYP_TEXT] AS PTYP_TEXT,
	COALESCE([PÅTBET_GILTIG_FOM], '1899-12-31 00:00:00') AS PÅTBET_GILTIG_FOM,
	COALESCE([PÅTBET_GILTIG_TOM], '1899-12-31 00:00:00') AS PÅTBET_GILTIG_TOM,
	[PÅTBET_ID] AS PÅTBET_ID,
	[PÅTBET_ID_TEXT] AS PÅTBET_ID_TEXT,
	[PÅTBET_PASSIV] AS PÅTBET_PASSIV,
	[PÅTBET_TEXT] AS PÅTBET_TEXT,
	COALESCE([PÅTRAP_GILTIG_FOM], '1899-12-31 00:00:00') AS PÅTRAP_GILTIG_FOM,
	COALESCE([PÅTRAP_GILTIG_TOM], '1899-12-31 00:00:00') AS PÅTRAP_GILTIG_TOM,
	[PÅTRAP_ID] AS PÅTRAP_ID,
	[PÅTRAP_ID_TEXT] AS PÅTRAP_ID_TEXT,
	[PÅTRAP_PASSIV] AS PÅTRAP_PASSIV,
	[PÅTRAP_TEXT] AS PÅTRAP_TEXT,
	COALESCE([XPLED_GILTIG_FOM], '1899-12-31 00:00:00') AS XPLED_GILTIG_FOM,
	COALESCE([XPLED_GILTIG_TOM], '1899-12-31 00:00:00') AS XPLED_GILTIG_TOM,
	[XPLED_ID] AS XPLED_ID,
	[XPLED_ID_TEXT] AS XPLED_ID_TEXT,
	[XPLED_PASSIV] AS XPLED_PASSIV,
	[XPLED_TEXT] AS XPLED_TEXT
    FROM [Utdata].[udp_100].[EK_DIM_OBJ_PROJ]

    """
    total_rows = 0
    first_batch = True
    for df in read("RAINDANCE_1210", query):
        if len(df) == 0:
            continue
        write(cfg, df, dest_dsn)
        if first_batch:
            cfg.write_mode = WriteMode.APPEND
            first_batch = False
        total_rows += len(df)
    print(f"  ✓ {cfg.name}: {total_rows:,} rows written" if total_rows else f"  ⏭ {cfg.name}: no data, skipping")