from bollhav import Model, WriteMode
from bollhav.postgres import PostgresColumn, PostgresType
from bollhav.database import Database
from core import read

config = Model(
    name="ek_dim_obj_konto",
    source_entity="EK_DIM_OBJ_KONTO",
    table="ek_dim_obj_konto",
    schema="raindance_raw_1210",
    write_mode=WriteMode.TRUNCATE_INSERT,
    columns=[
        PostgresColumn(name="_data_modified", data_type=PostgresType.DATE),
        PostgresColumn(name="_metadata_modified", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="FRANGO_GILTIG_FOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="FRANGO_GILTIG_TOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="FRANGO_ID", data_type=PostgresType.TEXT),
        PostgresColumn(name="FRANGO_ID_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="FRANGO_PASSIV", data_type=PostgresType.BOOLEAN),
        PostgresColumn(name="FRANGO_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="FRARAD_GILTIG_FOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="FRARAD_GILTIG_TOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="FRARAD_ID", data_type=PostgresType.TEXT),
        PostgresColumn(name="FRARAD_ID_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="FRARAD_PASSIV", data_type=PostgresType.BOOLEAN),
        PostgresColumn(name="FRARAD_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="FRASUM_GILTIG_FOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="FRASUM_GILTIG_TOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="FRASUM_ID", data_type=PostgresType.TEXT),
        PostgresColumn(name="FRASUM_ID_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="FRASUM_PASSIV", data_type=PostgresType.BOOLEAN),
        PostgresColumn(name="FRASUM_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="FRIRA2_GILTIG_FOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="FRIRA2_GILTIG_TOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="FRIRA2_ID", data_type=PostgresType.TEXT),
        PostgresColumn(name="FRIRA2_ID_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="FRIRA2_PASSIV", data_type=PostgresType.BOOLEAN),
        PostgresColumn(name="FRIRA2_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="FRIRAD_GILTIG_FOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="FRIRAD_GILTIG_TOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="FRIRAD_ID", data_type=PostgresType.TEXT),
        PostgresColumn(name="FRIRAD_ID_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="FRIRAD_PASSIV", data_type=PostgresType.BOOLEAN),
        PostgresColumn(name="FRIRAD_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="FRISUM_GILTIG_FOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="FRISUM_GILTIG_TOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="FRISUM_ID", data_type=PostgresType.TEXT),
        PostgresColumn(name="FRISUM_ID_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="FRISUM_PASSIV", data_type=PostgresType.BOOLEAN),
        PostgresColumn(name="FRISUM_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="KONTO_GILTIG_FOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="KONTO_GILTIG_TOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="KONTO_ID", data_type=PostgresType.TEXT),
        PostgresColumn(name="KONTO_ID_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="KONTO_PASSIV", data_type=PostgresType.BOOLEAN),
        PostgresColumn(name="KONTO_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="KRES_GILTIG_FOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="KRES_GILTIG_TOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="KRES_ID", data_type=PostgresType.TEXT),
        PostgresColumn(name="KRES_ID_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="KRES_PASSIV", data_type=PostgresType.BOOLEAN),
        PostgresColumn(name="KRES_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="KRGRP_GILTIG_FOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="KRGRP_GILTIG_TOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="KRGRP_ID", data_type=PostgresType.TEXT),
        PostgresColumn(name="KRGRP_ID_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="KRGRP_PASSIV", data_type=PostgresType.BOOLEAN),
        PostgresColumn(name="KRGRP_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="KTO2_GILTIG_FOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="KTO2_GILTIG_TOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="KTO2_ID", data_type=PostgresType.TEXT),
        PostgresColumn(name="KTO2_ID_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="KTO2_PASSIV", data_type=PostgresType.BOOLEAN),
        PostgresColumn(name="KTO2_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="SJKGRP_GILTIG_FOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="SJKGRP_GILTIG_TOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="SJKGRP_ID", data_type=PostgresType.TEXT),
        PostgresColumn(name="SJKGRP_ID_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="SJKGRP_PASSIV", data_type=PostgresType.BOOLEAN),
        PostgresColumn(name="SJKGRP_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="SJKRAD_GILTIG_FOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="SJKRAD_GILTIG_TOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="SJKRAD_ID", data_type=PostgresType.TEXT),
        PostgresColumn(name="SJKRAD_ID_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="SJKRAD_PASSIV", data_type=PostgresType.BOOLEAN),
        PostgresColumn(name="SJKRAD_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="UKONTO_GILTIG_FOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="UKONTO_GILTIG_TOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="UKONTO_ID", data_type=PostgresType.TEXT),
        PostgresColumn(name="UKONTO_ID_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="UKONTO_PASSIV", data_type=PostgresType.BOOLEAN),
        PostgresColumn(name="UKONTO_TEXT", data_type=PostgresType.TEXT),
    ],
    database=Database.POSTGRES,
    cron="0 6 * * *",
    tags=['kar', 'raindance', 'raw'],
)

def execute(env, cfg=config):
    query=f"""SELECT * FROM (SELECT
    	CAST(GETDATE() AS DATE) as _data_modified,
    	CAST(GETDATE() AS DATETIME2) as _metadata_modified,
    	COALESCE([FRANGO_GILTIG_FOM], '1899-12-31 00:00:00') AS FRANGO_GILTIG_FOM,
    	COALESCE([FRANGO_GILTIG_TOM], '1899-12-31 00:00:00') AS FRANGO_GILTIG_TOM,
    	[FRANGO_ID] AS FRANGO_ID,
    	[FRANGO_ID_TEXT] AS FRANGO_ID_TEXT,
    	[FRANGO_PASSIV] AS FRANGO_PASSIV,
    	[FRANGO_TEXT] AS FRANGO_TEXT,
    	COALESCE([FRARAD_GILTIG_FOM], '1899-12-31 00:00:00') AS FRARAD_GILTIG_FOM,
    	COALESCE([FRARAD_GILTIG_TOM], '1899-12-31 00:00:00') AS FRARAD_GILTIG_TOM,
    	[FRARAD_ID] AS FRARAD_ID,
    	[FRARAD_ID_TEXT] AS FRARAD_ID_TEXT,
    	[FRARAD_PASSIV] AS FRARAD_PASSIV,
    	[FRARAD_TEXT] AS FRARAD_TEXT,
    	COALESCE([FRASUM_GILTIG_FOM], '1899-12-31 00:00:00') AS FRASUM_GILTIG_FOM,
    	COALESCE([FRASUM_GILTIG_TOM], '1899-12-31 00:00:00') AS FRASUM_GILTIG_TOM,
    	[FRASUM_ID] AS FRASUM_ID,
    	[FRASUM_ID_TEXT] AS FRASUM_ID_TEXT,
    	[FRASUM_PASSIV] AS FRASUM_PASSIV,
    	[FRASUM_TEXT] AS FRASUM_TEXT,
    	COALESCE([FRIRA2_GILTIG_FOM], '1899-12-31 00:00:00') AS FRIRA2_GILTIG_FOM,
    	COALESCE([FRIRA2_GILTIG_TOM], '1899-12-31 00:00:00') AS FRIRA2_GILTIG_TOM,
    	[FRIRA2_ID] AS FRIRA2_ID,
    	[FRIRA2_ID_TEXT] AS FRIRA2_ID_TEXT,
    	[FRIRA2_PASSIV] AS FRIRA2_PASSIV,
    	[FRIRA2_TEXT] AS FRIRA2_TEXT,
    	COALESCE([FRIRAD_GILTIG_FOM], '1899-12-31 00:00:00') AS FRIRAD_GILTIG_FOM,
    	COALESCE([FRIRAD_GILTIG_TOM], '1899-12-31 00:00:00') AS FRIRAD_GILTIG_TOM,
    	[FRIRAD_ID] AS FRIRAD_ID,
    	[FRIRAD_ID_TEXT] AS FRIRAD_ID_TEXT,
    	[FRIRAD_PASSIV] AS FRIRAD_PASSIV,
    	[FRIRAD_TEXT] AS FRIRAD_TEXT,
    	COALESCE([FRISUM_GILTIG_FOM], '1899-12-31 00:00:00') AS FRISUM_GILTIG_FOM,
    	COALESCE([FRISUM_GILTIG_TOM], '1899-12-31 00:00:00') AS FRISUM_GILTIG_TOM,
    	[FRISUM_ID] AS FRISUM_ID,
    	[FRISUM_ID_TEXT] AS FRISUM_ID_TEXT,
    	[FRISUM_PASSIV] AS FRISUM_PASSIV,
    	[FRISUM_TEXT] AS FRISUM_TEXT,
    	COALESCE([KONTO_GILTIG_FOM], '1899-12-31 00:00:00') AS KONTO_GILTIG_FOM,
    	COALESCE([KONTO_GILTIG_TOM], '1899-12-31 00:00:00') AS KONTO_GILTIG_TOM,
    	[KONTO_ID] AS KONTO_ID,
    	[KONTO_ID_TEXT] AS KONTO_ID_TEXT,
    	[KONTO_PASSIV] AS KONTO_PASSIV,
    	[KONTO_TEXT] AS KONTO_TEXT,
    	COALESCE([KRES_GILTIG_FOM], '1899-12-31 00:00:00') AS KRES_GILTIG_FOM,
    	COALESCE([KRES_GILTIG_TOM], '1899-12-31 00:00:00') AS KRES_GILTIG_TOM,
    	[KRES_ID] AS KRES_ID,
    	[KRES_ID_TEXT] AS KRES_ID_TEXT,
    	[KRES_PASSIV] AS KRES_PASSIV,
    	[KRES_TEXT] AS KRES_TEXT,
    	COALESCE([KRGRP_GILTIG_FOM], '1899-12-31 00:00:00') AS KRGRP_GILTIG_FOM,
    	COALESCE([KRGRP_GILTIG_TOM], '1899-12-31 00:00:00') AS KRGRP_GILTIG_TOM,
    	[KRGRP_ID] AS KRGRP_ID,
    	[KRGRP_ID_TEXT] AS KRGRP_ID_TEXT,
    	[KRGRP_PASSIV] AS KRGRP_PASSIV,
    	[KRGRP_TEXT] AS KRGRP_TEXT,
    	COALESCE([KTO2_GILTIG_FOM], '1899-12-31 00:00:00') AS KTO2_GILTIG_FOM,
    	COALESCE([KTO2_GILTIG_TOM], '1899-12-31 00:00:00') AS KTO2_GILTIG_TOM,
    	[KTO2_ID] AS KTO2_ID,
    	[KTO2_ID_TEXT] AS KTO2_ID_TEXT,
    	[KTO2_PASSIV] AS KTO2_PASSIV,
    	[KTO2_TEXT] AS KTO2_TEXT,
    	COALESCE([SJKGRP_GILTIG_FOM], '1899-12-31 00:00:00') AS SJKGRP_GILTIG_FOM,
    	COALESCE([SJKGRP_GILTIG_TOM], '1899-12-31 00:00:00') AS SJKGRP_GILTIG_TOM,
    	[SJKGRP_ID] AS SJKGRP_ID,
    	[SJKGRP_ID_TEXT] AS SJKGRP_ID_TEXT,
    	[SJKGRP_PASSIV] AS SJKGRP_PASSIV,
    	[SJKGRP_TEXT] AS SJKGRP_TEXT,
    	COALESCE([SJKRAD_GILTIG_FOM], '1899-12-31 00:00:00') AS SJKRAD_GILTIG_FOM,
    	COALESCE([SJKRAD_GILTIG_TOM], '1899-12-31 00:00:00') AS SJKRAD_GILTIG_TOM,
    	[SJKRAD_ID] AS SJKRAD_ID,
    	[SJKRAD_ID_TEXT] AS SJKRAD_ID_TEXT,
    	[SJKRAD_PASSIV] AS SJKRAD_PASSIV,
    	[SJKRAD_TEXT] AS SJKRAD_TEXT,
    	COALESCE([UKONTO_GILTIG_FOM], '1899-12-31 00:00:00') AS UKONTO_GILTIG_FOM,
    	COALESCE([UKONTO_GILTIG_TOM], '1899-12-31 00:00:00') AS UKONTO_GILTIG_TOM,
    	[UKONTO_ID] AS UKONTO_ID,
    	[UKONTO_ID_TEXT] AS UKONTO_ID_TEXT,
    	[UKONTO_PASSIV] AS UKONTO_PASSIV,
    	[UKONTO_TEXT] AS UKONTO_TEXT
    FROM [Utdata].[udp_100].[EK_DIM_OBJ_KONTO]) y
    WHERE 1=1"""
    yield from read(query=query, env_var_name='RAINDANCE_1210')