from bollhav import Model, WriteMode
from bollhav.postgres import PostgresColumn, PostgresType
from bollhav.database import Database
from core import read, write
from roskarl.marshal import with_env_config, EnvConfig
from roskarl import env_var_dsn

config = Model(
    name="rk_fakta_levfakt_verifikat",
    source_entity="RK_FAKTA_LEVFAKT_VERIFIKAT",
    table="rk_fakta_levfakt_verifikat",
    schema="raindance_raw_1210",
    write_mode=WriteMode.MERGE,
    columns=[
        PostgresColumn(name="_data_modified", data_type=PostgresType.DATE),
        PostgresColumn(name="_metadata_modified", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="AKT_ID", data_type=PostgresType.TEXT),
        PostgresColumn(name="ANTAL_V", data_type=PostgresType.NUMERIC),
        PostgresColumn(name="ATTEST", data_type=PostgresType.BOOLEAN),
        PostgresColumn(name="ATTESTDATUM1", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="ATTESTDATUM2", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="ATTESTSIGN1", data_type=PostgresType.TEXT),
        PostgresColumn(name="ATTESTSIGN2", data_type=PostgresType.TEXT),
        PostgresColumn(name="AVTAL_ID", data_type=PostgresType.TEXT),
        PostgresColumn(name="AVTALID", data_type=PostgresType.TEXT),
        PostgresColumn(name="BELOPP_SEK", data_type=PostgresType.NUMERIC),
        PostgresColumn(name="BELOPP_VAL", data_type=PostgresType.NUMERIC),
        PostgresColumn(name="BETALNINGSSPARR", data_type=PostgresType.BOOLEAN),
        PostgresColumn(name="BETALT_SEK", data_type=PostgresType.NUMERIC),
        PostgresColumn(name="BETALT_VAL", data_type=PostgresType.NUMERIC),
        PostgresColumn(name="BETDAGAR", data_type=PostgresType.NUMERIC),
        PostgresColumn(name="BPUTF_V", data_type=PostgresType.NUMERIC),
        PostgresColumn(name="DEFDATUM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="DEFSIGN", data_type=PostgresType.TEXT),
        PostgresColumn(name="DOK_ANTAL", data_type=PostgresType.NUMERIC),
        PostgresColumn(name="DOKTYP", data_type=PostgresType.NUMERIC),
        PostgresColumn(name="DOKUMENTID", data_type=PostgresType.TEXT),
        PostgresColumn(name="EREF", data_type=PostgresType.TEXT),
        PostgresColumn(name="EXTERNANM", data_type=PostgresType.TEXT),
        PostgresColumn(name="EXTERNID", data_type=PostgresType.TEXT),
        PostgresColumn(name="EXTERNNR", data_type=PostgresType.TEXT),
        PostgresColumn(name="F_DOK_ANTAL", data_type=PostgresType.NUMERIC),
        PostgresColumn(name="F_MED", data_type=PostgresType.NUMERIC),
        PostgresColumn(name="FAKPERSLUTDAT", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="FAKPERSTARTDAT", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="FAKTSTATUS", data_type=PostgresType.TEXT),
        PostgresColumn(name="FAKTURA_REGDATUM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="FAKTURADATUM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="FORETAG", data_type=PostgresType.NUMERIC),
        PostgresColumn(name="FORFALLODATUM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="FÖPROC_ID", data_type=PostgresType.TEXT),
        PostgresColumn(name="FÖRBEL_V", data_type=PostgresType.NUMERIC),
        PostgresColumn(name="HDATUM_ID", data_type=PostgresType.TEXT),
        PostgresColumn(name="HUVUDTEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="IB", data_type=PostgresType.TEXT),
        PostgresColumn(name="INTERNVERNR", data_type=PostgresType.NUMERIC),
        PostgresColumn(name="INVNR_ID", data_type=PostgresType.TEXT),
        PostgresColumn(name="KATEGORI", data_type=PostgresType.NUMERIC),
        PostgresColumn(name="KONTO_ID", data_type=PostgresType.TEXT),
        PostgresColumn(name="KONTSIGN", data_type=PostgresType.TEXT),
        PostgresColumn(name="KRAVNIVA", data_type=PostgresType.NUMERIC),
        PostgresColumn(name="KST_ID", data_type=PostgresType.TEXT),
        PostgresColumn(name="LEVID", data_type=PostgresType.TEXT),
        PostgresColumn(name="LEVID_ID", data_type=PostgresType.TEXT),
        PostgresColumn(name="LEVRTYP", data_type=PostgresType.TEXT),
        PostgresColumn(name="MED", data_type=PostgresType.NUMERIC),
        PostgresColumn(name="MOMS_SEK", data_type=PostgresType.NUMERIC),
        PostgresColumn(name="MOMS_VAL", data_type=PostgresType.NUMERIC),
        PostgresColumn(name="MOTP_ID", data_type=PostgresType.TEXT),
        PostgresColumn(name="MOTTATTDAT", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="MOTTATTSIGN", data_type=PostgresType.TEXT),
        PostgresColumn(name="NR", data_type=PostgresType.NUMERIC),
        PostgresColumn(name="OCRNR", data_type=PostgresType.TEXT),
        PostgresColumn(name="OKI_ID", data_type=PostgresType.TEXT),
        PostgresColumn(name="ORGVAL_V", data_type=PostgresType.NUMERIC),
        PostgresColumn(name="OVERDRDAGAR", data_type=PostgresType.NUMERIC),
        PostgresColumn(name="PNYCKEL", data_type=PostgresType.TEXT),
        PostgresColumn(name="PROD_ID", data_type=PostgresType.TEXT),
        PostgresColumn(name="PROJ_ID", data_type=PostgresType.TEXT),
        PostgresColumn(name="RAD_ID", data_type=PostgresType.TEXT),
        PostgresColumn(name="RADTEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="RADTYPNR", data_type=PostgresType.NUMERIC),
        PostgresColumn(name="RANTEDEB", data_type=PostgresType.BOOLEAN),
        PostgresColumn(name="REGDATUM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="REGSIGN", data_type=PostgresType.TEXT),
        PostgresColumn(name="SENASTBETDATUM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="SKI_ID", data_type=PostgresType.TEXT),
        PostgresColumn(name="STATUS", data_type=PostgresType.TEXT),
        PostgresColumn(name="TAB_A#P", data_type=PostgresType.TEXT),
        PostgresColumn(name="TAB_BETV", data_type=PostgresType.TEXT),
        PostgresColumn(name="TAB_CW", data_type=PostgresType.TEXT),
        PostgresColumn(name="TAB_DIV", data_type=PostgresType.TEXT),
        PostgresColumn(name="TAB_EXPORT", data_type=PostgresType.TEXT),
        PostgresColumn(name="TAB_HANDL", data_type=PostgresType.TEXT),
        PostgresColumn(name="TAB_KLIN", data_type=PostgresType.TEXT),
        PostgresColumn(name="TAB_KST", data_type=PostgresType.TEXT),
        PostgresColumn(name="TAB_LAND", data_type=PostgresType.TEXT),
        PostgresColumn(name="TAB_MOMS", data_type=PostgresType.TEXT),
        PostgresColumn(name="TAB_MOTP", data_type=PostgresType.TEXT),
        PostgresColumn(name="TAB_ORDNR", data_type=PostgresType.TEXT),
        PostgresColumn(name="TAB_RESK", data_type=PostgresType.TEXT),
        PostgresColumn(name="TAB_RTYP", data_type=PostgresType.TEXT),
        PostgresColumn(name="TAB_SCADAT", data_type=PostgresType.TEXT),
        PostgresColumn(name="TAB_SCANNR", data_type=PostgresType.TEXT),
        PostgresColumn(name="TAB_SEKT", data_type=PostgresType.TEXT),
        PostgresColumn(name="TAB_SNI", data_type=PostgresType.TEXT),
        PostgresColumn(name="TAB_UBF", data_type=PostgresType.TEXT),
        PostgresColumn(name="TAB_UBK", data_type=PostgresType.TEXT),
        PostgresColumn(name="TAB_VALR", data_type=PostgresType.TEXT),
        PostgresColumn(name="TAB_VARUKD", data_type=PostgresType.TEXT),
        PostgresColumn(name="TANV_ID", data_type=PostgresType.TEXT),
        PostgresColumn(name="TIMMAR_V", data_type=PostgresType.NUMERIC),
        PostgresColumn(name="TTYP_ID", data_type=PostgresType.TEXT),
        PostgresColumn(name="TYP_ID", data_type=PostgresType.TEXT),
        PostgresColumn(name="URSPR_ID", data_type=PostgresType.TEXT),
        PostgresColumn(name="URSPRUNGS_VERIFIKAT", data_type=PostgresType.TEXT),
        PostgresColumn(name="URSPTEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="UTFALL_V", data_type=PostgresType.NUMERIC),
        PostgresColumn(name="UTILITY", data_type=PostgresType.NUMERIC),
        PostgresColumn(name="UTSKRDATUM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="VALUTA_ID", data_type=PostgresType.TEXT),
        PostgresColumn(name="VERDATUM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="VERDOKREF", data_type=PostgresType.TEXT),
        PostgresColumn(name="VERNR", data_type=PostgresType.NUMERIC),
        PostgresColumn(name="VERRAD", data_type=PostgresType.NUMERIC),
        PostgresColumn(name="VERTYP", data_type=PostgresType.TEXT),
        PostgresColumn(name="VREF", data_type=PostgresType.TEXT),
        PostgresColumn(name="YRKE_ID", data_type=PostgresType.TEXT),
    ],
    database=Database.POSTGRES,
    cron="0 6 * * *",
    tags=['kar', 'raindance', 'raw'],
)

@with_env_config
def execute(env: EnvConfig, cfg=config):
    dest_dsn = env_var_dsn("BIG_EKONOMI_EXECUTION_PROD")
    if env.backfill and env.backfill.enabled:
        since = env.backfill.since.strftime("%Y-%m-%d")
        until = env.backfill.until.strftime("%Y-%m-%d")
    elif env.cron and env.cron.enabled:
        since = env.cron.since.strftime("%Y-%m-%d")
        until = env.cron.until.strftime("%Y-%m-%d")
    else:
        raise ValueError(f"{cfg.name}: MERGE requires CRON or BACKFILL env vars")
    query = f"""
    SELECT
	CAST(VERDATUM AS DATE) as _data_modified,
	CAST(GETDATE() AS DATETIME2) as _metadata_modified,
	[AKT_ID] AS AKT_ID,
	[ANTAL_V] AS ANTAL_V,
	[ATTEST] AS ATTEST,
	COALESCE([ATTESTDATUM1], '1899-12-31 00:00:00') AS ATTESTDATUM1,
	COALESCE([ATTESTDATUM2], '1899-12-31 00:00:00') AS ATTESTDATUM2,
	[ATTESTSIGN1] AS ATTESTSIGN1,
	[ATTESTSIGN2] AS ATTESTSIGN2,
	[AVTAL_ID] AS AVTAL_ID,
	[AVTALID] AS AVTALID,
	[BELOPP_SEK] AS BELOPP_SEK,
	[BELOPP_VAL] AS BELOPP_VAL,
	[BETALNINGSSPARR] AS BETALNINGSSPARR,
	[BETALT_SEK] AS BETALT_SEK,
	[BETALT_VAL] AS BETALT_VAL,
	[BETDAGAR] AS BETDAGAR,
	[BPUTF_V] AS BPUTF_V,
	COALESCE([DEFDATUM], '1899-12-31 00:00:00') AS DEFDATUM,
	[DEFSIGN] AS DEFSIGN,
	[DOK_ANTAL] AS DOK_ANTAL,
	[DOKTYP] AS DOKTYP,
	[DOKUMENTID] AS DOKUMENTID,
	[EREF] AS EREF,
	[EXTERNANM] AS EXTERNANM,
	[EXTERNID] AS EXTERNID,
	[EXTERNNR] AS EXTERNNR,
	[F_DOK_ANTAL] AS F_DOK_ANTAL,
	[F_MED] AS F_MED,
	COALESCE([FAKPERSLUTDAT], '1899-12-31 00:00:00') AS FAKPERSLUTDAT,
	COALESCE([FAKPERSTARTDAT], '1899-12-31 00:00:00') AS FAKPERSTARTDAT,
	[FAKTSTATUS] AS FAKTSTATUS,
	COALESCE([FAKTURA_REGDATUM], '1899-12-31 00:00:00') AS FAKTURA_REGDATUM,
	COALESCE([FAKTURADATUM], '1899-12-31 00:00:00') AS FAKTURADATUM,
	[FORETAG] AS FORETAG,
	COALESCE([FORFALLODATUM], '1899-12-31 00:00:00') AS FORFALLODATUM,
	[FÖPROC_ID] AS FÖPROC_ID,
	[FÖRBEL_V] AS FÖRBEL_V,
	[HDATUM_ID] AS HDATUM_ID,
	[HUVUDTEXT] AS HUVUDTEXT,
	[IB] AS IB,
	[INTERNVERNR] AS INTERNVERNR,
	[INVNR_ID] AS INVNR_ID,
	[KATEGORI] AS KATEGORI,
	[KONTO_ID] AS KONTO_ID,
	[KONTSIGN] AS KONTSIGN,
	[KRAVNIVA] AS KRAVNIVA,
	[KST_ID] AS KST_ID,
	[LEVID] AS LEVID,
	[LEVID_ID] AS LEVID_ID,
	[LEVRTYP] AS LEVRTYP,
	[MED] AS MED,
	[MOMS_SEK] AS MOMS_SEK,
	[MOMS_VAL] AS MOMS_VAL,
	[MOTP_ID] AS MOTP_ID,
	COALESCE([MOTTATTDAT], '1899-12-31 00:00:00') AS MOTTATTDAT,
	[MOTTATTSIGN] AS MOTTATTSIGN,
	[NR] AS NR,
	[OCRNR] AS OCRNR,
	[OKI_ID] AS OKI_ID,
	[ORGVAL_V] AS ORGVAL_V,
	[OVERDRDAGAR] AS OVERDRDAGAR,
	[PNYCKEL] AS PNYCKEL,
	[PROD_ID] AS PROD_ID,
	[PROJ_ID] AS PROJ_ID,
	[RAD_ID] AS RAD_ID,
	[RADTEXT] AS RADTEXT,
	[RADTYPNR] AS RADTYPNR,
	[RANTEDEB] AS RANTEDEB,
	COALESCE([REGDATUM], '1899-12-31 00:00:00') AS REGDATUM,
	[REGSIGN] AS REGSIGN,
	COALESCE([SENASTBETDATUM], '1899-12-31 00:00:00') AS SENASTBETDATUM,
	[SKI_ID] AS SKI_ID,
	[STATUS] AS STATUS,
	[TAB_A#P] AS TAB_A#P,
	[TAB_BETV] AS TAB_BETV,
	[TAB_CW] AS TAB_CW,
	[TAB_DIV] AS TAB_DIV,
	[TAB_EXPORT] AS TAB_EXPORT,
	[TAB_HANDL] AS TAB_HANDL,
	[TAB_KLIN] AS TAB_KLIN,
	[TAB_KST] AS TAB_KST,
	[TAB_LAND] AS TAB_LAND,
	[TAB_MOMS] AS TAB_MOMS,
	[TAB_MOTP] AS TAB_MOTP,
	[TAB_ORDNR] AS TAB_ORDNR,
	[TAB_RESK] AS TAB_RESK,
	[TAB_RTYP] AS TAB_RTYP,
	[TAB_SCADAT] AS TAB_SCADAT,
	[TAB_SCANNR] AS TAB_SCANNR,
	[TAB_SEKT] AS TAB_SEKT,
	[TAB_SNI] AS TAB_SNI,
	[TAB_UBF] AS TAB_UBF,
	[TAB_UBK] AS TAB_UBK,
	[TAB_VALR] AS TAB_VALR,
	[TAB_VARUKD] AS TAB_VARUKD,
	[TANV_ID] AS TANV_ID,
	[TIMMAR_V] AS TIMMAR_V,
	[TTYP_ID] AS TTYP_ID,
	[TYP_ID] AS TYP_ID,
	[URSPR_ID] AS URSPR_ID,
	[URSPRUNGS_VERIFIKAT] AS URSPRUNGS_VERIFIKAT,
	[URSPTEXT] AS URSPTEXT,
	[UTFALL_V] AS UTFALL_V,
	[UTILITY] AS UTILITY,
	COALESCE([UTSKRDATUM], '1899-12-31 00:00:00') AS UTSKRDATUM,
	[VALUTA_ID] AS VALUTA_ID,
	COALESCE([VERDATUM], '1899-12-31 00:00:00') AS VERDATUM,
	[VERDOKREF] AS VERDOKREF,
	[VERNR] AS VERNR,
	[VERRAD] AS VERRAD,
	[VERTYP] AS VERTYP,
	[VREF] AS VREF,
	[YRKE_ID] AS YRKE_ID
    FROM [Utdata].[udp_100].[RK_FAKTA_LEVFAKT_VERIFIKAT]
    WHERE CAST(VERDATUM AS DATE) BETWEEN '{since}' AND '{until}'
    """
    total_rows = 0
    first_batch = True
    for df in read("RAINDANCE_1210", query, batch_size=500_000):
        if len(df) == 0:
            continue
        write(cfg, df, dest_dsn, since=since, until=until)
        if first_batch:
            cfg.write_mode = WriteMode.APPEND
            first_batch = False
        total_rows += len(df)
    print(f"  ✓ {cfg.name}: {total_rows:,} rows written" if total_rows else f"  ⏭ {cfg.name}: no data, skipping")