from bollhav import Model, WriteMode
from bollhav.postgres import PostgresColumn, PostgresType
from bollhav.database import Database
from core import read

config = Model(
    name="ek_fakta_verifikat",
    source_entity="EK_FAKTA_VERIFIKAT",
    table="ek_fakta_verifikat",
    schema="raindance_raw_1100",
    write_mode=WriteMode.MERGE,
    columns=[
        PostgresColumn(name="_data_modified", data_type=PostgresType.DATE),
        PostgresColumn(name="_metadata_modified", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="AKT_ID", data_type=PostgresType.TEXT),
        PostgresColumn(name="ATTESTDATUM1", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="ATTESTDATUM2", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="ATTESTSIGN1", data_type=PostgresType.TEXT),
        PostgresColumn(name="ATTESTSIGN2", data_type=PostgresType.TEXT),
        PostgresColumn(name="AVT_ID", data_type=PostgresType.TEXT),
        PostgresColumn(name="BESTUT_V", data_type=PostgresType.NUMERIC),
        PostgresColumn(name="BUDGET_V", data_type=PostgresType.NUMERIC),
        PostgresColumn(name="BUDV2_V", data_type=PostgresType.NUMERIC),
        PostgresColumn(name="DATUM_ID", data_type=PostgresType.TEXT),
        PostgresColumn(name="DEFDATUM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="DEFSIGN", data_type=PostgresType.TEXT),
        PostgresColumn(name="DOK_ANTAL", data_type=PostgresType.NUMERIC),
        PostgresColumn(name="DOKTYP", data_type=PostgresType.NUMERIC),
        PostgresColumn(name="DOKUMENTID", data_type=PostgresType.TEXT),
        PostgresColumn(name="ERS_ID", data_type=PostgresType.TEXT),
        PostgresColumn(name="EXTERNANM", data_type=PostgresType.TEXT),
        PostgresColumn(name="EXTERNID", data_type=PostgresType.TEXT),
        PostgresColumn(name="EXTERNNR", data_type=PostgresType.TEXT),
        PostgresColumn(name="FORETAG", data_type=PostgresType.NUMERIC),
        PostgresColumn(name="FÖPROC_ID", data_type=PostgresType.TEXT),
        PostgresColumn(name="FÖRBEL_V", data_type=PostgresType.NUMERIC),
        PostgresColumn(name="HUVUDTEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="HÄND_ID", data_type=PostgresType.TEXT),
        PostgresColumn(name="IB", data_type=PostgresType.TEXT),
        PostgresColumn(name="IMOT_ID", data_type=PostgresType.TEXT),
        PostgresColumn(name="INTERNVERNR", data_type=PostgresType.NUMERIC),
        PostgresColumn(name="KASSA_ID", data_type=PostgresType.TEXT),
        PostgresColumn(name="KATEGORI", data_type=PostgresType.NUMERIC),
        PostgresColumn(name="KONTO_ID", data_type=PostgresType.TEXT),
        PostgresColumn(name="KONTSIGN", data_type=PostgresType.TEXT),
        PostgresColumn(name="KST_ID", data_type=PostgresType.TEXT),
        PostgresColumn(name="MED", data_type=PostgresType.NUMERIC),
        PostgresColumn(name="MOTP_ID", data_type=PostgresType.TEXT),
        PostgresColumn(name="ORGVAL_V", data_type=PostgresType.NUMERIC),
        PostgresColumn(name="PNYCKEL", data_type=PostgresType.TEXT),
        PostgresColumn(name="PROG_V", data_type=PostgresType.NUMERIC),
        PostgresColumn(name="PROR12_V", data_type=PostgresType.NUMERIC),
        PostgresColumn(name="RADTEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="RADTYPNR", data_type=PostgresType.NUMERIC),
        PostgresColumn(name="REGDAT_ID", data_type=PostgresType.TEXT),
        PostgresColumn(name="REGDATUM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="REGSIGN", data_type=PostgresType.TEXT),
        PostgresColumn(name="SID_ID", data_type=PostgresType.TEXT),
        PostgresColumn(name="STATUS", data_type=PostgresType.TEXT),
        PostgresColumn(name="TRID_ID", data_type=PostgresType.TEXT),
        PostgresColumn(name="URSPRUNGS_VERIFIKAT", data_type=PostgresType.TEXT),
        PostgresColumn(name="URSPTEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="UTFALL_V", data_type=PostgresType.NUMERIC),
        PostgresColumn(name="UTFUTL_V", data_type=PostgresType.NUMERIC),
        PostgresColumn(name="UTILITY", data_type=PostgresType.NUMERIC),
        PostgresColumn(name="VAL_ID", data_type=PostgresType.TEXT),
        PostgresColumn(name="VERDATUM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="VERDOKREF", data_type=PostgresType.TEXT),
        PostgresColumn(name="VERNR", data_type=PostgresType.NUMERIC),
        PostgresColumn(name="VERRAD", data_type=PostgresType.NUMERIC),
        PostgresColumn(name="VERTYP", data_type=PostgresType.TEXT),
        PostgresColumn(name="YRK_ID", data_type=PostgresType.TEXT),
    ],
    database=Database.POSTGRES,
    cron="0 6 * * *",
    tags=['slso', 'raindance', 'raw'],
)

def execute(env, cfg=config):
    if env.backfill and env.backfill.enabled:
        since = env.backfill.since.strftime("%Y-%m-%d")
        until = env.backfill.until.strftime("%Y-%m-%d")
    elif env.cron and env.cron.enabled:
        since = env.cron.since.strftime("%Y-%m-%d")
        until = env.cron.until.strftime("%Y-%m-%d")
    else:
        since = None
        until = None
    query=f"""SELECT * FROM (SELECT
    	CAST(VERDATUM AS DATE) as _data_modified,
    	CAST(GETDATE() AS DATETIME2) as _metadata_modified,
    	[AKT_ID] AS AKT_ID,
    	COALESCE([ATTESTDATUM1], '1899-12-31 00:00:00') AS ATTESTDATUM1,
    	COALESCE([ATTESTDATUM2], '1899-12-31 00:00:00') AS ATTESTDATUM2,
    	[ATTESTSIGN1] AS ATTESTSIGN1,
    	[ATTESTSIGN2] AS ATTESTSIGN2,
    	[AVT_ID] AS AVT_ID,
    	[BESTUT_V] AS BESTUT_V,
    	[BUDGET_V] AS BUDGET_V,
    	[BUDV2_V] AS BUDV2_V,
    	[DATUM_ID] AS DATUM_ID,
    	COALESCE([DEFDATUM], '1899-12-31 00:00:00') AS DEFDATUM,
    	[DEFSIGN] AS DEFSIGN,
    	[DOK_ANTAL] AS DOK_ANTAL,
    	[DOKTYP] AS DOKTYP,
    	[DOKUMENTID] AS DOKUMENTID,
    	[ERS_ID] AS ERS_ID,
    	[EXTERNANM] AS EXTERNANM,
    	[EXTERNID] AS EXTERNID,
    	[EXTERNNR] AS EXTERNNR,
    	[FORETAG] AS FORETAG,
    	[FÖPROC_ID] AS FÖPROC_ID,
    	[FÖRBEL_V] AS FÖRBEL_V,
    	[HUVUDTEXT] AS HUVUDTEXT,
    	[HÄND_ID] AS HÄND_ID,
    	[IB] AS IB,
    	[IMOT_ID] AS IMOT_ID,
    	[INTERNVERNR] AS INTERNVERNR,
    	[KASSA_ID] AS KASSA_ID,
    	[KATEGORI] AS KATEGORI,
    	[KONTO_ID] AS KONTO_ID,
    	[KONTSIGN] AS KONTSIGN,
    	[KST_ID] AS KST_ID,
    	[MED] AS MED,
    	[MOTP_ID] AS MOTP_ID,
    	[ORGVAL_V] AS ORGVAL_V,
    	[PNYCKEL] AS PNYCKEL,
    	[PROG_V] AS PROG_V,
    	[PROR12_V] AS PROR12_V,
    	[RADTEXT] AS RADTEXT,
    	[RADTYPNR] AS RADTYPNR,
    	[REGDAT_ID] AS REGDAT_ID,
    	COALESCE([REGDATUM], '1899-12-31 00:00:00') AS REGDATUM,
    	[REGSIGN] AS REGSIGN,
    	[SID_ID] AS SID_ID,
    	[STATUS] AS STATUS,
    	[TRID_ID] AS TRID_ID,
    	[URSPRUNGS_VERIFIKAT] AS URSPRUNGS_VERIFIKAT,
    	[URSPTEXT] AS URSPTEXT,
    	[UTFALL_V] AS UTFALL_V,
    	[UTFUTL_V] AS UTFUTL_V,
    	[UTILITY] AS UTILITY,
    	[VAL_ID] AS VAL_ID,
    	COALESCE([VERDATUM], '1899-12-31 00:00:00') AS VERDATUM,
    	[VERDOKREF] AS VERDOKREF,
    	[VERNR] AS VERNR,
    	[VERRAD] AS VERRAD,
    	[VERTYP] AS VERTYP,
    	[YRK_ID] AS YRK_ID
    FROM [udpb4].[udpb4_100].[EK_FAKTA_VERIFIKAT]) y
    WHERE _data_modified BETWEEN '{since}' AND '{until}'"""
    yield from read(query=query, env_var_name='RAINDANCE_1100')