from bollhav import Model, WriteMode
from bollhav.postgres import PostgresColumn, PostgresType
from bollhav.database import Database
from core import read

config = Model(
    name="ek_dim_obj_kto",
    source_entity="EK_DIM_OBJ_KTO",
    table="ek_dim_obj_kto",
    schema="raindance_raw_1500",
    write_mode=WriteMode.TRUNCATE_INSERT,
    columns=[
        PostgresColumn(name="_data_modified", data_type=PostgresType.DATE),
        PostgresColumn(name="_metadata_modified", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="FRANGO_GILTIG_FOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="FRANGO_GILTIG_TOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="FRANGO_ID", data_type=PostgresType.TEXT),
        PostgresColumn(name="FRANGO_ID_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="FRANGO_PASSIV", data_type=PostgresType.BOOLEAN),
        PostgresColumn(name="FRANGO_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="KGRUPP_GILTIG_FOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="KGRUPP_GILTIG_TOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="KGRUPP_ID", data_type=PostgresType.TEXT),
        PostgresColumn(name="KGRUPP_ID_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="KGRUPP_PASSIV", data_type=PostgresType.BOOLEAN),
        PostgresColumn(name="KGRUPP_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="KKL_GILTIG_FOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="KKL_GILTIG_TOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="KKL_ID", data_type=PostgresType.TEXT),
        PostgresColumn(name="KKL_ID_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="KKL_PASSIV", data_type=PostgresType.BOOLEAN),
        PostgresColumn(name="KKL_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="KTO_GILTIG_FOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="KTO_GILTIG_TOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="KTO_ID", data_type=PostgresType.TEXT),
        PostgresColumn(name="KTO_ID_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="KTO_PASSIV", data_type=PostgresType.BOOLEAN),
        PostgresColumn(name="KTO_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="STÖKGR_GILTIG_FOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="STÖKGR_GILTIG_TOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="STÖKGR_ID", data_type=PostgresType.TEXT),
        PostgresColumn(name="STÖKGR_ID_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="STÖKGR_PASSIV", data_type=PostgresType.BOOLEAN),
        PostgresColumn(name="STÖKGR_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="STÖKOD_GILTIG_FOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="STÖKOD_GILTIG_TOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="STÖKOD_ID", data_type=PostgresType.TEXT),
        PostgresColumn(name="STÖKOD_ID_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="STÖKOD_PASSIV", data_type=PostgresType.BOOLEAN),
        PostgresColumn(name="STÖKOD_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="TSIK_GILTIG_FOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="TSIK_GILTIG_TOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="TSIK_ID", data_type=PostgresType.TEXT),
        PostgresColumn(name="TSIK_ID_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="TSIK_PASSIV", data_type=PostgresType.BOOLEAN),
        PostgresColumn(name="TSIK_TEXT", data_type=PostgresType.TEXT),
    ],
    database=Database.POSTGRES,
    cron="0 6 * * *",
    tags=['hosn', 'raindance', 'raw'],
)

def execute(env, cfg=config):
    query=f"""SELECT * FROM (SELECT
    	CAST(GETDATE() AS DATE) as _data_modified,
    	CAST(GETDATE() AS DATETIME2) as _metadata_modified,
    	COALESCE([FRANGO_GILTIG_FOM], '1899-12-31 00:00:00') AS FRANGO_GILTIG_FOM,
    	COALESCE([FRANGO_GILTIG_TOM], '1899-12-31 00:00:00') AS FRANGO_GILTIG_TOM,
    	[FRANGO_ID] AS FRANGO_ID,
    	[FRANGO_ID_TEXT] AS FRANGO_ID_TEXT,
    	[FRANGO_PASSIV] AS FRANGO_PASSIV,
    	[FRANGO_TEXT] AS FRANGO_TEXT,
    	COALESCE([KGRUPP_GILTIG_FOM], '1899-12-31 00:00:00') AS KGRUPP_GILTIG_FOM,
    	COALESCE([KGRUPP_GILTIG_TOM], '1899-12-31 00:00:00') AS KGRUPP_GILTIG_TOM,
    	[KGRUPP_ID] AS KGRUPP_ID,
    	[KGRUPP_ID_TEXT] AS KGRUPP_ID_TEXT,
    	[KGRUPP_PASSIV] AS KGRUPP_PASSIV,
    	[KGRUPP_TEXT] AS KGRUPP_TEXT,
    	COALESCE([KKL_GILTIG_FOM], '1899-12-31 00:00:00') AS KKL_GILTIG_FOM,
    	COALESCE([KKL_GILTIG_TOM], '1899-12-31 00:00:00') AS KKL_GILTIG_TOM,
    	[KKL_ID] AS KKL_ID,
    	[KKL_ID_TEXT] AS KKL_ID_TEXT,
    	[KKL_PASSIV] AS KKL_PASSIV,
    	[KKL_TEXT] AS KKL_TEXT,
    	COALESCE([KTO_GILTIG_FOM], '1899-12-31 00:00:00') AS KTO_GILTIG_FOM,
    	COALESCE([KTO_GILTIG_TOM], '1899-12-31 00:00:00') AS KTO_GILTIG_TOM,
    	[KTO_ID] AS KTO_ID,
    	[KTO_ID_TEXT] AS KTO_ID_TEXT,
    	[KTO_PASSIV] AS KTO_PASSIV,
    	[KTO_TEXT] AS KTO_TEXT,
    	COALESCE([STÖKGR_GILTIG_FOM], '1899-12-31 00:00:00') AS STÖKGR_GILTIG_FOM,
    	COALESCE([STÖKGR_GILTIG_TOM], '1899-12-31 00:00:00') AS STÖKGR_GILTIG_TOM,
    	[STÖKGR_ID] AS STÖKGR_ID,
    	[STÖKGR_ID_TEXT] AS STÖKGR_ID_TEXT,
    	[STÖKGR_PASSIV] AS STÖKGR_PASSIV,
    	[STÖKGR_TEXT] AS STÖKGR_TEXT,
    	COALESCE([STÖKOD_GILTIG_FOM], '1899-12-31 00:00:00') AS STÖKOD_GILTIG_FOM,
    	COALESCE([STÖKOD_GILTIG_TOM], '1899-12-31 00:00:00') AS STÖKOD_GILTIG_TOM,
    	[STÖKOD_ID] AS STÖKOD_ID,
    	[STÖKOD_ID_TEXT] AS STÖKOD_ID_TEXT,
    	[STÖKOD_PASSIV] AS STÖKOD_PASSIV,
    	[STÖKOD_TEXT] AS STÖKOD_TEXT,
    	COALESCE([TSIK_GILTIG_FOM], '1899-12-31 00:00:00') AS TSIK_GILTIG_FOM,
    	COALESCE([TSIK_GILTIG_TOM], '1899-12-31 00:00:00') AS TSIK_GILTIG_TOM,
    	[TSIK_ID] AS TSIK_ID,
    	[TSIK_ID_TEXT] AS TSIK_ID_TEXT,
    	[TSIK_PASSIV] AS TSIK_PASSIV,
    	[TSIK_TEXT] AS TSIK_TEXT
    FROM [utdata].[utdata150].[EK_DIM_OBJ_KTO]) y
    WHERE 1=1"""
    yield from read(query=query, env_var_name='RAINDANCE_1500')