from bollhav import Model, WriteMode
from bollhav.postgres import PostgresColumn, PostgresType
from bollhav.database import Database
from core import read, write
from roskarl.marshal import with_env_config, EnvConfig
from roskarl import env_var_dsn

config = Model(
    name="rk_dim_lev",
    source_entity="RK_DIM_LEV",
    table="rk_dim_lev",
    schema="raindance_raw_1500",
    write_mode=WriteMode.TRUNCATE_INSERT,
    columns=[
        PostgresColumn(name="_data_modified", data_type=PostgresType.DATE),
        PostgresColumn(name="_metadata_modified", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="ADR1", data_type=PostgresType.TEXT),
        PostgresColumn(name="ADR2", data_type=PostgresType.TEXT),
        PostgresColumn(name="ATTRIBUTE_ACTORID", data_type=PostgresType.TEXT),
        PostgresColumn(name="ATTRIBUTE_EAN", data_type=PostgresType.TEXT),
        PostgresColumn(name="BANKADR", data_type=PostgresType.TEXT),
        PostgresColumn(name="BANKKONTO", data_type=PostgresType.TEXT),
        PostgresColumn(name="BANKLAND", data_type=PostgresType.TEXT),
        PostgresColumn(name="BANKNAMN", data_type=PostgresType.TEXT),
        PostgresColumn(name="BANKORT", data_type=PostgresType.TEXT),
        PostgresColumn(name="BBAN", data_type=PostgresType.TEXT),
        PostgresColumn(name="BETALVAG", data_type=PostgresType.NUMERIC),
        PostgresColumn(name="BETSPARR", data_type=PostgresType.BOOLEAN),
        PostgresColumn(name="BGNR", data_type=PostgresType.TEXT),
        PostgresColumn(name="BIC", data_type=PostgresType.TEXT),
        PostgresColumn(name="DUMMY1", data_type=PostgresType.TEXT),
        PostgresColumn(name="ELEKTRONISK_KOMMUNIKATION", data_type=PostgresType.TEXT),
        PostgresColumn(name="ENGANG", data_type=PostgresType.BOOLEAN),
        PostgresColumn(name="FACBG", data_type=PostgresType.TEXT),
        PostgresColumn(name="FACNAMN", data_type=PostgresType.TEXT),
        PostgresColumn(name="FACPG", data_type=PostgresType.TEXT),
        PostgresColumn(name="FRI1", data_type=PostgresType.TEXT),
        PostgresColumn(name="FRI2", data_type=PostgresType.TEXT),
        PostgresColumn(name="FRI3", data_type=PostgresType.TEXT),
        PostgresColumn(name="FRI4", data_type=PostgresType.TEXT),
        PostgresColumn(name="GRUPP", data_type=PostgresType.TEXT),
        PostgresColumn(name="IBAN", data_type=PostgresType.TEXT),
        PostgresColumn(name="KREDITLIMIT", data_type=PostgresType.NUMERIC),
        PostgresColumn(name="LAND", data_type=PostgresType.TEXT),
        PostgresColumn(name="LEV_EREF", data_type=PostgresType.TEXT),
        PostgresColumn(name="LEV_TAB_ABONID", data_type=PostgresType.TEXT),
        PostgresColumn(name="LEV_TAB_BEHÄND", data_type=PostgresType.TEXT),
        PostgresColumn(name="LEV_TAB_BETV", data_type=PostgresType.TEXT),
        PostgresColumn(name="LEV_TAB_BEVAK", data_type=PostgresType.TEXT),
        PostgresColumn(name="LEV_TAB_CMALL", data_type=PostgresType.TEXT),
        PostgresColumn(name="LEV_TAB_DEBKRE", data_type=PostgresType.TEXT),
        PostgresColumn(name="LEV_TAB_FÖRK", data_type=PostgresType.TEXT),
        PostgresColumn(name="LEV_TAB_HANDL", data_type=PostgresType.TEXT),
        PostgresColumn(name="LEV_TAB_MOMS", data_type=PostgresType.TEXT),
        PostgresColumn(name="LEV_TAB_MOTP", data_type=PostgresType.TEXT),
        PostgresColumn(name="LEV_TAB_REF", data_type=PostgresType.TEXT),
        PostgresColumn(name="LEV_TAB_RESEN2", data_type=PostgresType.TEXT),
        PostgresColumn(name="LEV_TAB_RESENH", data_type=PostgresType.TEXT),
        PostgresColumn(name="LEV_TAB_RESK", data_type=PostgresType.TEXT),
        PostgresColumn(name="LEV_TAB_SCADAT", data_type=PostgresType.TEXT),
        PostgresColumn(name="LEV_TAB_SCANNR", data_type=PostgresType.TEXT),
        PostgresColumn(name="LEV_TAB_UBF", data_type=PostgresType.TEXT),
        PostgresColumn(name="LEV_TAB_UBK", data_type=PostgresType.TEXT),
        PostgresColumn(name="LEV_TAB_VALUTA", data_type=PostgresType.TEXT),
        PostgresColumn(name="LEV_VREF", data_type=PostgresType.TEXT),
        PostgresColumn(name="LEVID", data_type=PostgresType.TEXT),
        PostgresColumn(name="LEVID2", data_type=PostgresType.TEXT),
        PostgresColumn(name="LEVID_ID_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="LEVID_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="MOMSREG", data_type=PostgresType.TEXT),
        PostgresColumn(name="MSG_DESADV_FORMAT", data_type=PostgresType.TEXT),
        PostgresColumn(name="MSG_DESADV_PA", data_type=PostgresType.TEXT),
        PostgresColumn(name="MSG_DESADV_TRANSPORT", data_type=PostgresType.TEXT),
        PostgresColumn(name="MSG_DESADV_VAG", data_type=PostgresType.TEXT),
        PostgresColumn(name="MSG_EXTORD_FORMAT", data_type=PostgresType.TEXT),
        PostgresColumn(name="MSG_EXTORD_PA", data_type=PostgresType.TEXT),
        PostgresColumn(name="MSG_EXTORD_TRANSPORT", data_type=PostgresType.TEXT),
        PostgresColumn(name="MSG_EXTORD_VAG", data_type=PostgresType.TEXT),
        PostgresColumn(name="MSG_INVOIC_FORMAT", data_type=PostgresType.TEXT),
        PostgresColumn(name="MSG_INVOIC_PA", data_type=PostgresType.TEXT),
        PostgresColumn(name="MSG_INVOIC_TRANSPORT", data_type=PostgresType.TEXT),
        PostgresColumn(name="MSG_INVOIC_VAG", data_type=PostgresType.TEXT),
        PostgresColumn(name="MSG_MSCONS_FORMAT", data_type=PostgresType.TEXT),
        PostgresColumn(name="MSG_MSCONS_PA", data_type=PostgresType.TEXT),
        PostgresColumn(name="MSG_MSCONS_TRANSPORT", data_type=PostgresType.TEXT),
        PostgresColumn(name="MSG_MSCONS_VAG", data_type=PostgresType.TEXT),
        PostgresColumn(name="MSG_ORDERS_FORMAT", data_type=PostgresType.TEXT),
        PostgresColumn(name="MSG_ORDERS_PA", data_type=PostgresType.TEXT),
        PostgresColumn(name="MSG_ORDERS_TRANSPORT", data_type=PostgresType.TEXT),
        PostgresColumn(name="MSG_ORDERS_VAG", data_type=PostgresType.TEXT),
        PostgresColumn(name="MSG_ORDRSP_FORMAT", data_type=PostgresType.TEXT),
        PostgresColumn(name="MSG_ORDRSP_PA", data_type=PostgresType.TEXT),
        PostgresColumn(name="MSG_ORDRSP_TRANSPORT", data_type=PostgresType.TEXT),
        PostgresColumn(name="MSG_ORDRSP_VAG", data_type=PostgresType.TEXT),
        PostgresColumn(name="MSG_PRICAT_FORMAT", data_type=PostgresType.TEXT),
        PostgresColumn(name="MSG_PRICAT_PA", data_type=PostgresType.TEXT),
        PostgresColumn(name="MSG_PRICAT_TRANSPORT", data_type=PostgresType.TEXT),
        PostgresColumn(name="MSG_PRICAT_VAG", data_type=PostgresType.TEXT),
        PostgresColumn(name="MSG_SHOPCART_FORMAT", data_type=PostgresType.TEXT),
        PostgresColumn(name="MSG_SHOPCART_PA", data_type=PostgresType.TEXT),
        PostgresColumn(name="MSG_SHOPCART_TRANSPORT", data_type=PostgresType.TEXT),
        PostgresColumn(name="MSG_SHOPCART_VAG", data_type=PostgresType.TEXT),
        PostgresColumn(name="NAMN2", data_type=PostgresType.TEXT),
        PostgresColumn(name="NATCLEARKOD", data_type=PostgresType.TEXT),
        PostgresColumn(name="OMSATTNING", data_type=PostgresType.NUMERIC),
        PostgresColumn(name="OMSATTNING_FG", data_type=PostgresType.NUMERIC),
        PostgresColumn(name="OMSATTNINGSAR", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="ORGNR", data_type=PostgresType.TEXT),
        PostgresColumn(name="ORT", data_type=PostgresType.TEXT),
        PostgresColumn(name="PASSIV", data_type=PostgresType.BOOLEAN),
        PostgresColumn(name="PGNR", data_type=PostgresType.TEXT),
        PostgresColumn(name="SALDO", data_type=PostgresType.NUMERIC),
        PostgresColumn(name="SEPA", data_type=PostgresType.BOOLEAN),
        PostgresColumn(name="SOKBEGR", data_type=PostgresType.TEXT),
        PostgresColumn(name="SWIFTADR", data_type=PostgresType.TEXT),
        PostgresColumn(name="TELNR", data_type=PostgresType.TEXT),
        PostgresColumn(name="TERMIN", data_type=PostgresType.TEXT),
    ],
    database=Database.POSTGRES,
    cron="0 6 * * *",
    tags=['hosn', 'raindance', 'raw'],
)

@with_env_config
def execute(env: EnvConfig, cfg=config):
    dest_dsn = env_var_dsn("BIG_EKONOMI_EXECUTION_PROD")
    query = """
    SELECT
	CAST(GETDATE() AS DATE) as _data_modified,
	CAST(GETDATE() AS DATETIME2) as _metadata_modified,
	[ADR1] AS ADR1,
	[ADR2] AS ADR2,
	[ATTRIBUTE_ACTORID] AS ATTRIBUTE_ACTORID,
	[ATTRIBUTE_EAN] AS ATTRIBUTE_EAN,
	[BANKADR] AS BANKADR,
	[BANKKONTO] AS BANKKONTO,
	[BANKLAND] AS BANKLAND,
	[BANKNAMN] AS BANKNAMN,
	[BANKORT] AS BANKORT,
	[BBAN] AS BBAN,
	[BETALVAG] AS BETALVAG,
	[BETSPARR] AS BETSPARR,
	[BGNR] AS BGNR,
	[BIC] AS BIC,
	[DUMMY1] AS DUMMY1,
	[ELEKTRONISK_KOMMUNIKATION] AS ELEKTRONISK_KOMMUNIKATION,
	[ENGANG] AS ENGANG,
	[FACBG] AS FACBG,
	[FACNAMN] AS FACNAMN,
	[FACPG] AS FACPG,
	[FRI1] AS FRI1,
	[FRI2] AS FRI2,
	[FRI3] AS FRI3,
	[FRI4] AS FRI4,
	[GRUPP] AS GRUPP,
	[IBAN] AS IBAN,
	[KREDITLIMIT] AS KREDITLIMIT,
	[LAND] AS LAND,
	[LEV_EREF] AS LEV_EREF,
	[LEV_TAB_ABONID] AS LEV_TAB_ABONID,
	[LEV_TAB_BEHÄND] AS LEV_TAB_BEHÄND,
	[LEV_TAB_BETV] AS LEV_TAB_BETV,
	[LEV_TAB_BEVAK] AS LEV_TAB_BEVAK,
	[LEV_TAB_CMALL] AS LEV_TAB_CMALL,
	[LEV_TAB_DEBKRE] AS LEV_TAB_DEBKRE,
	[LEV_TAB_FÖRK] AS LEV_TAB_FÖRK,
	[LEV_TAB_HANDL] AS LEV_TAB_HANDL,
	[LEV_TAB_MOMS] AS LEV_TAB_MOMS,
	[LEV_TAB_MOTP] AS LEV_TAB_MOTP,
	[LEV_TAB_REF] AS LEV_TAB_REF,
	[LEV_TAB_RESEN2] AS LEV_TAB_RESEN2,
	[LEV_TAB_RESENH] AS LEV_TAB_RESENH,
	[LEV_TAB_RESK] AS LEV_TAB_RESK,
	[LEV_TAB_SCADAT] AS LEV_TAB_SCADAT,
	[LEV_TAB_SCANNR] AS LEV_TAB_SCANNR,
	[LEV_TAB_UBF] AS LEV_TAB_UBF,
	[LEV_TAB_UBK] AS LEV_TAB_UBK,
	[LEV_TAB_VALUTA] AS LEV_TAB_VALUTA,
	[LEV_VREF] AS LEV_VREF,
	[LEVID] AS LEVID,
	[LEVID2] AS LEVID2,
	[LEVID_ID_TEXT] AS LEVID_ID_TEXT,
	[LEVID_TEXT] AS LEVID_TEXT,
	[MOMSREG] AS MOMSREG,
	[MSG_DESADV_FORMAT] AS MSG_DESADV_FORMAT,
	[MSG_DESADV_PA] AS MSG_DESADV_PA,
	[MSG_DESADV_TRANSPORT] AS MSG_DESADV_TRANSPORT,
	[MSG_DESADV_VAG] AS MSG_DESADV_VAG,
	[MSG_EXTORD_FORMAT] AS MSG_EXTORD_FORMAT,
	[MSG_EXTORD_PA] AS MSG_EXTORD_PA,
	[MSG_EXTORD_TRANSPORT] AS MSG_EXTORD_TRANSPORT,
	[MSG_EXTORD_VAG] AS MSG_EXTORD_VAG,
	[MSG_INVOIC_FORMAT] AS MSG_INVOIC_FORMAT,
	[MSG_INVOIC_PA] AS MSG_INVOIC_PA,
	[MSG_INVOIC_TRANSPORT] AS MSG_INVOIC_TRANSPORT,
	[MSG_INVOIC_VAG] AS MSG_INVOIC_VAG,
	[MSG_MSCONS_FORMAT] AS MSG_MSCONS_FORMAT,
	[MSG_MSCONS_PA] AS MSG_MSCONS_PA,
	[MSG_MSCONS_TRANSPORT] AS MSG_MSCONS_TRANSPORT,
	[MSG_MSCONS_VAG] AS MSG_MSCONS_VAG,
	[MSG_ORDERS_FORMAT] AS MSG_ORDERS_FORMAT,
	[MSG_ORDERS_PA] AS MSG_ORDERS_PA,
	[MSG_ORDERS_TRANSPORT] AS MSG_ORDERS_TRANSPORT,
	[MSG_ORDERS_VAG] AS MSG_ORDERS_VAG,
	[MSG_ORDRSP_FORMAT] AS MSG_ORDRSP_FORMAT,
	[MSG_ORDRSP_PA] AS MSG_ORDRSP_PA,
	[MSG_ORDRSP_TRANSPORT] AS MSG_ORDRSP_TRANSPORT,
	[MSG_ORDRSP_VAG] AS MSG_ORDRSP_VAG,
	[MSG_PRICAT_FORMAT] AS MSG_PRICAT_FORMAT,
	[MSG_PRICAT_PA] AS MSG_PRICAT_PA,
	[MSG_PRICAT_TRANSPORT] AS MSG_PRICAT_TRANSPORT,
	[MSG_PRICAT_VAG] AS MSG_PRICAT_VAG,
	[MSG_SHOPCART_FORMAT] AS MSG_SHOPCART_FORMAT,
	[MSG_SHOPCART_PA] AS MSG_SHOPCART_PA,
	[MSG_SHOPCART_TRANSPORT] AS MSG_SHOPCART_TRANSPORT,
	[MSG_SHOPCART_VAG] AS MSG_SHOPCART_VAG,
	[NAMN2] AS NAMN2,
	[NATCLEARKOD] AS NATCLEARKOD,
	[OMSATTNING] AS OMSATTNING,
	[OMSATTNING_FG] AS OMSATTNING_FG,
	COALESCE([OMSATTNINGSAR], '1899-12-31 00:00:00') AS OMSATTNINGSAR,
	[ORGNR] AS ORGNR,
	[ORT] AS ORT,
	[PASSIV] AS PASSIV,
	[PGNR] AS PGNR,
	[SALDO] AS SALDO,
	[SEPA] AS SEPA,
	[SOKBEGR] AS SOKBEGR,
	[SWIFTADR] AS SWIFTADR,
	[TELNR] AS TELNR,
	[TERMIN] AS TERMIN
    FROM [utdata].[utdata150].[RK_DIM_LEV]

    """
    total_rows = 0
    first_batch = True
    for df in read("RAINDANCE_1500", query):
        if len(df) == 0:
            continue
        write(cfg, df, dest_dsn)
        if first_batch:
            cfg.write_mode = WriteMode.APPEND
            first_batch = False
        total_rows += len(df)
    print(f"  ✓ {cfg.name}: {total_rows:,} rows written" if total_rows else f"  ⏭ {cfg.name}: no data, skipping")