from bollhav import Model, WriteMode
from bollhav.postgres import PostgresColumn, PostgresType
from bollhav.database import Database
from core import read

config = Model(
    name="rk_fakta_levfakt_verifikat",
    source_entity="RK_FAKTA_LEVFAKT_VERIFIKAT",
    table="rk_fakta_levfakt_verifikat",
    schema="raindance_raw_1500",
    write_mode=WriteMode.MERGE,
    columns=[
        PostgresColumn(name="_data_modified", data_type=PostgresType.DATE),
        PostgresColumn(name="_metadata_modified", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="ANS_ID", data_type=PostgresType.TEXT),
        PostgresColumn(name="ATTEST", data_type=PostgresType.BOOLEAN),
        PostgresColumn(name="ATTESTDATUM1", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="ATTESTDATUM2", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="ATTESTSIGN1", data_type=PostgresType.TEXT),
        PostgresColumn(name="ATTESTSIGN2", data_type=PostgresType.TEXT),
        PostgresColumn(name="AVT_ID", data_type=PostgresType.TEXT),
        PostgresColumn(name="AVTALID", data_type=PostgresType.TEXT),
        PostgresColumn(name="BELOPP_SEK", data_type=PostgresType.NUMERIC),
        PostgresColumn(name="BELOPP_VAL", data_type=PostgresType.NUMERIC),
        PostgresColumn(name="BETALNINGSSPARR", data_type=PostgresType.BOOLEAN),
        PostgresColumn(name="BETALT_SEK", data_type=PostgresType.NUMERIC),
        PostgresColumn(name="BETALT_VAL", data_type=PostgresType.NUMERIC),
        PostgresColumn(name="BETDAGAR", data_type=PostgresType.NUMERIC),
        PostgresColumn(name="BPUTF_V", data_type=PostgresType.NUMERIC),
        PostgresColumn(name="BUD_V", data_type=PostgresType.NUMERIC),
        PostgresColumn(name="BUDPRE_V", data_type=PostgresType.NUMERIC),
        PostgresColumn(name="DATUM_ID", data_type=PostgresType.TEXT),
        PostgresColumn(name="DEFDATUM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="DEFSIGN", data_type=PostgresType.TEXT),
        PostgresColumn(name="DOK_ANTAL", data_type=PostgresType.NUMERIC),
        PostgresColumn(name="DOKTYP", data_type=PostgresType.NUMERIC),
        PostgresColumn(name="DOKUMENTID", data_type=PostgresType.TEXT),
        PostgresColumn(name="DOMÄN_ID", data_type=PostgresType.TEXT),
        PostgresColumn(name="EREF", data_type=PostgresType.TEXT),
        PostgresColumn(name="EXTERNANM", data_type=PostgresType.TEXT),
        PostgresColumn(name="EXTERNID", data_type=PostgresType.TEXT),
        PostgresColumn(name="EXTERNNR", data_type=PostgresType.TEXT),
        PostgresColumn(name="F_DOK_ANTAL", data_type=PostgresType.NUMERIC),
        PostgresColumn(name="F_MED", data_type=PostgresType.NUMERIC),
        PostgresColumn(name="FAKTSTATUS", data_type=PostgresType.TEXT),
        PostgresColumn(name="FAKTURA_REGDATUM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="FAKTURADATUM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="FORETAG", data_type=PostgresType.NUMERIC),
        PostgresColumn(name="FORFALLODATUM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="FRI_ID", data_type=PostgresType.TEXT),
        PostgresColumn(name="FÖPROC_ID", data_type=PostgresType.TEXT),
        PostgresColumn(name="FÖRBEL_V", data_type=PostgresType.NUMERIC),
        PostgresColumn(name="GEO_ID", data_type=PostgresType.TEXT),
        PostgresColumn(name="HUVUDTEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="IB", data_type=PostgresType.TEXT),
        PostgresColumn(name="INTERNVERNR", data_type=PostgresType.NUMERIC),
        PostgresColumn(name="KATEGORI", data_type=PostgresType.NUMERIC),
        PostgresColumn(name="KONTSIGN", data_type=PostgresType.TEXT),
        PostgresColumn(name="KRAVNIVA", data_type=PostgresType.NUMERIC),
        PostgresColumn(name="KTO_ID", data_type=PostgresType.TEXT),
        PostgresColumn(name="LEV_ID", data_type=PostgresType.TEXT),
        PostgresColumn(name="LEVID", data_type=PostgresType.TEXT),
        PostgresColumn(name="LEVRTYP", data_type=PostgresType.TEXT),
        PostgresColumn(name="MED", data_type=PostgresType.NUMERIC),
        PostgresColumn(name="MOMS_SEK", data_type=PostgresType.NUMERIC),
        PostgresColumn(name="MOMS_VAL", data_type=PostgresType.NUMERIC),
        PostgresColumn(name="MOTP_ID", data_type=PostgresType.TEXT),
        PostgresColumn(name="MOTTATTDAT", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="MOTTATTSIGN", data_type=PostgresType.TEXT),
        PostgresColumn(name="NR", data_type=PostgresType.NUMERIC),
        PostgresColumn(name="OCRNR", data_type=PostgresType.TEXT),
        PostgresColumn(name="ORGVAL_V", data_type=PostgresType.NUMERIC),
        PostgresColumn(name="OVERDRDAGAR", data_type=PostgresType.NUMERIC),
        PostgresColumn(name="PNYCKEL", data_type=PostgresType.TEXT),
        PostgresColumn(name="PRG_V", data_type=PostgresType.NUMERIC),
        PostgresColumn(name="PROC_ID", data_type=PostgresType.TEXT),
        PostgresColumn(name="PROJ_ID", data_type=PostgresType.TEXT),
        PostgresColumn(name="PROJUT_V", data_type=PostgresType.NUMERIC),
        PostgresColumn(name="RADTEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="RADTYPNR", data_type=PostgresType.NUMERIC),
        PostgresColumn(name="RANTEDEB", data_type=PostgresType.BOOLEAN),
        PostgresColumn(name="REGDAT_ID", data_type=PostgresType.TEXT),
        PostgresColumn(name="REGDATUM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="REGSIGN", data_type=PostgresType.TEXT),
        PostgresColumn(name="SENASTBETDATUM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="STATUS", data_type=PostgresType.TEXT),
        PostgresColumn(name="TAB_ABONID", data_type=PostgresType.TEXT),
        PostgresColumn(name="TAB_BEHÄND", data_type=PostgresType.TEXT),
        PostgresColumn(name="TAB_BETV", data_type=PostgresType.TEXT),
        PostgresColumn(name="TAB_CMALL", data_type=PostgresType.TEXT),
        PostgresColumn(name="TAB_DEBKRE", data_type=PostgresType.TEXT),
        PostgresColumn(name="TAB_FÖRK", data_type=PostgresType.TEXT),
        PostgresColumn(name="TAB_HANDL", data_type=PostgresType.TEXT),
        PostgresColumn(name="TAB_MOMS", data_type=PostgresType.TEXT),
        PostgresColumn(name="TAB_MOTP", data_type=PostgresType.TEXT),
        PostgresColumn(name="TAB_REF", data_type=PostgresType.TEXT),
        PostgresColumn(name="TAB_RESEN2", data_type=PostgresType.TEXT),
        PostgresColumn(name="TAB_RESENH", data_type=PostgresType.TEXT),
        PostgresColumn(name="TAB_RESK", data_type=PostgresType.TEXT),
        PostgresColumn(name="TAB_SCADAT", data_type=PostgresType.TEXT),
        PostgresColumn(name="TAB_SCANNR", data_type=PostgresType.TEXT),
        PostgresColumn(name="TAB_UBF", data_type=PostgresType.TEXT),
        PostgresColumn(name="TAB_UBK", data_type=PostgresType.TEXT),
        PostgresColumn(name="TAB_VALUTA", data_type=PostgresType.TEXT),
        PostgresColumn(name="UPPID_ID", data_type=PostgresType.TEXT),
        PostgresColumn(name="UPT_ID", data_type=PostgresType.TEXT),
        PostgresColumn(name="URS_ID", data_type=PostgresType.TEXT),
        PostgresColumn(name="URSPRUNGS_VERIFIKAT", data_type=PostgresType.TEXT),
        PostgresColumn(name="URSPTEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="UTF_V", data_type=PostgresType.NUMERIC),
        PostgresColumn(name="UTILITY", data_type=PostgresType.NUMERIC),
        PostgresColumn(name="UTSKRDATUM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="V_ID", data_type=PostgresType.TEXT),
        PostgresColumn(name="VALUTA_ID", data_type=PostgresType.TEXT),
        PostgresColumn(name="VERDATUM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="VERDOKREF", data_type=PostgresType.TEXT),
        PostgresColumn(name="VERNR", data_type=PostgresType.NUMERIC),
        PostgresColumn(name="VERRAD", data_type=PostgresType.NUMERIC),
        PostgresColumn(name="VERTYP", data_type=PostgresType.TEXT),
        PostgresColumn(name="VREF", data_type=PostgresType.TEXT),
    ],
    database=Database.POSTGRES,
    cron="0 6 * * *",
    tags=['hosn', 'raindance', 'raw'],
)

def execute(env, cfg=config):
    if env.backfill and env.backfill.enabled:
        since = env.backfill.since.strftime("%Y-%m-%d")
        until = env.backfill.until.strftime("%Y-%m-%d")
    elif env.cron and env.cron.enabled:
        since = env.cron.since.strftime("%Y-%m-%d")
        until = env.cron.until.strftime("%Y-%m-%d")
    else:
        since = None
        until = None
    query=f"""SELECT * FROM (SELECT
    	CAST(VERDATUM AS DATE) as _data_modified,
    	CAST(GETDATE() AS DATETIME2) as _metadata_modified,
    	[ANS_ID] AS ANS_ID,
    	[ATTEST] AS ATTEST,
    	COALESCE([ATTESTDATUM1], '1899-12-31 00:00:00') AS ATTESTDATUM1,
    	COALESCE([ATTESTDATUM2], '1899-12-31 00:00:00') AS ATTESTDATUM2,
    	[ATTESTSIGN1] AS ATTESTSIGN1,
    	[ATTESTSIGN2] AS ATTESTSIGN2,
    	[AVT_ID] AS AVT_ID,
    	[AVTALID] AS AVTALID,
    	[BELOPP_SEK] AS BELOPP_SEK,
    	[BELOPP_VAL] AS BELOPP_VAL,
    	[BETALNINGSSPARR] AS BETALNINGSSPARR,
    	[BETALT_SEK] AS BETALT_SEK,
    	[BETALT_VAL] AS BETALT_VAL,
    	[BETDAGAR] AS BETDAGAR,
    	[BPUTF_V] AS BPUTF_V,
    	[BUD_V] AS BUD_V,
    	[BUDPRE_V] AS BUDPRE_V,
    	[DATUM_ID] AS DATUM_ID,
    	COALESCE([DEFDATUM], '1899-12-31 00:00:00') AS DEFDATUM,
    	[DEFSIGN] AS DEFSIGN,
    	[DOK_ANTAL] AS DOK_ANTAL,
    	[DOKTYP] AS DOKTYP,
    	[DOKUMENTID] AS DOKUMENTID,
    	[DOMÄN_ID] AS DOMÄN_ID,
    	[EREF] AS EREF,
    	[EXTERNANM] AS EXTERNANM,
    	[EXTERNID] AS EXTERNID,
    	[EXTERNNR] AS EXTERNNR,
    	[F_DOK_ANTAL] AS F_DOK_ANTAL,
    	[F_MED] AS F_MED,
    	[FAKTSTATUS] AS FAKTSTATUS,
    	COALESCE([FAKTURA_REGDATUM], '1899-12-31 00:00:00') AS FAKTURA_REGDATUM,
    	COALESCE([FAKTURADATUM], '1899-12-31 00:00:00') AS FAKTURADATUM,
    	[FORETAG] AS FORETAG,
    	COALESCE([FORFALLODATUM], '1899-12-31 00:00:00') AS FORFALLODATUM,
    	[FRI_ID] AS FRI_ID,
    	[FÖPROC_ID] AS FÖPROC_ID,
    	[FÖRBEL_V] AS FÖRBEL_V,
    	[GEO_ID] AS GEO_ID,
    	[HUVUDTEXT] AS HUVUDTEXT,
    	[IB] AS IB,
    	[INTERNVERNR] AS INTERNVERNR,
    	[KATEGORI] AS KATEGORI,
    	[KONTSIGN] AS KONTSIGN,
    	[KRAVNIVA] AS KRAVNIVA,
    	[KTO_ID] AS KTO_ID,
    	[LEV_ID] AS LEV_ID,
    	[LEVID] AS LEVID,
    	[LEVRTYP] AS LEVRTYP,
    	[MED] AS MED,
    	[MOMS_SEK] AS MOMS_SEK,
    	[MOMS_VAL] AS MOMS_VAL,
    	[MOTP_ID] AS MOTP_ID,
    	COALESCE([MOTTATTDAT], '1899-12-31 00:00:00') AS MOTTATTDAT,
    	[MOTTATTSIGN] AS MOTTATTSIGN,
    	[NR] AS NR,
    	[OCRNR] AS OCRNR,
    	[ORGVAL_V] AS ORGVAL_V,
    	[OVERDRDAGAR] AS OVERDRDAGAR,
    	[PNYCKEL] AS PNYCKEL,
    	[PRG_V] AS PRG_V,
    	[PROC_ID] AS PROC_ID,
    	[PROJ_ID] AS PROJ_ID,
    	[PROJUT_V] AS PROJUT_V,
    	[RADTEXT] AS RADTEXT,
    	[RADTYPNR] AS RADTYPNR,
    	[RANTEDEB] AS RANTEDEB,
    	[REGDAT_ID] AS REGDAT_ID,
    	COALESCE([REGDATUM], '1899-12-31 00:00:00') AS REGDATUM,
    	[REGSIGN] AS REGSIGN,
    	COALESCE([SENASTBETDATUM], '1899-12-31 00:00:00') AS SENASTBETDATUM,
    	[STATUS] AS STATUS,
    	[TAB_ABONID] AS TAB_ABONID,
    	[TAB_BEHÄND] AS TAB_BEHÄND,
    	[TAB_BETV] AS TAB_BETV,
    	[TAB_CMALL] AS TAB_CMALL,
    	[TAB_DEBKRE] AS TAB_DEBKRE,
    	[TAB_FÖRK] AS TAB_FÖRK,
    	[TAB_HANDL] AS TAB_HANDL,
    	[TAB_MOMS] AS TAB_MOMS,
    	[TAB_MOTP] AS TAB_MOTP,
    	[TAB_REF] AS TAB_REF,
    	[TAB_RESEN2] AS TAB_RESEN2,
    	[TAB_RESENH] AS TAB_RESENH,
    	[TAB_RESK] AS TAB_RESK,
    	[TAB_SCADAT] AS TAB_SCADAT,
    	[TAB_SCANNR] AS TAB_SCANNR,
    	[TAB_UBF] AS TAB_UBF,
    	[TAB_UBK] AS TAB_UBK,
    	[TAB_VALUTA] AS TAB_VALUTA,
    	[UPPID_ID] AS UPPID_ID,
    	[UPT_ID] AS UPT_ID,
    	[URS_ID] AS URS_ID,
    	[URSPRUNGS_VERIFIKAT] AS URSPRUNGS_VERIFIKAT,
    	[URSPTEXT] AS URSPTEXT,
    	[UTF_V] AS UTF_V,
    	[UTILITY] AS UTILITY,
    	COALESCE([UTSKRDATUM], '1899-12-31 00:00:00') AS UTSKRDATUM,
    	[V_ID] AS V_ID,
    	[VALUTA_ID] AS VALUTA_ID,
    	COALESCE([VERDATUM], '1899-12-31 00:00:00') AS VERDATUM,
    	[VERDOKREF] AS VERDOKREF,
    	[VERNR] AS VERNR,
    	[VERRAD] AS VERRAD,
    	[VERTYP] AS VERTYP,
    	[VREF] AS VREF
    FROM [utdata].[utdata150].[RK_FAKTA_LEVFAKT_VERIFIKAT]) y
    WHERE _data_modified BETWEEN '{since}' AND '{until}'"""
    yield from read(query=query, env_var_name='RAINDANCE_1500')