from bollhav import Model, WriteMode
from bollhav.postgres import PostgresColumn, PostgresType
from bollhav.database import Database
from core import read, write
from roskarl.marshal import with_env_config, EnvConfig
from roskarl import env_var_dsn

config = Model(
    name="ek_dim_obj_konto",
    source_entity="EK_DIM_OBJ_KONTO",
    table="ek_dim_obj_konto",
    schema="raindance_raw_8580",
    write_mode=WriteMode.TRUNCATE_INSERT,
    columns=[
        PostgresColumn(name="_data_modified", data_type=PostgresType.DATE),
        PostgresColumn(name="_metadata_modified", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="ANSELI_GILTIG_FOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="ANSELI_GILTIG_TOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="ANSELI_ID", data_type=PostgresType.TEXT),
        PostgresColumn(name="ANSELI_ID_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="ANSELI_PASSIV", data_type=PostgresType.BOOLEAN),
        PostgresColumn(name="ANSELI_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="ELSJKH_GILTIG_FOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="ELSJKH_GILTIG_TOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="ELSJKH_ID", data_type=PostgresType.TEXT),
        PostgresColumn(name="ELSJKH_ID_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="ELSJKH_PASSIV", data_type=PostgresType.BOOLEAN),
        PostgresColumn(name="ELSJKH_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="FRAGRP_GILTIG_FOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="FRAGRP_GILTIG_TOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="FRAGRP_ID", data_type=PostgresType.TEXT),
        PostgresColumn(name="FRAGRP_ID_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="FRAGRP_PASSIV", data_type=PostgresType.BOOLEAN),
        PostgresColumn(name="FRAGRP_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="FRANGO_GILTIG_FOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="FRANGO_GILTIG_TOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="FRANGO_ID", data_type=PostgresType.TEXT),
        PostgresColumn(name="FRANGO_ID_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="FRANGO_PASSIV", data_type=PostgresType.BOOLEAN),
        PostgresColumn(name="FRANGO_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="IK_GILTIG_FOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="IK_GILTIG_TOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="IK_ID", data_type=PostgresType.TEXT),
        PostgresColumn(name="IK_ID_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="IK_PASSIV", data_type=PostgresType.BOOLEAN),
        PostgresColumn(name="IK_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="KGRUPP_GILTIG_FOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="KGRUPP_GILTIG_TOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="KGRUPP_ID", data_type=PostgresType.TEXT),
        PostgresColumn(name="KGRUPP_ID_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="KGRUPP_PASSIV", data_type=PostgresType.BOOLEAN),
        PostgresColumn(name="KGRUPP_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="KKLASS_GILTIG_FOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="KKLASS_GILTIG_TOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="KKLASS_ID", data_type=PostgresType.TEXT),
        PostgresColumn(name="KKLASS_ID_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="KKLASS_PASSIV", data_type=PostgresType.BOOLEAN),
        PostgresColumn(name="KKLASS_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="KONTO_GILTIG_FOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="KONTO_GILTIG_TOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="KONTO_ID", data_type=PostgresType.TEXT),
        PostgresColumn(name="KONTO_ID_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="KONTO_PASSIV", data_type=PostgresType.BOOLEAN),
        PostgresColumn(name="KONTO_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="RAD_GILTIG_FOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="RAD_GILTIG_TOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="RAD_ID", data_type=PostgresType.TEXT),
        PostgresColumn(name="RAD_ID_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="RAD_PASSIV", data_type=PostgresType.BOOLEAN),
        PostgresColumn(name="RAD_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="RR_STS_GILTIG_FOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="RR_STS_GILTIG_TOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="RR_STS_ID", data_type=PostgresType.TEXT),
        PostgresColumn(name="RR_STS_ID_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="RR_STS_PASSIV", data_type=PostgresType.BOOLEAN),
        PostgresColumn(name="RR_STS_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="ÅRL_GILTIG_FOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="ÅRL_GILTIG_TOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="ÅRL_ID", data_type=PostgresType.TEXT),
        PostgresColumn(name="ÅRL_ID_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="ÅRL_PASSIV", data_type=PostgresType.BOOLEAN),
        PostgresColumn(name="ÅRL_TEXT", data_type=PostgresType.TEXT),
    ],
    database=Database.POSTGRES,
    cron="0 6 * * *",
    tags=['sts', 'raindance', 'raw'],
)

@with_env_config
def execute(env: EnvConfig, cfg=config):
    dest_dsn = env_var_dsn("BIG_EKONOMI_EXECUTION_PROD")
    query = """
    SELECT
	CAST(GETDATE() AS DATE) as _data_modified,
	CAST(GETDATE() AS DATETIME2) as _metadata_modified,
	COALESCE([ANSELI_GILTIG_FOM], '1899-12-31 00:00:00') AS ANSELI_GILTIG_FOM,
	COALESCE([ANSELI_GILTIG_TOM], '1899-12-31 00:00:00') AS ANSELI_GILTIG_TOM,
	[ANSELI_ID] AS ANSELI_ID,
	[ANSELI_ID_TEXT] AS ANSELI_ID_TEXT,
	[ANSELI_PASSIV] AS ANSELI_PASSIV,
	[ANSELI_TEXT] AS ANSELI_TEXT,
	COALESCE([ELSJKH_GILTIG_FOM], '1899-12-31 00:00:00') AS ELSJKH_GILTIG_FOM,
	COALESCE([ELSJKH_GILTIG_TOM], '1899-12-31 00:00:00') AS ELSJKH_GILTIG_TOM,
	[ELSJKH_ID] AS ELSJKH_ID,
	[ELSJKH_ID_TEXT] AS ELSJKH_ID_TEXT,
	[ELSJKH_PASSIV] AS ELSJKH_PASSIV,
	[ELSJKH_TEXT] AS ELSJKH_TEXT,
	COALESCE([FRAGRP_GILTIG_FOM], '1899-12-31 00:00:00') AS FRAGRP_GILTIG_FOM,
	COALESCE([FRAGRP_GILTIG_TOM], '1899-12-31 00:00:00') AS FRAGRP_GILTIG_TOM,
	[FRAGRP_ID] AS FRAGRP_ID,
	[FRAGRP_ID_TEXT] AS FRAGRP_ID_TEXT,
	[FRAGRP_PASSIV] AS FRAGRP_PASSIV,
	[FRAGRP_TEXT] AS FRAGRP_TEXT,
	COALESCE([FRANGO_GILTIG_FOM], '1899-12-31 00:00:00') AS FRANGO_GILTIG_FOM,
	COALESCE([FRANGO_GILTIG_TOM], '1899-12-31 00:00:00') AS FRANGO_GILTIG_TOM,
	[FRANGO_ID] AS FRANGO_ID,
	[FRANGO_ID_TEXT] AS FRANGO_ID_TEXT,
	[FRANGO_PASSIV] AS FRANGO_PASSIV,
	[FRANGO_TEXT] AS FRANGO_TEXT,
	COALESCE([IK_GILTIG_FOM], '1899-12-31 00:00:00') AS IK_GILTIG_FOM,
	COALESCE([IK_GILTIG_TOM], '1899-12-31 00:00:00') AS IK_GILTIG_TOM,
	[IK_ID] AS IK_ID,
	[IK_ID_TEXT] AS IK_ID_TEXT,
	[IK_PASSIV] AS IK_PASSIV,
	[IK_TEXT] AS IK_TEXT,
	COALESCE([KGRUPP_GILTIG_FOM], '1899-12-31 00:00:00') AS KGRUPP_GILTIG_FOM,
	COALESCE([KGRUPP_GILTIG_TOM], '1899-12-31 00:00:00') AS KGRUPP_GILTIG_TOM,
	[KGRUPP_ID] AS KGRUPP_ID,
	[KGRUPP_ID_TEXT] AS KGRUPP_ID_TEXT,
	[KGRUPP_PASSIV] AS KGRUPP_PASSIV,
	[KGRUPP_TEXT] AS KGRUPP_TEXT,
	COALESCE([KKLASS_GILTIG_FOM], '1899-12-31 00:00:00') AS KKLASS_GILTIG_FOM,
	COALESCE([KKLASS_GILTIG_TOM], '1899-12-31 00:00:00') AS KKLASS_GILTIG_TOM,
	[KKLASS_ID] AS KKLASS_ID,
	[KKLASS_ID_TEXT] AS KKLASS_ID_TEXT,
	[KKLASS_PASSIV] AS KKLASS_PASSIV,
	[KKLASS_TEXT] AS KKLASS_TEXT,
	COALESCE([KONTO_GILTIG_FOM], '1899-12-31 00:00:00') AS KONTO_GILTIG_FOM,
	COALESCE([KONTO_GILTIG_TOM], '1899-12-31 00:00:00') AS KONTO_GILTIG_TOM,
	[KONTO_ID] AS KONTO_ID,
	[KONTO_ID_TEXT] AS KONTO_ID_TEXT,
	[KONTO_PASSIV] AS KONTO_PASSIV,
	[KONTO_TEXT] AS KONTO_TEXT,
	COALESCE([RAD_GILTIG_FOM], '1899-12-31 00:00:00') AS RAD_GILTIG_FOM,
	COALESCE([RAD_GILTIG_TOM], '1899-12-31 00:00:00') AS RAD_GILTIG_TOM,
	[RAD_ID] AS RAD_ID,
	[RAD_ID_TEXT] AS RAD_ID_TEXT,
	[RAD_PASSIV] AS RAD_PASSIV,
	[RAD_TEXT] AS RAD_TEXT,
	COALESCE([RR_STS_GILTIG_FOM], '1899-12-31 00:00:00') AS RR_STS_GILTIG_FOM,
	COALESCE([RR_STS_GILTIG_TOM], '1899-12-31 00:00:00') AS RR_STS_GILTIG_TOM,
	[RR_STS_ID] AS RR_STS_ID,
	[RR_STS_ID_TEXT] AS RR_STS_ID_TEXT,
	[RR_STS_PASSIV] AS RR_STS_PASSIV,
	[RR_STS_TEXT] AS RR_STS_TEXT,
	COALESCE([ÅRL_GILTIG_FOM], '1899-12-31 00:00:00') AS ÅRL_GILTIG_FOM,
	COALESCE([ÅRL_GILTIG_TOM], '1899-12-31 00:00:00') AS ÅRL_GILTIG_TOM,
	[ÅRL_ID] AS ÅRL_ID,
	[ÅRL_ID_TEXT] AS ÅRL_ID_TEXT,
	[ÅRL_PASSIV] AS ÅRL_PASSIV,
	[ÅRL_TEXT] AS ÅRL_TEXT
    FROM [stsudp].[udp_858].[EK_DIM_OBJ_KONTO]

    """
    total_rows = 0
    first_batch = True
    for df in read("RAINDANCE_8580", query):
        if len(df) == 0:
            continue
        write(cfg, df, dest_dsn)
        if first_batch:
            cfg.write_mode = WriteMode.APPEND
            first_batch = False
        total_rows += len(df)
    print(f"  ✓ {cfg.name}: {total_rows:,} rows written" if total_rows else f"  ⏭ {cfg.name}: no data, skipping")