from bollhav import Model, WriteMode
from bollhav.postgres import PostgresColumn, PostgresType
from bollhav.database import Database
from core import read, write
from roskarl.marshal import with_env_config, EnvConfig
from roskarl import env_var_dsn

config = Model(
    name="rk_dim_kund",
    source_entity="RK_DIM_KUND",
    table="rk_dim_kund",
    schema="raindance_raw_8810",
    write_mode=WriteMode.TRUNCATE_INSERT,
    columns=[
        PostgresColumn(name="_data_modified", data_type=PostgresType.DATE),
        PostgresColumn(name="_metadata_modified", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="ADR1", data_type=PostgresType.TEXT),
        PostgresColumn(name="ADR2", data_type=PostgresType.TEXT),
        PostgresColumn(name="ATTRIBUTE_ACTORID", data_type=PostgresType.TEXT),
        PostgresColumn(name="ATTRIBUTE_EAN", data_type=PostgresType.TEXT),
        PostgresColumn(name="BETSPARR", data_type=PostgresType.BOOLEAN),
        PostgresColumn(name="BGNR", data_type=PostgresType.TEXT),
        PostgresColumn(name="DUMMY1", data_type=PostgresType.TEXT),
        PostgresColumn(name="ELEKTRONISK_KOMMUNIKATION", data_type=PostgresType.TEXT),
        PostgresColumn(name="ENGANG", data_type=PostgresType.BOOLEAN),
        PostgresColumn(name="FRI1", data_type=PostgresType.TEXT),
        PostgresColumn(name="FRI2", data_type=PostgresType.TEXT),
        PostgresColumn(name="FRI3", data_type=PostgresType.TEXT),
        PostgresColumn(name="FRI4", data_type=PostgresType.TEXT),
        PostgresColumn(name="GRUPP", data_type=PostgresType.TEXT),
        PostgresColumn(name="KREDITLIMIT", data_type=PostgresType.NUMERIC),
        PostgresColumn(name="KUND_EREF", data_type=PostgresType.TEXT),
        PostgresColumn(name="KUND_TAB_AF", data_type=PostgresType.TEXT),
        PostgresColumn(name="KUND_TAB_AGF", data_type=PostgresType.TEXT),
        PostgresColumn(name="KUND_TAB_AVBET", data_type=PostgresType.TEXT),
        PostgresColumn(name="KUND_TAB_BEHÄND", data_type=PostgresType.TEXT),
        PostgresColumn(name="KUND_TAB_BETP", data_type=PostgresType.TEXT),
        PostgresColumn(name="KUND_TAB_BETV", data_type=PostgresType.TEXT),
        PostgresColumn(name="KUND_TAB_DEBAVB", data_type=PostgresType.TEXT),
        PostgresColumn(name="KUND_TAB_DEBBP", data_type=PostgresType.TEXT),
        PostgresColumn(name="KUND_TAB_DIV", data_type=PostgresType.TEXT),
        PostgresColumn(name="KUND_TAB_ENHET", data_type=PostgresType.TEXT),
        PostgresColumn(name="KUND_TAB_FELKOD", data_type=PostgresType.TEXT),
        PostgresColumn(name="KUND_TAB_INK", data_type=PostgresType.TEXT),
        PostgresColumn(name="KUND_TAB_KAT", data_type=PostgresType.TEXT),
        PostgresColumn(name="KUND_TAB_KRAVGR", data_type=PostgresType.TEXT),
        PostgresColumn(name="KUND_TAB_LÖPNR", data_type=PostgresType.TEXT),
        PostgresColumn(name="KUND_TAB_MOMS", data_type=PostgresType.TEXT),
        PostgresColumn(name="KUND_TAB_MOTP", data_type=PostgresType.TEXT),
        PostgresColumn(name="KUND_TAB_PERSNR", data_type=PostgresType.TEXT),
        PostgresColumn(name="KUND_TAB_RDEB", data_type=PostgresType.TEXT),
        PostgresColumn(name="KUND_TAB_RÄNTGR", data_type=PostgresType.TEXT),
        PostgresColumn(name="KUND_TAB_UBF", data_type=PostgresType.TEXT),
        PostgresColumn(name="KUND_VREF", data_type=PostgresType.TEXT),
        PostgresColumn(name="KUNDID", data_type=PostgresType.TEXT),
        PostgresColumn(name="KUNDID2", data_type=PostgresType.TEXT),
        PostgresColumn(name="KUNDID_ID_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="KUNDID_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="LAND", data_type=PostgresType.TEXT),
        PostgresColumn(name="MOMSREG", data_type=PostgresType.TEXT),
        PostgresColumn(name="MSG_INVOIC_FORMAT", data_type=PostgresType.TEXT),
        PostgresColumn(name="MSG_INVOIC_PA", data_type=PostgresType.TEXT),
        PostgresColumn(name="MSG_INVOIC_TRANSPORT", data_type=PostgresType.TEXT),
        PostgresColumn(name="MSG_INVOIC_VAG", data_type=PostgresType.TEXT),
        PostgresColumn(name="NAMN2", data_type=PostgresType.TEXT),
        PostgresColumn(name="OMSATTNING", data_type=PostgresType.NUMERIC),
        PostgresColumn(name="OMSATTNING_FG", data_type=PostgresType.NUMERIC),
        PostgresColumn(name="OMSATTNINGSAR", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="ORGNR", data_type=PostgresType.TEXT),
        PostgresColumn(name="ORT", data_type=PostgresType.TEXT),
        PostgresColumn(name="PASSIV", data_type=PostgresType.BOOLEAN),
        PostgresColumn(name="PGNR", data_type=PostgresType.TEXT),
        PostgresColumn(name="SALDO", data_type=PostgresType.NUMERIC),
        PostgresColumn(name="SOKBEGR", data_type=PostgresType.TEXT),
        PostgresColumn(name="TELNR", data_type=PostgresType.TEXT),
    ],
    database=Database.POSTGRES,
    cron="0 6 * * *",
    tags=['ftsl', 'raindance', 'raw'],
)

@with_env_config
def execute(env: EnvConfig, cfg=config):
    dest_dsn = env_var_dsn("BIG_EKONOMI_EXECUTION_PROD")
    query = """
    SELECT
	CAST(GETDATE() AS DATE) as _data_modified,
	CAST(GETDATE() AS DATETIME2) as _metadata_modified,
	[ADR1] AS ADR1,
	[ADR2] AS ADR2,
	[ATTRIBUTE_ACTORID] AS ATTRIBUTE_ACTORID,
	[ATTRIBUTE_EAN] AS ATTRIBUTE_EAN,
	[BETSPARR] AS BETSPARR,
	[BGNR] AS BGNR,
	[DUMMY1] AS DUMMY1,
	[ELEKTRONISK_KOMMUNIKATION] AS ELEKTRONISK_KOMMUNIKATION,
	[ENGANG] AS ENGANG,
	[FRI1] AS FRI1,
	[FRI2] AS FRI2,
	[FRI3] AS FRI3,
	[FRI4] AS FRI4,
	[GRUPP] AS GRUPP,
	[KREDITLIMIT] AS KREDITLIMIT,
	[KUND_EREF] AS KUND_EREF,
	[KUND_TAB_AF] AS KUND_TAB_AF,
	[KUND_TAB_AGF] AS KUND_TAB_AGF,
	[KUND_TAB_AVBET] AS KUND_TAB_AVBET,
	[KUND_TAB_BEHÄND] AS KUND_TAB_BEHÄND,
	[KUND_TAB_BETP] AS KUND_TAB_BETP,
	[KUND_TAB_BETV] AS KUND_TAB_BETV,
	[KUND_TAB_DEBAVB] AS KUND_TAB_DEBAVB,
	[KUND_TAB_DEBBP] AS KUND_TAB_DEBBP,
	[KUND_TAB_DIV] AS KUND_TAB_DIV,
	[KUND_TAB_ENHET] AS KUND_TAB_ENHET,
	[KUND_TAB_FELKOD] AS KUND_TAB_FELKOD,
	[KUND_TAB_INK] AS KUND_TAB_INK,
	[KUND_TAB_KAT] AS KUND_TAB_KAT,
	[KUND_TAB_KRAVGR] AS KUND_TAB_KRAVGR,
	[KUND_TAB_LÖPNR] AS KUND_TAB_LÖPNR,
	[KUND_TAB_MOMS] AS KUND_TAB_MOMS,
	[KUND_TAB_MOTP] AS KUND_TAB_MOTP,
	[KUND_TAB_PERSNR] AS KUND_TAB_PERSNR,
	[KUND_TAB_RDEB] AS KUND_TAB_RDEB,
	[KUND_TAB_RÄNTGR] AS KUND_TAB_RÄNTGR,
	[KUND_TAB_UBF] AS KUND_TAB_UBF,
	[KUND_VREF] AS KUND_VREF,
	[KUNDID] AS KUNDID,
	[KUNDID2] AS KUNDID2,
	[KUNDID_ID_TEXT] AS KUNDID_ID_TEXT,
	[KUNDID_TEXT] AS KUNDID_TEXT,
	[LAND] AS LAND,
	[MOMSREG] AS MOMSREG,
	[MSG_INVOIC_FORMAT] AS MSG_INVOIC_FORMAT,
	[MSG_INVOIC_PA] AS MSG_INVOIC_PA,
	[MSG_INVOIC_TRANSPORT] AS MSG_INVOIC_TRANSPORT,
	[MSG_INVOIC_VAG] AS MSG_INVOIC_VAG,
	[NAMN2] AS NAMN2,
	[OMSATTNING] AS OMSATTNING,
	[OMSATTNING_FG] AS OMSATTNING_FG,
	COALESCE([OMSATTNINGSAR], '1899-12-31 00:00:00') AS OMSATTNINGSAR,
	[ORGNR] AS ORGNR,
	[ORT] AS ORT,
	[PASSIV] AS PASSIV,
	[PGNR] AS PGNR,
	[SALDO] AS SALDO,
	[SOKBEGR] AS SOKBEGR,
	[TELNR] AS TELNR
    FROM [ftvudp].[ftv_400].[RK_DIM_KUND]

    """
    total_rows = 0
    first_batch = True
    for df in read("RAINDANCE_8810", query):
        if len(df) == 0:
            continue
        write(cfg, df, dest_dsn)
        if first_batch:
            cfg.write_mode = WriteMode.APPEND
            first_batch = False
        total_rows += len(df)
    print(f"  ✓ {cfg.name}: {total_rows:,} rows written" if total_rows else f"  ⏭ {cfg.name}: no data, skipping")