from bollhav import Model, WriteMode
from bollhav.postgres import PostgresColumn, PostgresType
from bollhav.database import Database
from core import read

config = Model(
    name="rk_fakta_levfakt_verifikat",
    source_entity="RK_FAKTA_LEVFAKT_VERIFIKAT",
    table="rk_fakta_levfakt_verifikat",
    schema="raindance_raw_8810",
    write_mode=WriteMode.MERGE,
    columns=[
        PostgresColumn(name="_data_modified", data_type=PostgresType.DATE),
        PostgresColumn(name="_metadata_modified", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="AFFO_ID", data_type=PostgresType.TEXT),
        PostgresColumn(name="ANTAL_V", data_type=PostgresType.NUMERIC),
        PostgresColumn(name="ARPINV_ID", data_type=PostgresType.TEXT),
        PostgresColumn(name="ATTEST", data_type=PostgresType.BOOLEAN),
        PostgresColumn(name="ATTESTDATUM1", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="ATTESTDATUM2", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="ATTESTSIGN1", data_type=PostgresType.TEXT),
        PostgresColumn(name="ATTESTSIGN2", data_type=PostgresType.TEXT),
        PostgresColumn(name="AVTALID", data_type=PostgresType.TEXT),
        PostgresColumn(name="BELOPP_SEK", data_type=PostgresType.NUMERIC),
        PostgresColumn(name="BELOPP_VAL", data_type=PostgresType.NUMERIC),
        PostgresColumn(name="BESTUT_V", data_type=PostgresType.NUMERIC),
        PostgresColumn(name="BETALNINGSSPARR", data_type=PostgresType.BOOLEAN),
        PostgresColumn(name="BETALT_SEK", data_type=PostgresType.NUMERIC),
        PostgresColumn(name="BETALT_VAL", data_type=PostgresType.NUMERIC),
        PostgresColumn(name="BETDAGAR", data_type=PostgresType.NUMERIC),
        PostgresColumn(name="BUDGET_V", data_type=PostgresType.NUMERIC),
        PostgresColumn(name="DEFDATUM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="DEFSIGN", data_type=PostgresType.TEXT),
        PostgresColumn(name="DOK_ANTAL", data_type=PostgresType.NUMERIC),
        PostgresColumn(name="DOKTYP", data_type=PostgresType.NUMERIC),
        PostgresColumn(name="DOKUMENTID", data_type=PostgresType.TEXT),
        PostgresColumn(name="ENHET_ID", data_type=PostgresType.TEXT),
        PostgresColumn(name="EREF", data_type=PostgresType.TEXT),
        PostgresColumn(name="EXTERNANM", data_type=PostgresType.TEXT),
        PostgresColumn(name="EXTERNID", data_type=PostgresType.TEXT),
        PostgresColumn(name="EXTERNNR", data_type=PostgresType.TEXT),
        PostgresColumn(name="F_DOK_ANTAL", data_type=PostgresType.NUMERIC),
        PostgresColumn(name="F_MED", data_type=PostgresType.NUMERIC),
        PostgresColumn(name="FAKTSTATUS", data_type=PostgresType.TEXT),
        PostgresColumn(name="FAKTURA_REGDATUM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="FAKTURADATUM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="FORETAG", data_type=PostgresType.NUMERIC),
        PostgresColumn(name="FORFALLODATUM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="HUVUDTEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="HÄND_ID", data_type=PostgresType.TEXT),
        PostgresColumn(name="HÄNDAT_ID", data_type=PostgresType.TEXT),
        PostgresColumn(name="IB", data_type=PostgresType.TEXT),
        PostgresColumn(name="INTERNVERNR", data_type=PostgresType.NUMERIC),
        PostgresColumn(name="KATEGORI", data_type=PostgresType.NUMERIC),
        PostgresColumn(name="KONTO_ID", data_type=PostgresType.TEXT),
        PostgresColumn(name="KONTSIGN", data_type=PostgresType.TEXT),
        PostgresColumn(name="KRAVNIVA", data_type=PostgresType.NUMERIC),
        PostgresColumn(name="LEVID", data_type=PostgresType.TEXT),
        PostgresColumn(name="LEVRTYP", data_type=PostgresType.TEXT),
        PostgresColumn(name="LPMALL_ID", data_type=PostgresType.TEXT),
        PostgresColumn(name="MED", data_type=PostgresType.NUMERIC),
        PostgresColumn(name="MOMS_SEK", data_type=PostgresType.NUMERIC),
        PostgresColumn(name="MOMS_VAL", data_type=PostgresType.NUMERIC),
        PostgresColumn(name="MOTP_ID", data_type=PostgresType.TEXT),
        PostgresColumn(name="MOTTATTDAT", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="MOTTATTSIGN", data_type=PostgresType.TEXT),
        PostgresColumn(name="NR", data_type=PostgresType.NUMERIC),
        PostgresColumn(name="OCRNR", data_type=PostgresType.TEXT),
        PostgresColumn(name="OVERDRDAGAR", data_type=PostgresType.NUMERIC),
        PostgresColumn(name="PNYCKEL", data_type=PostgresType.TEXT),
        PostgresColumn(name="PROJ_ID", data_type=PostgresType.TEXT),
        PostgresColumn(name="RAD_ID", data_type=PostgresType.TEXT),
        PostgresColumn(name="RADTEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="RADTYPNR", data_type=PostgresType.NUMERIC),
        PostgresColumn(name="RANTEDEB", data_type=PostgresType.BOOLEAN),
        PostgresColumn(name="REGDAT_ID", data_type=PostgresType.TEXT),
        PostgresColumn(name="REGDATUM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="REGSIGN", data_type=PostgresType.TEXT),
        PostgresColumn(name="RESPRO_ID", data_type=PostgresType.TEXT),
        PostgresColumn(name="RESPRO_V", data_type=PostgresType.NUMERIC),
        PostgresColumn(name="SENASTBETDATUM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="SPEC_ID", data_type=PostgresType.TEXT),
        PostgresColumn(name="STATUS", data_type=PostgresType.TEXT),
        PostgresColumn(name="TAB_BETV", data_type=PostgresType.TEXT),
        PostgresColumn(name="TAB_BGCNR", data_type=PostgresType.TEXT),
        PostgresColumn(name="TAB_ENHET", data_type=PostgresType.TEXT),
        PostgresColumn(name="TAB_KAT", data_type=PostgresType.TEXT),
        PostgresColumn(name="TAB_LPMALL", data_type=PostgresType.TEXT),
        PostgresColumn(name="TAB_MOMS", data_type=PostgresType.TEXT),
        PostgresColumn(name="TAB_MOMSOM", data_type=PostgresType.TEXT),
        PostgresColumn(name="TAB_MOTP", data_type=PostgresType.TEXT),
        PostgresColumn(name="TAB_ORDNR", data_type=PostgresType.TEXT),
        PostgresColumn(name="TAB_SKDAT", data_type=PostgresType.TEXT),
        PostgresColumn(name="TAB_SKNR", data_type=PostgresType.TEXT),
        PostgresColumn(name="TAB_UBF", data_type=PostgresType.TEXT),
        PostgresColumn(name="TAB_UBK", data_type=PostgresType.TEXT),
        PostgresColumn(name="TAB_VALUTA", data_type=PostgresType.TEXT),
        PostgresColumn(name="TYP_ID", data_type=PostgresType.TEXT),
        PostgresColumn(name="URSPRUNGS_VERIFIKAT", data_type=PostgresType.TEXT),
        PostgresColumn(name="URSPTEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="UTFALL_V", data_type=PostgresType.NUMERIC),
        PostgresColumn(name="UTFVAL_V", data_type=PostgresType.NUMERIC),
        PostgresColumn(name="UTILITY", data_type=PostgresType.NUMERIC),
        PostgresColumn(name="UTSKRDATUM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="VALUTA_ID", data_type=PostgresType.TEXT),
        PostgresColumn(name="VERDATUM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="VERDOKREF", data_type=PostgresType.TEXT),
        PostgresColumn(name="VERNR", data_type=PostgresType.NUMERIC),
        PostgresColumn(name="VERRAD", data_type=PostgresType.NUMERIC),
        PostgresColumn(name="VERTYP", data_type=PostgresType.TEXT),
        PostgresColumn(name="VREF", data_type=PostgresType.TEXT),
        PostgresColumn(name="YGRP_ID", data_type=PostgresType.TEXT),
    ],
    database=Database.POSTGRES,
    cron="0 6 * * *",
    tags=['ftsl', 'raindance', 'raw'],
)

def execute(env, cfg=config):
    if env.backfill and env.backfill.enabled:
        since = env.backfill.since.strftime("%Y-%m-%d")
        until = env.backfill.until.strftime("%Y-%m-%d")
    elif env.cron and env.cron.enabled:
        since = env.cron.since.strftime("%Y-%m-%d")
        until = env.cron.until.strftime("%Y-%m-%d")
    else:
        since = None
        until = None
    query=f"""SELECT * FROM (SELECT
    	CAST(VERDATUM AS DATE) as _data_modified,
    	CAST(GETDATE() AS DATETIME2) as _metadata_modified,
    	[AFFO_ID] AS AFFO_ID,
    	[ANTAL_V] AS ANTAL_V,
    	[ARPINV_ID] AS ARPINV_ID,
    	[ATTEST] AS ATTEST,
    	COALESCE([ATTESTDATUM1], '1899-12-31 00:00:00') AS ATTESTDATUM1,
    	COALESCE([ATTESTDATUM2], '1899-12-31 00:00:00') AS ATTESTDATUM2,
    	[ATTESTSIGN1] AS ATTESTSIGN1,
    	[ATTESTSIGN2] AS ATTESTSIGN2,
    	[AVTALID] AS AVTALID,
    	[BELOPP_SEK] AS BELOPP_SEK,
    	[BELOPP_VAL] AS BELOPP_VAL,
    	[BESTUT_V] AS BESTUT_V,
    	[BETALNINGSSPARR] AS BETALNINGSSPARR,
    	[BETALT_SEK] AS BETALT_SEK,
    	[BETALT_VAL] AS BETALT_VAL,
    	[BETDAGAR] AS BETDAGAR,
    	[BUDGET_V] AS BUDGET_V,
    	COALESCE([DEFDATUM], '1899-12-31 00:00:00') AS DEFDATUM,
    	[DEFSIGN] AS DEFSIGN,
    	[DOK_ANTAL] AS DOK_ANTAL,
    	[DOKTYP] AS DOKTYP,
    	[DOKUMENTID] AS DOKUMENTID,
    	[ENHET_ID] AS ENHET_ID,
    	[EREF] AS EREF,
    	[EXTERNANM] AS EXTERNANM,
    	[EXTERNID] AS EXTERNID,
    	[EXTERNNR] AS EXTERNNR,
    	[F_DOK_ANTAL] AS F_DOK_ANTAL,
    	[F_MED] AS F_MED,
    	[FAKTSTATUS] AS FAKTSTATUS,
    	COALESCE([FAKTURA_REGDATUM], '1899-12-31 00:00:00') AS FAKTURA_REGDATUM,
    	COALESCE([FAKTURADATUM], '1899-12-31 00:00:00') AS FAKTURADATUM,
    	[FORETAG] AS FORETAG,
    	COALESCE([FORFALLODATUM], '1899-12-31 00:00:00') AS FORFALLODATUM,
    	[HUVUDTEXT] AS HUVUDTEXT,
    	[HÄND_ID] AS HÄND_ID,
    	[HÄNDAT_ID] AS HÄNDAT_ID,
    	[IB] AS IB,
    	[INTERNVERNR] AS INTERNVERNR,
    	[KATEGORI] AS KATEGORI,
    	[KONTO_ID] AS KONTO_ID,
    	[KONTSIGN] AS KONTSIGN,
    	[KRAVNIVA] AS KRAVNIVA,
    	[LEVID] AS LEVID,
    	[LEVRTYP] AS LEVRTYP,
    	[LPMALL_ID] AS LPMALL_ID,
    	[MED] AS MED,
    	[MOMS_SEK] AS MOMS_SEK,
    	[MOMS_VAL] AS MOMS_VAL,
    	[MOTP_ID] AS MOTP_ID,
    	COALESCE([MOTTATTDAT], '1899-12-31 00:00:00') AS MOTTATTDAT,
    	[MOTTATTSIGN] AS MOTTATTSIGN,
    	[NR] AS NR,
    	[OCRNR] AS OCRNR,
    	[OVERDRDAGAR] AS OVERDRDAGAR,
    	[PNYCKEL] AS PNYCKEL,
    	[PROJ_ID] AS PROJ_ID,
    	[RAD_ID] AS RAD_ID,
    	[RADTEXT] AS RADTEXT,
    	[RADTYPNR] AS RADTYPNR,
    	[RANTEDEB] AS RANTEDEB,
    	[REGDAT_ID] AS REGDAT_ID,
    	COALESCE([REGDATUM], '1899-12-31 00:00:00') AS REGDATUM,
    	[REGSIGN] AS REGSIGN,
    	[RESPRO_ID] AS RESPRO_ID,
    	[RESPRO_V] AS RESPRO_V,
    	COALESCE([SENASTBETDATUM], '1899-12-31 00:00:00') AS SENASTBETDATUM,
    	[SPEC_ID] AS SPEC_ID,
    	[STATUS] AS STATUS,
    	[TAB_BETV] AS TAB_BETV,
    	[TAB_BGCNR] AS TAB_BGCNR,
    	[TAB_ENHET] AS TAB_ENHET,
    	[TAB_KAT] AS TAB_KAT,
    	[TAB_LPMALL] AS TAB_LPMALL,
    	[TAB_MOMS] AS TAB_MOMS,
    	[TAB_MOMSOM] AS TAB_MOMSOM,
    	[TAB_MOTP] AS TAB_MOTP,
    	[TAB_ORDNR] AS TAB_ORDNR,
    	[TAB_SKDAT] AS TAB_SKDAT,
    	[TAB_SKNR] AS TAB_SKNR,
    	[TAB_UBF] AS TAB_UBF,
    	[TAB_UBK] AS TAB_UBK,
    	[TAB_VALUTA] AS TAB_VALUTA,
    	[TYP_ID] AS TYP_ID,
    	[URSPRUNGS_VERIFIKAT] AS URSPRUNGS_VERIFIKAT,
    	[URSPTEXT] AS URSPTEXT,
    	[UTFALL_V] AS UTFALL_V,
    	[UTFVAL_V] AS UTFVAL_V,
    	[UTILITY] AS UTILITY,
    	COALESCE([UTSKRDATUM], '1899-12-31 00:00:00') AS UTSKRDATUM,
    	[VALUTA_ID] AS VALUTA_ID,
    	COALESCE([VERDATUM], '1899-12-31 00:00:00') AS VERDATUM,
    	[VERDOKREF] AS VERDOKREF,
    	[VERNR] AS VERNR,
    	[VERRAD] AS VERRAD,
    	[VERTYP] AS VERTYP,
    	[VREF] AS VREF,
    	[YGRP_ID] AS YGRP_ID
    FROM [ftvudp].[ftv_400].[RK_FAKTA_LEVFAKT_VERIFIKAT]) y
    WHERE _data_modified BETWEEN '{since}' AND '{until}'"""
    yield from read(query=query, env_var_name='RAINDANCE_8810')