from bollhav import Model, WriteMode
from bollhav.postgres import PostgresColumn, PostgresType
from bollhav.database import Database
from core import read, write
from roskarl.marshal import with_env_config, EnvConfig
from roskarl import env_var_dsn

config = Model(
    name="ek_dim_obj_konto",
    source_entity="EK_DIM_OBJ_KONTO",
    table="ek_dim_obj_konto",
    schema="raindance_raw_8570",
    write_mode=WriteMode.TRUNCATE_INSERT,
    columns=[
        PostgresColumn(name="_data_modified", data_type=PostgresType.DATE),
        PostgresColumn(name="_metadata_modified", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="FMK_GILTIG_FOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="FMK_GILTIG_TOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="FMK_ID", data_type=PostgresType.TEXT),
        PostgresColumn(name="FMK_ID_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="FMK_PASSIV", data_type=PostgresType.BOOLEAN),
        PostgresColumn(name="FMK_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="FRA01_GILTIG_FOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="FRA01_GILTIG_TOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="FRA01_ID", data_type=PostgresType.TEXT),
        PostgresColumn(name="FRA01_ID_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="FRA01_PASSIV", data_type=PostgresType.BOOLEAN),
        PostgresColumn(name="FRA01_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="FRA03_GILTIG_FOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="FRA03_GILTIG_TOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="FRA03_ID", data_type=PostgresType.TEXT),
        PostgresColumn(name="FRA03_ID_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="FRA03_PASSIV", data_type=PostgresType.BOOLEAN),
        PostgresColumn(name="FRA03_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="FRA05_GILTIG_FOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="FRA05_GILTIG_TOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="FRA05_ID", data_type=PostgresType.TEXT),
        PostgresColumn(name="FRA05_ID_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="FRA05_PASSIV", data_type=PostgresType.BOOLEAN),
        PostgresColumn(name="FRA05_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="KBR_GILTIG_FOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="KBR_GILTIG_TOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="KBR_ID", data_type=PostgresType.TEXT),
        PostgresColumn(name="KBR_ID_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="KBR_PASSIV", data_type=PostgresType.BOOLEAN),
        PostgresColumn(name="KBR_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="KONCRR_GILTIG_FOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="KONCRR_GILTIG_TOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="KONCRR_ID", data_type=PostgresType.TEXT),
        PostgresColumn(name="KONCRR_ID_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="KONCRR_PASSIV", data_type=PostgresType.BOOLEAN),
        PostgresColumn(name="KONCRR_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="KONDEL_GILTIG_FOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="KONDEL_GILTIG_TOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="KONDEL_ID", data_type=PostgresType.TEXT),
        PostgresColumn(name="KONDEL_ID_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="KONDEL_PASSIV", data_type=PostgresType.BOOLEAN),
        PostgresColumn(name="KONDEL_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="KONTO_GILTIG_FOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="KONTO_GILTIG_TOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="KONTO_ID", data_type=PostgresType.TEXT),
        PostgresColumn(name="KONTO_ID_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="KONTO_PASSIV", data_type=PostgresType.BOOLEAN),
        PostgresColumn(name="KONTO_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="KTO1_GILTIG_FOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="KTO1_GILTIG_TOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="KTO1_ID", data_type=PostgresType.TEXT),
        PostgresColumn(name="KTO1_ID_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="KTO1_PASSIV", data_type=PostgresType.BOOLEAN),
        PostgresColumn(name="KTO1_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="KTO2_GILTIG_FOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="KTO2_GILTIG_TOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="KTO2_ID", data_type=PostgresType.TEXT),
        PostgresColumn(name="KTO2_ID_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="KTO2_PASSIV", data_type=PostgresType.BOOLEAN),
        PostgresColumn(name="KTO2_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="KTYP_GILTIG_FOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="KTYP_GILTIG_TOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="KTYP_ID", data_type=PostgresType.TEXT),
        PostgresColumn(name="KTYP_ID_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="KTYP_PASSIV", data_type=PostgresType.BOOLEAN),
        PostgresColumn(name="KTYP_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="MKTO_GILTIG_FOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="MKTO_GILTIG_TOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="MKTO_ID", data_type=PostgresType.TEXT),
        PostgresColumn(name="MKTO_ID_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="MKTO_PASSIV", data_type=PostgresType.BOOLEAN),
        PostgresColumn(name="MKTO_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="MS_GILTIG_FOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="MS_GILTIG_TOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="MS_ID", data_type=PostgresType.TEXT),
        PostgresColumn(name="MS_ID_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="MS_PASSIV", data_type=PostgresType.BOOLEAN),
        PostgresColumn(name="MS_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="SA_GILTIG_FOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="SA_GILTIG_TOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="SA_ID", data_type=PostgresType.TEXT),
        PostgresColumn(name="SA_ID_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="SA_PASSIV", data_type=PostgresType.BOOLEAN),
        PostgresColumn(name="SA_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="SKRD_GILTIG_FOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="SKRD_GILTIG_TOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="SKRD_ID", data_type=PostgresType.TEXT),
        PostgresColumn(name="SKRD_ID_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="SKRD_PASSIV", data_type=PostgresType.BOOLEAN),
        PostgresColumn(name="SKRD_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="SRU_GILTIG_FOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="SRU_GILTIG_TOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="SRU_ID", data_type=PostgresType.TEXT),
        PostgresColumn(name="SRU_ID_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="SRU_PASSIV", data_type=PostgresType.BOOLEAN),
        PostgresColumn(name="SRU_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="ST_GILTIG_FOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="ST_GILTIG_TOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="ST_ID", data_type=PostgresType.TEXT),
        PostgresColumn(name="ST_ID_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="ST_PASSIV", data_type=PostgresType.BOOLEAN),
        PostgresColumn(name="ST_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="SÖSRR_GILTIG_FOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="SÖSRR_GILTIG_TOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="SÖSRR_ID", data_type=PostgresType.TEXT),
        PostgresColumn(name="SÖSRR_ID_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="SÖSRR_PASSIV", data_type=PostgresType.BOOLEAN),
        PostgresColumn(name="SÖSRR_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="UKTO_GILTIG_FOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="UKTO_GILTIG_TOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="UKTO_ID", data_type=PostgresType.TEXT),
        PostgresColumn(name="UKTO_ID_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="UKTO_PASSIV", data_type=PostgresType.BOOLEAN),
        PostgresColumn(name="UKTO_TEXT", data_type=PostgresType.TEXT),
    ],
    database=Database.POSTGRES,
    cron="0 6 * * *",
    tags=['sos', 'raindance', 'raw'],
)

@with_env_config
def execute(env: EnvConfig, cfg=config):
    dest_dsn = env_var_dsn("BIG_EKONOMI_EXECUTION_PROD")
    query = """
    SELECT
	CAST(GETDATE() AS DATE) as _data_modified,
	CAST(GETDATE() AS DATETIME2) as _metadata_modified,
	COALESCE([FMK_GILTIG_FOM], '1899-12-31 00:00:00') AS FMK_GILTIG_FOM,
	COALESCE([FMK_GILTIG_TOM], '1899-12-31 00:00:00') AS FMK_GILTIG_TOM,
	[FMK_ID] AS FMK_ID,
	[FMK_ID_TEXT] AS FMK_ID_TEXT,
	[FMK_PASSIV] AS FMK_PASSIV,
	[FMK_TEXT] AS FMK_TEXT,
	COALESCE([FRA01_GILTIG_FOM], '1899-12-31 00:00:00') AS FRA01_GILTIG_FOM,
	COALESCE([FRA01_GILTIG_TOM], '1899-12-31 00:00:00') AS FRA01_GILTIG_TOM,
	[FRA01_ID] AS FRA01_ID,
	[FRA01_ID_TEXT] AS FRA01_ID_TEXT,
	[FRA01_PASSIV] AS FRA01_PASSIV,
	[FRA01_TEXT] AS FRA01_TEXT,
	COALESCE([FRA03_GILTIG_FOM], '1899-12-31 00:00:00') AS FRA03_GILTIG_FOM,
	COALESCE([FRA03_GILTIG_TOM], '1899-12-31 00:00:00') AS FRA03_GILTIG_TOM,
	[FRA03_ID] AS FRA03_ID,
	[FRA03_ID_TEXT] AS FRA03_ID_TEXT,
	[FRA03_PASSIV] AS FRA03_PASSIV,
	[FRA03_TEXT] AS FRA03_TEXT,
	COALESCE([FRA05_GILTIG_FOM], '1899-12-31 00:00:00') AS FRA05_GILTIG_FOM,
	COALESCE([FRA05_GILTIG_TOM], '1899-12-31 00:00:00') AS FRA05_GILTIG_TOM,
	[FRA05_ID] AS FRA05_ID,
	[FRA05_ID_TEXT] AS FRA05_ID_TEXT,
	[FRA05_PASSIV] AS FRA05_PASSIV,
	[FRA05_TEXT] AS FRA05_TEXT,
	COALESCE([KBR_GILTIG_FOM], '1899-12-31 00:00:00') AS KBR_GILTIG_FOM,
	COALESCE([KBR_GILTIG_TOM], '1899-12-31 00:00:00') AS KBR_GILTIG_TOM,
	[KBR_ID] AS KBR_ID,
	[KBR_ID_TEXT] AS KBR_ID_TEXT,
	[KBR_PASSIV] AS KBR_PASSIV,
	[KBR_TEXT] AS KBR_TEXT,
	COALESCE([KONCRR_GILTIG_FOM], '1899-12-31 00:00:00') AS KONCRR_GILTIG_FOM,
	COALESCE([KONCRR_GILTIG_TOM], '1899-12-31 00:00:00') AS KONCRR_GILTIG_TOM,
	[KONCRR_ID] AS KONCRR_ID,
	[KONCRR_ID_TEXT] AS KONCRR_ID_TEXT,
	[KONCRR_PASSIV] AS KONCRR_PASSIV,
	[KONCRR_TEXT] AS KONCRR_TEXT,
	COALESCE([KONDEL_GILTIG_FOM], '1899-12-31 00:00:00') AS KONDEL_GILTIG_FOM,
	COALESCE([KONDEL_GILTIG_TOM], '1899-12-31 00:00:00') AS KONDEL_GILTIG_TOM,
	[KONDEL_ID] AS KONDEL_ID,
	[KONDEL_ID_TEXT] AS KONDEL_ID_TEXT,
	[KONDEL_PASSIV] AS KONDEL_PASSIV,
	[KONDEL_TEXT] AS KONDEL_TEXT,
	COALESCE([KONTO_GILTIG_FOM], '1899-12-31 00:00:00') AS KONTO_GILTIG_FOM,
	COALESCE([KONTO_GILTIG_TOM], '1899-12-31 00:00:00') AS KONTO_GILTIG_TOM,
	[KONTO_ID] AS KONTO_ID,
	[KONTO_ID_TEXT] AS KONTO_ID_TEXT,
	[KONTO_PASSIV] AS KONTO_PASSIV,
	[KONTO_TEXT] AS KONTO_TEXT,
	COALESCE([KTO1_GILTIG_FOM], '1899-12-31 00:00:00') AS KTO1_GILTIG_FOM,
	COALESCE([KTO1_GILTIG_TOM], '1899-12-31 00:00:00') AS KTO1_GILTIG_TOM,
	[KTO1_ID] AS KTO1_ID,
	[KTO1_ID_TEXT] AS KTO1_ID_TEXT,
	[KTO1_PASSIV] AS KTO1_PASSIV,
	[KTO1_TEXT] AS KTO1_TEXT,
	COALESCE([KTO2_GILTIG_FOM], '1899-12-31 00:00:00') AS KTO2_GILTIG_FOM,
	COALESCE([KTO2_GILTIG_TOM], '1899-12-31 00:00:00') AS KTO2_GILTIG_TOM,
	[KTO2_ID] AS KTO2_ID,
	[KTO2_ID_TEXT] AS KTO2_ID_TEXT,
	[KTO2_PASSIV] AS KTO2_PASSIV,
	[KTO2_TEXT] AS KTO2_TEXT,
	COALESCE([KTYP_GILTIG_FOM], '1899-12-31 00:00:00') AS KTYP_GILTIG_FOM,
	COALESCE([KTYP_GILTIG_TOM], '1899-12-31 00:00:00') AS KTYP_GILTIG_TOM,
	[KTYP_ID] AS KTYP_ID,
	[KTYP_ID_TEXT] AS KTYP_ID_TEXT,
	[KTYP_PASSIV] AS KTYP_PASSIV,
	[KTYP_TEXT] AS KTYP_TEXT,
	COALESCE([MKTO_GILTIG_FOM], '1899-12-31 00:00:00') AS MKTO_GILTIG_FOM,
	COALESCE([MKTO_GILTIG_TOM], '1899-12-31 00:00:00') AS MKTO_GILTIG_TOM,
	[MKTO_ID] AS MKTO_ID,
	[MKTO_ID_TEXT] AS MKTO_ID_TEXT,
	[MKTO_PASSIV] AS MKTO_PASSIV,
	[MKTO_TEXT] AS MKTO_TEXT,
	COALESCE([MS_GILTIG_FOM], '1899-12-31 00:00:00') AS MS_GILTIG_FOM,
	COALESCE([MS_GILTIG_TOM], '1899-12-31 00:00:00') AS MS_GILTIG_TOM,
	[MS_ID] AS MS_ID,
	[MS_ID_TEXT] AS MS_ID_TEXT,
	[MS_PASSIV] AS MS_PASSIV,
	[MS_TEXT] AS MS_TEXT,
	COALESCE([SA_GILTIG_FOM], '1899-12-31 00:00:00') AS SA_GILTIG_FOM,
	COALESCE([SA_GILTIG_TOM], '1899-12-31 00:00:00') AS SA_GILTIG_TOM,
	[SA_ID] AS SA_ID,
	[SA_ID_TEXT] AS SA_ID_TEXT,
	[SA_PASSIV] AS SA_PASSIV,
	[SA_TEXT] AS SA_TEXT,
	COALESCE([SKRD_GILTIG_FOM], '1899-12-31 00:00:00') AS SKRD_GILTIG_FOM,
	COALESCE([SKRD_GILTIG_TOM], '1899-12-31 00:00:00') AS SKRD_GILTIG_TOM,
	[SKRD_ID] AS SKRD_ID,
	[SKRD_ID_TEXT] AS SKRD_ID_TEXT,
	[SKRD_PASSIV] AS SKRD_PASSIV,
	[SKRD_TEXT] AS SKRD_TEXT,
	COALESCE([SRU_GILTIG_FOM], '1899-12-31 00:00:00') AS SRU_GILTIG_FOM,
	COALESCE([SRU_GILTIG_TOM], '1899-12-31 00:00:00') AS SRU_GILTIG_TOM,
	[SRU_ID] AS SRU_ID,
	[SRU_ID_TEXT] AS SRU_ID_TEXT,
	[SRU_PASSIV] AS SRU_PASSIV,
	[SRU_TEXT] AS SRU_TEXT,
	COALESCE([ST_GILTIG_FOM], '1899-12-31 00:00:00') AS ST_GILTIG_FOM,
	COALESCE([ST_GILTIG_TOM], '1899-12-31 00:00:00') AS ST_GILTIG_TOM,
	[ST_ID] AS ST_ID,
	[ST_ID_TEXT] AS ST_ID_TEXT,
	[ST_PASSIV] AS ST_PASSIV,
	[ST_TEXT] AS ST_TEXT,
	COALESCE([SÖSRR_GILTIG_FOM], '1899-12-31 00:00:00') AS SÖSRR_GILTIG_FOM,
	COALESCE([SÖSRR_GILTIG_TOM], '1899-12-31 00:00:00') AS SÖSRR_GILTIG_TOM,
	[SÖSRR_ID] AS SÖSRR_ID,
	[SÖSRR_ID_TEXT] AS SÖSRR_ID_TEXT,
	[SÖSRR_PASSIV] AS SÖSRR_PASSIV,
	[SÖSRR_TEXT] AS SÖSRR_TEXT,
	COALESCE([UKTO_GILTIG_FOM], '1899-12-31 00:00:00') AS UKTO_GILTIG_FOM,
	COALESCE([UKTO_GILTIG_TOM], '1899-12-31 00:00:00') AS UKTO_GILTIG_TOM,
	[UKTO_ID] AS UKTO_ID,
	[UKTO_ID_TEXT] AS UKTO_ID_TEXT,
	[UKTO_PASSIV] AS UKTO_PASSIV,
	[UKTO_TEXT] AS UKTO_TEXT
    FROM [raindance_udp].[udp_220].[EK_DIM_OBJ_KONTO]

    """
    total_rows = 0
    first_batch = True
    for df in read("RAINDANCE_8570", query):
        if len(df) == 0:
            continue
        write(cfg, df, dest_dsn)
        if first_batch:
            cfg.write_mode = WriteMode.APPEND
            first_batch = False
        total_rows += len(df)
    print(f"  ✓ {cfg.name}: {total_rows:,} rows written" if total_rows else f"  ⏭ {cfg.name}: no data, skipping")