from bollhav import Model, WriteMode
from bollhav.postgres import PostgresColumn, PostgresType
from bollhav.database import Database
from core import read, write
from roskarl.marshal import with_env_config, EnvConfig
from roskarl import env_var_dsn

config = Model(
    name="ar_dim_defanl",
    source_entity="AR_DIM_DEFANL",
    table="ar_dim_defanl",
    schema="raindance_raw_2950",
    write_mode=WriteMode.TRUNCATE_INSERT,
    columns=[
        PostgresColumn(name="_data_modified", data_type=PostgresType.DATE),
        PostgresColumn(name="_metadata_modified", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="ACKAVSKR", data_type=PostgresType.NUMERIC),
        PostgresColumn(name="ANDR_DAT", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="ANDR_SIGN", data_type=PostgresType.TEXT),
        PostgresColumn(name="ANL_ANLTYP_ID", data_type=PostgresType.TEXT),
        PostgresColumn(name="ANL_ARURSP_ID", data_type=PostgresType.TEXT),
        PostgresColumn(name="ANL_BESTNR_ID", data_type=PostgresType.TEXT),
        PostgresColumn(name="ANL_FN_ID", data_type=PostgresType.TEXT),
        PostgresColumn(name="ANL_FRI1_ID", data_type=PostgresType.TEXT),
        PostgresColumn(name="ANL_ITNUM_ID", data_type=PostgresType.TEXT),
        PostgresColumn(name="ANL_KST_ID", data_type=PostgresType.TEXT),
        PostgresColumn(name="ANL_PLAC2_ID", data_type=PostgresType.TEXT),
        PostgresColumn(name="ANL_PLAC_ID", data_type=PostgresType.TEXT),
        PostgresColumn(name="ANL_PLAVSK_ID", data_type=PostgresType.TEXT),
        PostgresColumn(name="ANL_PROJ_ID", data_type=PostgresType.TEXT),
        PostgresColumn(name="ANLAGGNING", data_type=PostgresType.TEXT),
        PostgresColumn(name="ANLAGGNING2", data_type=PostgresType.TEXT),
        PostgresColumn(name="ANLAGGNING2_ID_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="ANLAGGNING_ID_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="ANLAGGNING_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="ANLANTAL", data_type=PostgresType.NUMERIC),
        PostgresColumn(name="ANLBOKAR", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="ANLPREL_ID", data_type=PostgresType.TEXT),
        PostgresColumn(name="ANLPREL_LOPNR", data_type=PostgresType.NUMERIC),
        PostgresColumn(name="ANLSTATUS", data_type=PostgresType.TEXT),
        PostgresColumn(name="ANLSTATUS2", data_type=PostgresType.TEXT),
        PostgresColumn(name="ANSKDATUM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="ANSKVARDE", data_type=PostgresType.NUMERIC),
        PostgresColumn(name="ATERANSK", data_type=PostgresType.NUMERIC),
        PostgresColumn(name="ATERIDX_ID", data_type=PostgresType.TEXT),
        PostgresColumn(name="BER_PLMSLUT_DAT", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="EKDEFANL_ID", data_type=PostgresType.TEXT),
        PostgresColumn(name="EKDEFANL_ID_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="EKLIVS", data_type=PostgresType.NUMERIC),
        PostgresColumn(name="FORSAKR", data_type=PostgresType.NUMERIC),
        PostgresColumn(name="FORSIDX_ID", data_type=PostgresType.TEXT),
        PostgresColumn(name="FRITEXT1", data_type=PostgresType.TEXT),
        PostgresColumn(name="FRITEXT2", data_type=PostgresType.TEXT),
        PostgresColumn(name="FRITEXT3", data_type=PostgresType.TEXT),
        PostgresColumn(name="FRITEXT4", data_type=PostgresType.TEXT),
        PostgresColumn(name="FRITEXT5", data_type=PostgresType.TEXT),
        PostgresColumn(name="ID", data_type=PostgresType.TEXT),
        PostgresColumn(name="KALKIDX_ID", data_type=PostgresType.TEXT),
        PostgresColumn(name="KAPACK", data_type=PostgresType.NUMERIC),
        PostgresColumn(name="KAPPER", data_type=PostgresType.NUMERIC),
        PostgresColumn(name="KAPSEN", data_type=PostgresType.NUMERIC),
        PostgresColumn(name="KAPSEN_DAT", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="KKMACK", data_type=PostgresType.NUMERIC),
        PostgresColumn(name="KKMATER_ANSK", data_type=PostgresType.NUMERIC),
        PostgresColumn(name="KKMPER", data_type=PostgresType.NUMERIC),
        PostgresColumn(name="KKMSEN", data_type=PostgresType.NUMERIC),
        PostgresColumn(name="KKMSEN_DAT", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="KONTO_ANSKV", data_type=PostgresType.TEXT),
        PostgresColumn(name="KONTO_AVSKR", data_type=PostgresType.TEXT),
        PostgresColumn(name="KOPARE", data_type=PostgresType.TEXT),
        PostgresColumn(name="KOSTN_STDATUM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="LEVNAMN", data_type=PostgresType.TEXT),
        PostgresColumn(name="LOPNR", data_type=PostgresType.NUMERIC),
        PostgresColumn(name="NEDSKRBEL", data_type=PostgresType.NUMERIC),
        PostgresColumn(name="PLAN_STDATUM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="PLMPER", data_type=PostgresType.NUMERIC),
        PostgresColumn(name="PLMSEN", data_type=PostgresType.NUMERIC),
        PostgresColumn(name="PLMSEN_DAT", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="PLMSLUT_DAT", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="RESTV", data_type=PostgresType.NUMERIC),
        PostgresColumn(name="SKMACK", data_type=PostgresType.NUMERIC),
        PostgresColumn(name="SKMPER", data_type=PostgresType.NUMERIC),
        PostgresColumn(name="SKMSEN", data_type=PostgresType.NUMERIC),
        PostgresColumn(name="SKMSEN_DAT", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="UPPL_DAT", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="UPPSKRBEL", data_type=PostgresType.NUMERIC),
        PostgresColumn(name="URANSK", data_type=PostgresType.NUMERIC),
        PostgresColumn(name="URANTAL", data_type=PostgresType.NUMERIC),
        PostgresColumn(name="UTR", data_type=PostgresType.NUMERIC),
        PostgresColumn(name="UTR_DAT", data_type=PostgresType.TIMESTAMPTZ),
    ],
    database=Database.POSTGRES,
    cron="0 6 * * *",
    tags=['rlk', 'raindance', 'raw'],
)

@with_env_config
def execute(env: EnvConfig, cfg=config):
    dest_dsn = env_var_dsn("BIG_EKONOMI_EXECUTION_PROD")
    query = """
    SELECT
	CAST(GETDATE() AS DATE) as _data_modified,
	CAST(GETDATE() AS DATETIME2) as _metadata_modified,
	[ACKAVSKR] AS ACKAVSKR,
	COALESCE([ANDR_DAT], '1899-12-31 00:00:00') AS ANDR_DAT,
	[ANDR_SIGN] AS ANDR_SIGN,
	[ANL_ANLTYP_ID] AS ANL_ANLTYP_ID,
	[ANL_ARURSP_ID] AS ANL_ARURSP_ID,
	[ANL_BESTNR_ID] AS ANL_BESTNR_ID,
	[ANL_FN_ID] AS ANL_FN_ID,
	[ANL_FRI1_ID] AS ANL_FRI1_ID,
	[ANL_ITNUM_ID] AS ANL_ITNUM_ID,
	[ANL_KST_ID] AS ANL_KST_ID,
	[ANL_PLAC2_ID] AS ANL_PLAC2_ID,
	[ANL_PLAC_ID] AS ANL_PLAC_ID,
	[ANL_PLAVSK_ID] AS ANL_PLAVSK_ID,
	[ANL_PROJ_ID] AS ANL_PROJ_ID,
	[ANLAGGNING] AS ANLAGGNING,
	[ANLAGGNING2] AS ANLAGGNING2,
	[ANLAGGNING2_ID_TEXT] AS ANLAGGNING2_ID_TEXT,
	[ANLAGGNING_ID_TEXT] AS ANLAGGNING_ID_TEXT,
	[ANLAGGNING_TEXT] AS ANLAGGNING_TEXT,
	[ANLANTAL] AS ANLANTAL,
	COALESCE([ANLBOKAR], '1899-12-31 00:00:00') AS ANLBOKAR,
	[ANLPREL_ID] AS ANLPREL_ID,
	[ANLPREL_LOPNR] AS ANLPREL_LOPNR,
	[ANLSTATUS] AS ANLSTATUS,
	[ANLSTATUS2] AS ANLSTATUS2,
	COALESCE([ANSKDATUM], '1899-12-31 00:00:00') AS ANSKDATUM,
	[ANSKVARDE] AS ANSKVARDE,
	[ATERANSK] AS ATERANSK,
	[ATERIDX_ID] AS ATERIDX_ID,
	COALESCE([BER_PLMSLUT_DAT], '1899-12-31 00:00:00') AS BER_PLMSLUT_DAT,
	[EKDEFANL_ID] AS EKDEFANL_ID,
	[EKDEFANL_ID_TEXT] AS EKDEFANL_ID_TEXT,
	[EKLIVS] AS EKLIVS,
	[FORSAKR] AS FORSAKR,
	[FORSIDX_ID] AS FORSIDX_ID,
	[FRITEXT1] AS FRITEXT1,
	[FRITEXT2] AS FRITEXT2,
	[FRITEXT3] AS FRITEXT3,
	[FRITEXT4] AS FRITEXT4,
	[FRITEXT5] AS FRITEXT5,
	[ID] AS ID,
	[KALKIDX_ID] AS KALKIDX_ID,
	[KAPACK] AS KAPACK,
	[KAPPER] AS KAPPER,
	[KAPSEN] AS KAPSEN,
	COALESCE([KAPSEN_DAT], '1899-12-31 00:00:00') AS KAPSEN_DAT,
	[KKMACK] AS KKMACK,
	[KKMATER_ANSK] AS KKMATER_ANSK,
	[KKMPER] AS KKMPER,
	[KKMSEN] AS KKMSEN,
	COALESCE([KKMSEN_DAT], '1899-12-31 00:00:00') AS KKMSEN_DAT,
	[KONTO_ANSKV] AS KONTO_ANSKV,
	[KONTO_AVSKR] AS KONTO_AVSKR,
	[KOPARE] AS KOPARE,
	COALESCE([KOSTN_STDATUM], '1899-12-31 00:00:00') AS KOSTN_STDATUM,
	[LEVNAMN] AS LEVNAMN,
	[LOPNR] AS LOPNR,
	[NEDSKRBEL] AS NEDSKRBEL,
	COALESCE([PLAN_STDATUM], '1899-12-31 00:00:00') AS PLAN_STDATUM,
	[PLMPER] AS PLMPER,
	[PLMSEN] AS PLMSEN,
	COALESCE([PLMSEN_DAT], '1899-12-31 00:00:00') AS PLMSEN_DAT,
	COALESCE([PLMSLUT_DAT], '1899-12-31 00:00:00') AS PLMSLUT_DAT,
	[RESTV] AS RESTV,
	[SKMACK] AS SKMACK,
	[SKMPER] AS SKMPER,
	[SKMSEN] AS SKMSEN,
	COALESCE([SKMSEN_DAT], '1899-12-31 00:00:00') AS SKMSEN_DAT,
	COALESCE([UPPL_DAT], '1899-12-31 00:00:00') AS UPPL_DAT,
	[UPPSKRBEL] AS UPPSKRBEL,
	[URANSK] AS URANSK,
	[URANTAL] AS URANTAL,
	[UTR] AS UTR,
	COALESCE([UTR_DAT], '1899-12-31 00:00:00') AS UTR_DAT
    FROM [utdata].[utdata295].[AR_DIM_DEFANL]

    """
    total_rows = 0
    first_batch = True
    for df in read("RAINDANCE_2950", query):
        if len(df) == 0:
            continue
        write(cfg, df, dest_dsn)
        if first_batch:
            cfg.write_mode = WriteMode.APPEND
            first_batch = False
        total_rows += len(df)
    print(f"  ✓ {cfg.name}: {total_rows:,} rows written" if total_rows else f"  ⏭ {cfg.name}: no data, skipping")