from bollhav import Model, WriteMode
from bollhav.postgres import PostgresColumn, PostgresType
from bollhav.database import Database
from core import read

config = Model(
    name="ek_dim_obj_konto",
    source_entity="EK_DIM_OBJ_KONTO",
    table="ek_dim_obj_konto",
    schema="raindance_raw_8510",
    write_mode=WriteMode.TRUNCATE_INSERT,
    columns=[
        PostgresColumn(name="_data_modified", data_type=PostgresType.DATE),
        PostgresColumn(name="_metadata_modified", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="A1_GILTIG_FOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="A1_GILTIG_TOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="A1_ID", data_type=PostgresType.TEXT),
        PostgresColumn(name="A1_ID_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="A1_PASSIV", data_type=PostgresType.BOOLEAN),
        PostgresColumn(name="A1_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="A2_GILTIG_FOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="A2_GILTIG_TOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="A2_ID", data_type=PostgresType.TEXT),
        PostgresColumn(name="A2_ID_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="A2_PASSIV", data_type=PostgresType.BOOLEAN),
        PostgresColumn(name="A2_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="A3_GILTIG_FOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="A3_GILTIG_TOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="A3_ID", data_type=PostgresType.TEXT),
        PostgresColumn(name="A3_ID_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="A3_PASSIV", data_type=PostgresType.BOOLEAN),
        PostgresColumn(name="A3_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="C1_GILTIG_FOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="C1_GILTIG_TOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="C1_ID", data_type=PostgresType.TEXT),
        PostgresColumn(name="C1_ID_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="C1_PASSIV", data_type=PostgresType.BOOLEAN),
        PostgresColumn(name="C1_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="C2_GILTIG_FOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="C2_GILTIG_TOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="C2_ID", data_type=PostgresType.TEXT),
        PostgresColumn(name="C2_ID_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="C2_PASSIV", data_type=PostgresType.BOOLEAN),
        PostgresColumn(name="C2_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="C3_GILTIG_FOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="C3_GILTIG_TOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="C3_ID", data_type=PostgresType.TEXT),
        PostgresColumn(name="C3_ID_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="C3_PASSIV", data_type=PostgresType.BOOLEAN),
        PostgresColumn(name="C3_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="D3_GILTIG_FOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="D3_GILTIG_TOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="D3_ID", data_type=PostgresType.TEXT),
        PostgresColumn(name="D3_ID_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="D3_PASSIV", data_type=PostgresType.BOOLEAN),
        PostgresColumn(name="D3_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="DSRRK_GILTIG_FOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="DSRRK_GILTIG_TOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="DSRRK_ID", data_type=PostgresType.TEXT),
        PostgresColumn(name="DSRRK_ID_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="DSRRK_PASSIV", data_type=PostgresType.BOOLEAN),
        PostgresColumn(name="DSRRK_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="DSRRL_GILTIG_FOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="DSRRL_GILTIG_TOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="DSRRL_ID", data_type=PostgresType.TEXT),
        PostgresColumn(name="DSRRL_ID_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="DSRRL_PASSIV", data_type=PostgresType.BOOLEAN),
        PostgresColumn(name="DSRRL_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="FRA1I_GILTIG_FOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="FRA1I_GILTIG_TOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="FRA1I_ID", data_type=PostgresType.TEXT),
        PostgresColumn(name="FRA1I_ID_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="FRA1I_PASSIV", data_type=PostgresType.BOOLEAN),
        PostgresColumn(name="FRA1I_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="FRANGI_GILTIG_FOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="FRANGI_GILTIG_TOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="FRANGI_ID", data_type=PostgresType.TEXT),
        PostgresColumn(name="FRANGI_ID_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="FRANGI_PASSIV", data_type=PostgresType.BOOLEAN),
        PostgresColumn(name="FRANGI_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="GFRA1_GILTIG_FOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="GFRA1_GILTIG_TOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="GFRA1_ID", data_type=PostgresType.TEXT),
        PostgresColumn(name="GFRA1_ID_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="GFRA1_PASSIV", data_type=PostgresType.BOOLEAN),
        PostgresColumn(name="GFRA1_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="GFRA1I_GILTIG_FOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="GFRA1I_GILTIG_TOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="GFRA1I_ID", data_type=PostgresType.TEXT),
        PostgresColumn(name="GFRA1I_ID_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="GFRA1I_PASSIV", data_type=PostgresType.BOOLEAN),
        PostgresColumn(name="GFRA1I_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="GRANGI_GILTIG_FOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="GRANGI_GILTIG_TOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="GRANGI_ID", data_type=PostgresType.TEXT),
        PostgresColumn(name="GRANGI_ID_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="GRANGI_PASSIV", data_type=PostgresType.BOOLEAN),
        PostgresColumn(name="GRANGI_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="GRANGO_GILTIG_FOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="GRANGO_GILTIG_TOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="GRANGO_ID", data_type=PostgresType.TEXT),
        PostgresColumn(name="GRANGO_ID_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="GRANGO_PASSIV", data_type=PostgresType.BOOLEAN),
        PostgresColumn(name="GRANGO_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="KKTO1_GILTIG_FOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="KKTO1_GILTIG_TOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="KKTO1_ID", data_type=PostgresType.TEXT),
        PostgresColumn(name="KKTO1_ID_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="KKTO1_PASSIV", data_type=PostgresType.BOOLEAN),
        PostgresColumn(name="KKTO1_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="KKTO_GILTIG_FOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="KKTO_GILTIG_TOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="KKTO_ID", data_type=PostgresType.TEXT),
        PostgresColumn(name="KKTO_ID_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="KKTO_PASSIV", data_type=PostgresType.BOOLEAN),
        PostgresColumn(name="KKTO_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="KONTO_GILTIG_FOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="KONTO_GILTIG_TOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="KONTO_ID", data_type=PostgresType.TEXT),
        PostgresColumn(name="KONTO_ID_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="KONTO_PASSIV", data_type=PostgresType.BOOLEAN),
        PostgresColumn(name="KONTO_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="M2_GILTIG_FOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="M2_GILTIG_TOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="M2_ID", data_type=PostgresType.TEXT),
        PostgresColumn(name="M2_ID_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="M2_PASSIV", data_type=PostgresType.BOOLEAN),
        PostgresColumn(name="M2_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="M3_GILTIG_FOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="M3_GILTIG_TOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="M3_ID", data_type=PostgresType.TEXT),
        PostgresColumn(name="M3_ID_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="M3_PASSIV", data_type=PostgresType.BOOLEAN),
        PostgresColumn(name="M3_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="SKKTO1_GILTIG_FOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="SKKTO1_GILTIG_TOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="SKKTO1_ID", data_type=PostgresType.TEXT),
        PostgresColumn(name="SKKTO1_ID_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="SKKTO1_PASSIV", data_type=PostgresType.BOOLEAN),
        PostgresColumn(name="SKKTO1_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="SKKTO_GILTIG_FOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="SKKTO_GILTIG_TOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="SKKTO_ID", data_type=PostgresType.TEXT),
        PostgresColumn(name="SKKTO_ID_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="SKKTO_PASSIV", data_type=PostgresType.BOOLEAN),
        PostgresColumn(name="SKKTO_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="SRU2_GILTIG_FOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="SRU2_GILTIG_TOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="SRU2_ID", data_type=PostgresType.TEXT),
        PostgresColumn(name="SRU2_ID_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="SRU2_PASSIV", data_type=PostgresType.BOOLEAN),
        PostgresColumn(name="SRU2_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="SRU_GILTIG_FOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="SRU_GILTIG_TOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="SRU_ID", data_type=PostgresType.TEXT),
        PostgresColumn(name="SRU_ID_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="SRU_PASSIV", data_type=PostgresType.BOOLEAN),
        PostgresColumn(name="SRU_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="UPPH_GILTIG_FOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="UPPH_GILTIG_TOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="UPPH_ID", data_type=PostgresType.TEXT),
        PostgresColumn(name="UPPH_ID_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="UPPH_PASSIV", data_type=PostgresType.BOOLEAN),
        PostgresColumn(name="UPPH_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="XB1_GILTIG_FOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="XB1_GILTIG_TOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="XB1_ID", data_type=PostgresType.TEXT),
        PostgresColumn(name="XB1_ID_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="XB1_PASSIV", data_type=PostgresType.BOOLEAN),
        PostgresColumn(name="XB1_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="XB2_GILTIG_FOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="XB2_GILTIG_TOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="XB2_ID", data_type=PostgresType.TEXT),
        PostgresColumn(name="XB2_ID_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="XB2_PASSIV", data_type=PostgresType.BOOLEAN),
        PostgresColumn(name="XB2_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="XDSRRK_GILTIG_FOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="XDSRRK_GILTIG_TOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="XDSRRK_ID", data_type=PostgresType.TEXT),
        PostgresColumn(name="XDSRRK_ID_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="XDSRRK_PASSIV", data_type=PostgresType.BOOLEAN),
        PostgresColumn(name="XDSRRK_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="XDSRRL_GILTIG_FOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="XDSRRL_GILTIG_TOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="XDSRRL_ID", data_type=PostgresType.TEXT),
        PostgresColumn(name="XDSRRL_ID_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="XDSRRL_PASSIV", data_type=PostgresType.BOOLEAN),
        PostgresColumn(name="XDSRRL_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="XKKTO2_GILTIG_FOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="XKKTO2_GILTIG_TOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="XKKTO2_ID", data_type=PostgresType.TEXT),
        PostgresColumn(name="XKKTO2_ID_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="XKKTO2_PASSIV", data_type=PostgresType.BOOLEAN),
        PostgresColumn(name="XKKTO2_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="XKTO2_GILTIG_FOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="XKTO2_GILTIG_TOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="XKTO2_ID", data_type=PostgresType.TEXT),
        PostgresColumn(name="XKTO2_ID_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="XKTO2_PASSIV", data_type=PostgresType.BOOLEAN),
        PostgresColumn(name="XKTO2_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="XXFRA1_GILTIG_FOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="XXFRA1_GILTIG_TOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="XXFRA1_ID", data_type=PostgresType.TEXT),
        PostgresColumn(name="XXFRA1_ID_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="XXFRA1_PASSIV", data_type=PostgresType.BOOLEAN),
        PostgresColumn(name="XXFRA1_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="XXRA1I_GILTIG_FOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="XXRA1I_GILTIG_TOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="XXRA1I_ID", data_type=PostgresType.TEXT),
        PostgresColumn(name="XXRA1I_ID_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="XXRA1I_PASSIV", data_type=PostgresType.BOOLEAN),
        PostgresColumn(name="XXRA1I_TEXT", data_type=PostgresType.TEXT),
    ],
    database=Database.POSTGRES,
    cron="0 6 * * *",
    tags=['dan', 'raindance', 'raw'],
)

def execute(env, cfg=config):
    query=f"""SELECT * FROM (SELECT
    	CAST(GETDATE() AS DATE) as _data_modified,
    	CAST(GETDATE() AS DATETIME2) as _metadata_modified,
    	COALESCE([A1_GILTIG_FOM], '1899-12-31 00:00:00') AS A1_GILTIG_FOM,
    	COALESCE([A1_GILTIG_TOM], '1899-12-31 00:00:00') AS A1_GILTIG_TOM,
    	[A1_ID] AS A1_ID,
    	[A1_ID_TEXT] AS A1_ID_TEXT,
    	[A1_PASSIV] AS A1_PASSIV,
    	[A1_TEXT] AS A1_TEXT,
    	COALESCE([A2_GILTIG_FOM], '1899-12-31 00:00:00') AS A2_GILTIG_FOM,
    	COALESCE([A2_GILTIG_TOM], '1899-12-31 00:00:00') AS A2_GILTIG_TOM,
    	[A2_ID] AS A2_ID,
    	[A2_ID_TEXT] AS A2_ID_TEXT,
    	[A2_PASSIV] AS A2_PASSIV,
    	[A2_TEXT] AS A2_TEXT,
    	COALESCE([A3_GILTIG_FOM], '1899-12-31 00:00:00') AS A3_GILTIG_FOM,
    	COALESCE([A3_GILTIG_TOM], '1899-12-31 00:00:00') AS A3_GILTIG_TOM,
    	[A3_ID] AS A3_ID,
    	[A3_ID_TEXT] AS A3_ID_TEXT,
    	[A3_PASSIV] AS A3_PASSIV,
    	[A3_TEXT] AS A3_TEXT,
    	COALESCE([C1_GILTIG_FOM], '1899-12-31 00:00:00') AS C1_GILTIG_FOM,
    	COALESCE([C1_GILTIG_TOM], '1899-12-31 00:00:00') AS C1_GILTIG_TOM,
    	[C1_ID] AS C1_ID,
    	[C1_ID_TEXT] AS C1_ID_TEXT,
    	[C1_PASSIV] AS C1_PASSIV,
    	[C1_TEXT] AS C1_TEXT,
    	COALESCE([C2_GILTIG_FOM], '1899-12-31 00:00:00') AS C2_GILTIG_FOM,
    	COALESCE([C2_GILTIG_TOM], '1899-12-31 00:00:00') AS C2_GILTIG_TOM,
    	[C2_ID] AS C2_ID,
    	[C2_ID_TEXT] AS C2_ID_TEXT,
    	[C2_PASSIV] AS C2_PASSIV,
    	[C2_TEXT] AS C2_TEXT,
    	COALESCE([C3_GILTIG_FOM], '1899-12-31 00:00:00') AS C3_GILTIG_FOM,
    	COALESCE([C3_GILTIG_TOM], '1899-12-31 00:00:00') AS C3_GILTIG_TOM,
    	[C3_ID] AS C3_ID,
    	[C3_ID_TEXT] AS C3_ID_TEXT,
    	[C3_PASSIV] AS C3_PASSIV,
    	[C3_TEXT] AS C3_TEXT,
    	COALESCE([D3_GILTIG_FOM], '1899-12-31 00:00:00') AS D3_GILTIG_FOM,
    	COALESCE([D3_GILTIG_TOM], '1899-12-31 00:00:00') AS D3_GILTIG_TOM,
    	[D3_ID] AS D3_ID,
    	[D3_ID_TEXT] AS D3_ID_TEXT,
    	[D3_PASSIV] AS D3_PASSIV,
    	[D3_TEXT] AS D3_TEXT,
    	COALESCE([DSRRK_GILTIG_FOM], '1899-12-31 00:00:00') AS DSRRK_GILTIG_FOM,
    	COALESCE([DSRRK_GILTIG_TOM], '1899-12-31 00:00:00') AS DSRRK_GILTIG_TOM,
    	[DSRRK_ID] AS DSRRK_ID,
    	[DSRRK_ID_TEXT] AS DSRRK_ID_TEXT,
    	[DSRRK_PASSIV] AS DSRRK_PASSIV,
    	[DSRRK_TEXT] AS DSRRK_TEXT,
    	COALESCE([DSRRL_GILTIG_FOM], '1899-12-31 00:00:00') AS DSRRL_GILTIG_FOM,
    	COALESCE([DSRRL_GILTIG_TOM], '1899-12-31 00:00:00') AS DSRRL_GILTIG_TOM,
    	[DSRRL_ID] AS DSRRL_ID,
    	[DSRRL_ID_TEXT] AS DSRRL_ID_TEXT,
    	[DSRRL_PASSIV] AS DSRRL_PASSIV,
    	[DSRRL_TEXT] AS DSRRL_TEXT,
    	COALESCE([FRA1I_GILTIG_FOM], '1899-12-31 00:00:00') AS FRA1I_GILTIG_FOM,
    	COALESCE([FRA1I_GILTIG_TOM], '1899-12-31 00:00:00') AS FRA1I_GILTIG_TOM,
    	[FRA1I_ID] AS FRA1I_ID,
    	[FRA1I_ID_TEXT] AS FRA1I_ID_TEXT,
    	[FRA1I_PASSIV] AS FRA1I_PASSIV,
    	[FRA1I_TEXT] AS FRA1I_TEXT,
    	COALESCE([FRANGI_GILTIG_FOM], '1899-12-31 00:00:00') AS FRANGI_GILTIG_FOM,
    	COALESCE([FRANGI_GILTIG_TOM], '1899-12-31 00:00:00') AS FRANGI_GILTIG_TOM,
    	[FRANGI_ID] AS FRANGI_ID,
    	[FRANGI_ID_TEXT] AS FRANGI_ID_TEXT,
    	[FRANGI_PASSIV] AS FRANGI_PASSIV,
    	[FRANGI_TEXT] AS FRANGI_TEXT,
    	COALESCE([GFRA1_GILTIG_FOM], '1899-12-31 00:00:00') AS GFRA1_GILTIG_FOM,
    	COALESCE([GFRA1_GILTIG_TOM], '1899-12-31 00:00:00') AS GFRA1_GILTIG_TOM,
    	[GFRA1_ID] AS GFRA1_ID,
    	[GFRA1_ID_TEXT] AS GFRA1_ID_TEXT,
    	[GFRA1_PASSIV] AS GFRA1_PASSIV,
    	[GFRA1_TEXT] AS GFRA1_TEXT,
    	COALESCE([GFRA1I_GILTIG_FOM], '1899-12-31 00:00:00') AS GFRA1I_GILTIG_FOM,
    	COALESCE([GFRA1I_GILTIG_TOM], '1899-12-31 00:00:00') AS GFRA1I_GILTIG_TOM,
    	[GFRA1I_ID] AS GFRA1I_ID,
    	[GFRA1I_ID_TEXT] AS GFRA1I_ID_TEXT,
    	[GFRA1I_PASSIV] AS GFRA1I_PASSIV,
    	[GFRA1I_TEXT] AS GFRA1I_TEXT,
    	COALESCE([GRANGI_GILTIG_FOM], '1899-12-31 00:00:00') AS GRANGI_GILTIG_FOM,
    	COALESCE([GRANGI_GILTIG_TOM], '1899-12-31 00:00:00') AS GRANGI_GILTIG_TOM,
    	[GRANGI_ID] AS GRANGI_ID,
    	[GRANGI_ID_TEXT] AS GRANGI_ID_TEXT,
    	[GRANGI_PASSIV] AS GRANGI_PASSIV,
    	[GRANGI_TEXT] AS GRANGI_TEXT,
    	COALESCE([GRANGO_GILTIG_FOM], '1899-12-31 00:00:00') AS GRANGO_GILTIG_FOM,
    	COALESCE([GRANGO_GILTIG_TOM], '1899-12-31 00:00:00') AS GRANGO_GILTIG_TOM,
    	[GRANGO_ID] AS GRANGO_ID,
    	[GRANGO_ID_TEXT] AS GRANGO_ID_TEXT,
    	[GRANGO_PASSIV] AS GRANGO_PASSIV,
    	[GRANGO_TEXT] AS GRANGO_TEXT,
    	COALESCE([KKTO1_GILTIG_FOM], '1899-12-31 00:00:00') AS KKTO1_GILTIG_FOM,
    	COALESCE([KKTO1_GILTIG_TOM], '1899-12-31 00:00:00') AS KKTO1_GILTIG_TOM,
    	[KKTO1_ID] AS KKTO1_ID,
    	[KKTO1_ID_TEXT] AS KKTO1_ID_TEXT,
    	[KKTO1_PASSIV] AS KKTO1_PASSIV,
    	[KKTO1_TEXT] AS KKTO1_TEXT,
    	COALESCE([KKTO_GILTIG_FOM], '1899-12-31 00:00:00') AS KKTO_GILTIG_FOM,
    	COALESCE([KKTO_GILTIG_TOM], '1899-12-31 00:00:00') AS KKTO_GILTIG_TOM,
    	[KKTO_ID] AS KKTO_ID,
    	[KKTO_ID_TEXT] AS KKTO_ID_TEXT,
    	[KKTO_PASSIV] AS KKTO_PASSIV,
    	[KKTO_TEXT] AS KKTO_TEXT,
    	COALESCE([KONTO_GILTIG_FOM], '1899-12-31 00:00:00') AS KONTO_GILTIG_FOM,
    	COALESCE([KONTO_GILTIG_TOM], '1899-12-31 00:00:00') AS KONTO_GILTIG_TOM,
    	[KONTO_ID] AS KONTO_ID,
    	[KONTO_ID_TEXT] AS KONTO_ID_TEXT,
    	[KONTO_PASSIV] AS KONTO_PASSIV,
    	[KONTO_TEXT] AS KONTO_TEXT,
    	COALESCE([M2_GILTIG_FOM], '1899-12-31 00:00:00') AS M2_GILTIG_FOM,
    	COALESCE([M2_GILTIG_TOM], '1899-12-31 00:00:00') AS M2_GILTIG_TOM,
    	[M2_ID] AS M2_ID,
    	[M2_ID_TEXT] AS M2_ID_TEXT,
    	[M2_PASSIV] AS M2_PASSIV,
    	[M2_TEXT] AS M2_TEXT,
    	COALESCE([M3_GILTIG_FOM], '1899-12-31 00:00:00') AS M3_GILTIG_FOM,
    	COALESCE([M3_GILTIG_TOM], '1899-12-31 00:00:00') AS M3_GILTIG_TOM,
    	[M3_ID] AS M3_ID,
    	[M3_ID_TEXT] AS M3_ID_TEXT,
    	[M3_PASSIV] AS M3_PASSIV,
    	[M3_TEXT] AS M3_TEXT,
    	COALESCE([SKKTO1_GILTIG_FOM], '1899-12-31 00:00:00') AS SKKTO1_GILTIG_FOM,
    	COALESCE([SKKTO1_GILTIG_TOM], '1899-12-31 00:00:00') AS SKKTO1_GILTIG_TOM,
    	[SKKTO1_ID] AS SKKTO1_ID,
    	[SKKTO1_ID_TEXT] AS SKKTO1_ID_TEXT,
    	[SKKTO1_PASSIV] AS SKKTO1_PASSIV,
    	[SKKTO1_TEXT] AS SKKTO1_TEXT,
    	COALESCE([SKKTO_GILTIG_FOM], '1899-12-31 00:00:00') AS SKKTO_GILTIG_FOM,
    	COALESCE([SKKTO_GILTIG_TOM], '1899-12-31 00:00:00') AS SKKTO_GILTIG_TOM,
    	[SKKTO_ID] AS SKKTO_ID,
    	[SKKTO_ID_TEXT] AS SKKTO_ID_TEXT,
    	[SKKTO_PASSIV] AS SKKTO_PASSIV,
    	[SKKTO_TEXT] AS SKKTO_TEXT,
    	COALESCE([SRU2_GILTIG_FOM], '1899-12-31 00:00:00') AS SRU2_GILTIG_FOM,
    	COALESCE([SRU2_GILTIG_TOM], '1899-12-31 00:00:00') AS SRU2_GILTIG_TOM,
    	[SRU2_ID] AS SRU2_ID,
    	[SRU2_ID_TEXT] AS SRU2_ID_TEXT,
    	[SRU2_PASSIV] AS SRU2_PASSIV,
    	[SRU2_TEXT] AS SRU2_TEXT,
    	COALESCE([SRU_GILTIG_FOM], '1899-12-31 00:00:00') AS SRU_GILTIG_FOM,
    	COALESCE([SRU_GILTIG_TOM], '1899-12-31 00:00:00') AS SRU_GILTIG_TOM,
    	[SRU_ID] AS SRU_ID,
    	[SRU_ID_TEXT] AS SRU_ID_TEXT,
    	[SRU_PASSIV] AS SRU_PASSIV,
    	[SRU_TEXT] AS SRU_TEXT,
    	COALESCE([UPPH_GILTIG_FOM], '1899-12-31 00:00:00') AS UPPH_GILTIG_FOM,
    	COALESCE([UPPH_GILTIG_TOM], '1899-12-31 00:00:00') AS UPPH_GILTIG_TOM,
    	[UPPH_ID] AS UPPH_ID,
    	[UPPH_ID_TEXT] AS UPPH_ID_TEXT,
    	[UPPH_PASSIV] AS UPPH_PASSIV,
    	[UPPH_TEXT] AS UPPH_TEXT,
    	COALESCE([XB1_GILTIG_FOM], '1899-12-31 00:00:00') AS XB1_GILTIG_FOM,
    	COALESCE([XB1_GILTIG_TOM], '1899-12-31 00:00:00') AS XB1_GILTIG_TOM,
    	[XB1_ID] AS XB1_ID,
    	[XB1_ID_TEXT] AS XB1_ID_TEXT,
    	[XB1_PASSIV] AS XB1_PASSIV,
    	[XB1_TEXT] AS XB1_TEXT,
    	COALESCE([XB2_GILTIG_FOM], '1899-12-31 00:00:00') AS XB2_GILTIG_FOM,
    	COALESCE([XB2_GILTIG_TOM], '1899-12-31 00:00:00') AS XB2_GILTIG_TOM,
    	[XB2_ID] AS XB2_ID,
    	[XB2_ID_TEXT] AS XB2_ID_TEXT,
    	[XB2_PASSIV] AS XB2_PASSIV,
    	[XB2_TEXT] AS XB2_TEXT,
    	COALESCE([XDSRRK_GILTIG_FOM], '1899-12-31 00:00:00') AS XDSRRK_GILTIG_FOM,
    	COALESCE([XDSRRK_GILTIG_TOM], '1899-12-31 00:00:00') AS XDSRRK_GILTIG_TOM,
    	[XDSRRK_ID] AS XDSRRK_ID,
    	[XDSRRK_ID_TEXT] AS XDSRRK_ID_TEXT,
    	[XDSRRK_PASSIV] AS XDSRRK_PASSIV,
    	[XDSRRK_TEXT] AS XDSRRK_TEXT,
    	COALESCE([XDSRRL_GILTIG_FOM], '1899-12-31 00:00:00') AS XDSRRL_GILTIG_FOM,
    	COALESCE([XDSRRL_GILTIG_TOM], '1899-12-31 00:00:00') AS XDSRRL_GILTIG_TOM,
    	[XDSRRL_ID] AS XDSRRL_ID,
    	[XDSRRL_ID_TEXT] AS XDSRRL_ID_TEXT,
    	[XDSRRL_PASSIV] AS XDSRRL_PASSIV,
    	[XDSRRL_TEXT] AS XDSRRL_TEXT,
    	COALESCE([XKKTO2_GILTIG_FOM], '1899-12-31 00:00:00') AS XKKTO2_GILTIG_FOM,
    	COALESCE([XKKTO2_GILTIG_TOM], '1899-12-31 00:00:00') AS XKKTO2_GILTIG_TOM,
    	[XKKTO2_ID] AS XKKTO2_ID,
    	[XKKTO2_ID_TEXT] AS XKKTO2_ID_TEXT,
    	[XKKTO2_PASSIV] AS XKKTO2_PASSIV,
    	[XKKTO2_TEXT] AS XKKTO2_TEXT,
    	COALESCE([XKTO2_GILTIG_FOM], '1899-12-31 00:00:00') AS XKTO2_GILTIG_FOM,
    	COALESCE([XKTO2_GILTIG_TOM], '1899-12-31 00:00:00') AS XKTO2_GILTIG_TOM,
    	[XKTO2_ID] AS XKTO2_ID,
    	[XKTO2_ID_TEXT] AS XKTO2_ID_TEXT,
    	[XKTO2_PASSIV] AS XKTO2_PASSIV,
    	[XKTO2_TEXT] AS XKTO2_TEXT,
    	COALESCE([XXFRA1_GILTIG_FOM], '1899-12-31 00:00:00') AS XXFRA1_GILTIG_FOM,
    	COALESCE([XXFRA1_GILTIG_TOM], '1899-12-31 00:00:00') AS XXFRA1_GILTIG_TOM,
    	[XXFRA1_ID] AS XXFRA1_ID,
    	[XXFRA1_ID_TEXT] AS XXFRA1_ID_TEXT,
    	[XXFRA1_PASSIV] AS XXFRA1_PASSIV,
    	[XXFRA1_TEXT] AS XXFRA1_TEXT,
    	COALESCE([XXRA1I_GILTIG_FOM], '1899-12-31 00:00:00') AS XXRA1I_GILTIG_FOM,
    	COALESCE([XXRA1I_GILTIG_TOM], '1899-12-31 00:00:00') AS XXRA1I_GILTIG_TOM,
    	[XXRA1I_ID] AS XXRA1I_ID,
    	[XXRA1I_ID_TEXT] AS XXRA1I_ID_TEXT,
    	[XXRA1I_PASSIV] AS XXRA1I_PASSIV,
    	[XXRA1I_TEXT] AS XXRA1I_TEXT
    FROM [raindance_udp].[udp_150].[EK_DIM_OBJ_KONTO]) y
    WHERE 1=1"""
    yield from read(query=query, env_var_name='RAINDANCE_8510')