from bollhav import Model, WriteMode
from bollhav.postgres import PostgresColumn, PostgresType
from bollhav.database import Database
from core import read

config = Model(
    name="ek_dim_obj_motp",
    source_entity="EK_DIM_OBJ_MOTP",
    table="ek_dim_obj_motp",
    schema="raindance_raw_8530",
    write_mode=WriteMode.TRUNCATE_INSERT,
    columns=[
        PostgresColumn(name="_data_modified", data_type=PostgresType.DATE),
        PostgresColumn(name="_metadata_modified", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="DIVMP_GILTIG_FOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="DIVMP_GILTIG_TOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="DIVMP_ID", data_type=PostgresType.TEXT),
        PostgresColumn(name="DIVMP_ID_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="DIVMP_PASSIV", data_type=PostgresType.BOOLEAN),
        PostgresColumn(name="DIVMP_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="EKOD_GILTIG_FOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="EKOD_GILTIG_TOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="EKOD_ID", data_type=PostgresType.TEXT),
        PostgresColumn(name="EKOD_ID_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="EKOD_PASSIV", data_type=PostgresType.BOOLEAN),
        PostgresColumn(name="EKOD_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="IMOTPB_GILTIG_FOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="IMOTPB_GILTIG_TOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="IMOTPB_ID", data_type=PostgresType.TEXT),
        PostgresColumn(name="IMOTPB_ID_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="IMOTPB_PASSIV", data_type=PostgresType.BOOLEAN),
        PostgresColumn(name="IMOTPB_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="KMOTP_GILTIG_FOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="KMOTP_GILTIG_TOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="KMOTP_ID", data_type=PostgresType.TEXT),
        PostgresColumn(name="KMOTP_ID_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="KMOTP_PASSIV", data_type=PostgresType.BOOLEAN),
        PostgresColumn(name="KMOTP_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="MOTP_GILTIG_FOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="MOTP_GILTIG_TOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="MOTP_ID", data_type=PostgresType.TEXT),
        PostgresColumn(name="MOTP_ID_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="MOTP_PASSIV", data_type=PostgresType.BOOLEAN),
        PostgresColumn(name="MOTP_TEXT", data_type=PostgresType.TEXT),
    ],
    database=Database.POSTGRES,
    cron="0 6 * * *",
    tags=['ste', 'raindance', 'raw'],
)

def execute(env, cfg=config):
    query=f"""SELECT * FROM (SELECT
    	CAST(GETDATE() AS DATE) as _data_modified,
    	CAST(GETDATE() AS DATETIME2) as _metadata_modified,
    	COALESCE([DIVMP_GILTIG_FOM], '1899-12-31 00:00:00') AS DIVMP_GILTIG_FOM,
    	COALESCE([DIVMP_GILTIG_TOM], '1899-12-31 00:00:00') AS DIVMP_GILTIG_TOM,
    	[DIVMP_ID] AS DIVMP_ID,
    	[DIVMP_ID_TEXT] AS DIVMP_ID_TEXT,
    	[DIVMP_PASSIV] AS DIVMP_PASSIV,
    	[DIVMP_TEXT] AS DIVMP_TEXT,
    	COALESCE([EKOD_GILTIG_FOM], '1899-12-31 00:00:00') AS EKOD_GILTIG_FOM,
    	COALESCE([EKOD_GILTIG_TOM], '1899-12-31 00:00:00') AS EKOD_GILTIG_TOM,
    	[EKOD_ID] AS EKOD_ID,
    	[EKOD_ID_TEXT] AS EKOD_ID_TEXT,
    	[EKOD_PASSIV] AS EKOD_PASSIV,
    	[EKOD_TEXT] AS EKOD_TEXT,
    	COALESCE([IMOTPB_GILTIG_FOM], '1899-12-31 00:00:00') AS IMOTPB_GILTIG_FOM,
    	COALESCE([IMOTPB_GILTIG_TOM], '1899-12-31 00:00:00') AS IMOTPB_GILTIG_TOM,
    	[IMOTPB_ID] AS IMOTPB_ID,
    	[IMOTPB_ID_TEXT] AS IMOTPB_ID_TEXT,
    	[IMOTPB_PASSIV] AS IMOTPB_PASSIV,
    	[IMOTPB_TEXT] AS IMOTPB_TEXT,
    	COALESCE([KMOTP_GILTIG_FOM], '1899-12-31 00:00:00') AS KMOTP_GILTIG_FOM,
    	COALESCE([KMOTP_GILTIG_TOM], '1899-12-31 00:00:00') AS KMOTP_GILTIG_TOM,
    	[KMOTP_ID] AS KMOTP_ID,
    	[KMOTP_ID_TEXT] AS KMOTP_ID_TEXT,
    	[KMOTP_PASSIV] AS KMOTP_PASSIV,
    	[KMOTP_TEXT] AS KMOTP_TEXT,
    	COALESCE([MOTP_GILTIG_FOM], '1899-12-31 00:00:00') AS MOTP_GILTIG_FOM,
    	COALESCE([MOTP_GILTIG_TOM], '1899-12-31 00:00:00') AS MOTP_GILTIG_TOM,
    	[MOTP_ID] AS MOTP_ID,
    	[MOTP_ID_TEXT] AS MOTP_ID_TEXT,
    	[MOTP_PASSIV] AS MOTP_PASSIV,
    	[MOTP_TEXT] AS MOTP_TEXT
    FROM [steudp].[udp_600].[EK_DIM_OBJ_MOTP]) y
    WHERE 1=1"""
    yield from read(query=query, env_var_name='RAINDANCE_8530')