from bollhav import Model, WriteMode
from bollhav.postgres import PostgresColumn, PostgresType
from bollhav.database import Database
from core import read

config = Model(
    name="ek_dim_obj_avtbes",
    source_entity="EK_DIM_OBJ_AVTBES",
    table="ek_dim_obj_avtbes",
    schema="raindance_raw_nks",
    write_mode=WriteMode.TRUNCATE_INSERT,
    columns=[
        PostgresColumn(name="_data_modified", data_type=PostgresType.DATE),
        PostgresColumn(name="_metadata_modified", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="AVTBES_GILTIG_FOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="AVTBES_GILTIG_TOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="AVTBES_ID", data_type=PostgresType.TEXT),
        PostgresColumn(name="AVTBES_ID_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="AVTBES_PASSIV", data_type=PostgresType.BOOLEAN),
        PostgresColumn(name="AVTBES_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="BCHEF_GILTIG_FOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="BCHEF_GILTIG_TOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="BCHEF_ID", data_type=PostgresType.TEXT),
        PostgresColumn(name="BCHEF_ID_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="BCHEF_PASSIV", data_type=PostgresType.BOOLEAN),
        PostgresColumn(name="BCHEF_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="BGRP_GILTIG_FOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="BGRP_GILTIG_TOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="BGRP_ID", data_type=PostgresType.TEXT),
        PostgresColumn(name="BGRP_ID_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="BGRP_PASSIV", data_type=PostgresType.BOOLEAN),
        PostgresColumn(name="BGRP_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="BHANDL_GILTIG_FOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="BHANDL_GILTIG_TOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="BHANDL_ID", data_type=PostgresType.TEXT),
        PostgresColumn(name="BHANDL_ID_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="BHANDL_PASSIV", data_type=PostgresType.BOOLEAN),
        PostgresColumn(name="BHANDL_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="BSTAT_GILTIG_FOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="BSTAT_GILTIG_TOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="BSTAT_ID", data_type=PostgresType.TEXT),
        PostgresColumn(name="BSTAT_ID_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="BSTAT_PASSIV", data_type=PostgresType.BOOLEAN),
        PostgresColumn(name="BSTAT_TEXT", data_type=PostgresType.TEXT),
    ],
    database=Database.POSTGRES,
    cron="0 6 * * *",
    tags=['nks', 'raindance', 'raw'],
)

def execute(env, cfg=config):
    query=f"""SELECT * FROM (SELECT
    	CAST(GETDATE() AS DATE) as _data_modified,
    	CAST(GETDATE() AS DATETIME2) as _metadata_modified,
    	COALESCE([AVTBES_GILTIG_FOM], '1899-12-31 00:00:00') AS AVTBES_GILTIG_FOM,
    	COALESCE([AVTBES_GILTIG_TOM], '1899-12-31 00:00:00') AS AVTBES_GILTIG_TOM,
    	[AVTBES_ID] AS AVTBES_ID,
    	[AVTBES_ID_TEXT] AS AVTBES_ID_TEXT,
    	[AVTBES_PASSIV] AS AVTBES_PASSIV,
    	[AVTBES_TEXT] AS AVTBES_TEXT,
    	COALESCE([BCHEF_GILTIG_FOM], '1899-12-31 00:00:00') AS BCHEF_GILTIG_FOM,
    	COALESCE([BCHEF_GILTIG_TOM], '1899-12-31 00:00:00') AS BCHEF_GILTIG_TOM,
    	[BCHEF_ID] AS BCHEF_ID,
    	[BCHEF_ID_TEXT] AS BCHEF_ID_TEXT,
    	[BCHEF_PASSIV] AS BCHEF_PASSIV,
    	[BCHEF_TEXT] AS BCHEF_TEXT,
    	COALESCE([BGRP_GILTIG_FOM], '1899-12-31 00:00:00') AS BGRP_GILTIG_FOM,
    	COALESCE([BGRP_GILTIG_TOM], '1899-12-31 00:00:00') AS BGRP_GILTIG_TOM,
    	[BGRP_ID] AS BGRP_ID,
    	[BGRP_ID_TEXT] AS BGRP_ID_TEXT,
    	[BGRP_PASSIV] AS BGRP_PASSIV,
    	[BGRP_TEXT] AS BGRP_TEXT,
    	COALESCE([BHANDL_GILTIG_FOM], '1899-12-31 00:00:00') AS BHANDL_GILTIG_FOM,
    	COALESCE([BHANDL_GILTIG_TOM], '1899-12-31 00:00:00') AS BHANDL_GILTIG_TOM,
    	[BHANDL_ID] AS BHANDL_ID,
    	[BHANDL_ID_TEXT] AS BHANDL_ID_TEXT,
    	[BHANDL_PASSIV] AS BHANDL_PASSIV,
    	[BHANDL_TEXT] AS BHANDL_TEXT,
    	COALESCE([BSTAT_GILTIG_FOM], '1899-12-31 00:00:00') AS BSTAT_GILTIG_FOM,
    	COALESCE([BSTAT_GILTIG_TOM], '1899-12-31 00:00:00') AS BSTAT_GILTIG_TOM,
    	[BSTAT_ID] AS BSTAT_ID,
    	[BSTAT_ID_TEXT] AS BSTAT_ID_TEXT,
    	[BSTAT_PASSIV] AS BSTAT_PASSIV,
    	[BSTAT_TEXT] AS BSTAT_TEXT
    FROM [raindance_udp].[udp_100].[EK_DIM_OBJ_AVTBES]) y
    WHERE 1=1"""
    yield from read(query=query, env_var_name='RAINDANCE_2710')