from bollhav import Model, WriteMode
from bollhav.postgres import PostgresColumn, PostgresType
from bollhav.database import Database
from core import read

config = Model(
    name="ek_dim_obj_kto",
    source_entity="EK_DIM_OBJ_KTO",
    table="ek_dim_obj_kto",
    schema="raindance_raw_nks",
    write_mode=WriteMode.TRUNCATE_INSERT,
    columns=[
        PostgresColumn(name="_data_modified", data_type=PostgresType.DATE),
        PostgresColumn(name="_metadata_modified", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="FRANGO_GILTIG_FOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="FRANGO_GILTIG_TOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="FRANGO_ID", data_type=PostgresType.TEXT),
        PostgresColumn(name="FRANGO_ID_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="FRANGO_PASSIV", data_type=PostgresType.BOOLEAN),
        PostgresColumn(name="FRANGO_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="FRARAD_GILTIG_FOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="FRARAD_GILTIG_TOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="FRARAD_ID", data_type=PostgresType.TEXT),
        PostgresColumn(name="FRARAD_ID_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="FRARAD_PASSIV", data_type=PostgresType.BOOLEAN),
        PostgresColumn(name="FRARAD_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="FRASUM_GILTIG_FOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="FRASUM_GILTIG_TOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="FRASUM_ID", data_type=PostgresType.TEXT),
        PostgresColumn(name="FRASUM_ID_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="FRASUM_PASSIV", data_type=PostgresType.BOOLEAN),
        PostgresColumn(name="FRASUM_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="KKLASS_GILTIG_FOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="KKLASS_GILTIG_TOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="KKLASS_ID", data_type=PostgresType.TEXT),
        PostgresColumn(name="KKLASS_ID_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="KKLASS_PASSIV", data_type=PostgresType.BOOLEAN),
        PostgresColumn(name="KKLASS_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="KTO_GILTIG_FOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="KTO_GILTIG_TOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="KTO_ID", data_type=PostgresType.TEXT),
        PostgresColumn(name="KTO_ID_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="KTO_PASSIV", data_type=PostgresType.BOOLEAN),
        PostgresColumn(name="KTO_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="KTOGRP_GILTIG_FOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="KTOGRP_GILTIG_TOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="KTOGRP_ID", data_type=PostgresType.TEXT),
        PostgresColumn(name="KTOGRP_ID_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="KTOGRP_PASSIV", data_type=PostgresType.BOOLEAN),
        PostgresColumn(name="KTOGRP_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="NIVÅ1_GILTIG_FOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="NIVÅ1_GILTIG_TOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="NIVÅ1_ID", data_type=PostgresType.TEXT),
        PostgresColumn(name="NIVÅ1_ID_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="NIVÅ1_PASSIV", data_type=PostgresType.BOOLEAN),
        PostgresColumn(name="NIVÅ1_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="NIVÅ2_GILTIG_FOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="NIVÅ2_GILTIG_TOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="NIVÅ2_ID", data_type=PostgresType.TEXT),
        PostgresColumn(name="NIVÅ2_ID_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="NIVÅ2_PASSIV", data_type=PostgresType.BOOLEAN),
        PostgresColumn(name="NIVÅ2_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="TABRAD_GILTIG_FOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="TABRAD_GILTIG_TOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="TABRAD_ID", data_type=PostgresType.TEXT),
        PostgresColumn(name="TABRAD_ID_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="TABRAD_PASSIV", data_type=PostgresType.BOOLEAN),
        PostgresColumn(name="TABRAD_TEXT", data_type=PostgresType.TEXT),
    ],
    database=Database.POSTGRES,
    cron="0 6 * * *",
    tags=['nks', 'raindance', 'raw'],
)

def execute(env, cfg=config):
    query=f"""SELECT * FROM (SELECT
    	CAST(GETDATE() AS DATE) as _data_modified,
    	CAST(GETDATE() AS DATETIME2) as _metadata_modified,
    	COALESCE([FRANGO_GILTIG_FOM], '1899-12-31 00:00:00') AS FRANGO_GILTIG_FOM,
    	COALESCE([FRANGO_GILTIG_TOM], '1899-12-31 00:00:00') AS FRANGO_GILTIG_TOM,
    	[FRANGO_ID] AS FRANGO_ID,
    	[FRANGO_ID_TEXT] AS FRANGO_ID_TEXT,
    	[FRANGO_PASSIV] AS FRANGO_PASSIV,
    	[FRANGO_TEXT] AS FRANGO_TEXT,
    	COALESCE([FRARAD_GILTIG_FOM], '1899-12-31 00:00:00') AS FRARAD_GILTIG_FOM,
    	COALESCE([FRARAD_GILTIG_TOM], '1899-12-31 00:00:00') AS FRARAD_GILTIG_TOM,
    	[FRARAD_ID] AS FRARAD_ID,
    	[FRARAD_ID_TEXT] AS FRARAD_ID_TEXT,
    	[FRARAD_PASSIV] AS FRARAD_PASSIV,
    	[FRARAD_TEXT] AS FRARAD_TEXT,
    	COALESCE([FRASUM_GILTIG_FOM], '1899-12-31 00:00:00') AS FRASUM_GILTIG_FOM,
    	COALESCE([FRASUM_GILTIG_TOM], '1899-12-31 00:00:00') AS FRASUM_GILTIG_TOM,
    	[FRASUM_ID] AS FRASUM_ID,
    	[FRASUM_ID_TEXT] AS FRASUM_ID_TEXT,
    	[FRASUM_PASSIV] AS FRASUM_PASSIV,
    	[FRASUM_TEXT] AS FRASUM_TEXT,
    	COALESCE([KKLASS_GILTIG_FOM], '1899-12-31 00:00:00') AS KKLASS_GILTIG_FOM,
    	COALESCE([KKLASS_GILTIG_TOM], '1899-12-31 00:00:00') AS KKLASS_GILTIG_TOM,
    	[KKLASS_ID] AS KKLASS_ID,
    	[KKLASS_ID_TEXT] AS KKLASS_ID_TEXT,
    	[KKLASS_PASSIV] AS KKLASS_PASSIV,
    	[KKLASS_TEXT] AS KKLASS_TEXT,
    	COALESCE([KTO_GILTIG_FOM], '1899-12-31 00:00:00') AS KTO_GILTIG_FOM,
    	COALESCE([KTO_GILTIG_TOM], '1899-12-31 00:00:00') AS KTO_GILTIG_TOM,
    	[KTO_ID] AS KTO_ID,
    	[KTO_ID_TEXT] AS KTO_ID_TEXT,
    	[KTO_PASSIV] AS KTO_PASSIV,
    	[KTO_TEXT] AS KTO_TEXT,
    	COALESCE([KTOGRP_GILTIG_FOM], '1899-12-31 00:00:00') AS KTOGRP_GILTIG_FOM,
    	COALESCE([KTOGRP_GILTIG_TOM], '1899-12-31 00:00:00') AS KTOGRP_GILTIG_TOM,
    	[KTOGRP_ID] AS KTOGRP_ID,
    	[KTOGRP_ID_TEXT] AS KTOGRP_ID_TEXT,
    	[KTOGRP_PASSIV] AS KTOGRP_PASSIV,
    	[KTOGRP_TEXT] AS KTOGRP_TEXT,
    	COALESCE([NIVÅ1_GILTIG_FOM], '1899-12-31 00:00:00') AS NIVÅ1_GILTIG_FOM,
    	COALESCE([NIVÅ1_GILTIG_TOM], '1899-12-31 00:00:00') AS NIVÅ1_GILTIG_TOM,
    	[NIVÅ1_ID] AS NIVÅ1_ID,
    	[NIVÅ1_ID_TEXT] AS NIVÅ1_ID_TEXT,
    	[NIVÅ1_PASSIV] AS NIVÅ1_PASSIV,
    	[NIVÅ1_TEXT] AS NIVÅ1_TEXT,
    	COALESCE([NIVÅ2_GILTIG_FOM], '1899-12-31 00:00:00') AS NIVÅ2_GILTIG_FOM,
    	COALESCE([NIVÅ2_GILTIG_TOM], '1899-12-31 00:00:00') AS NIVÅ2_GILTIG_TOM,
    	[NIVÅ2_ID] AS NIVÅ2_ID,
    	[NIVÅ2_ID_TEXT] AS NIVÅ2_ID_TEXT,
    	[NIVÅ2_PASSIV] AS NIVÅ2_PASSIV,
    	[NIVÅ2_TEXT] AS NIVÅ2_TEXT,
    	COALESCE([TABRAD_GILTIG_FOM], '1899-12-31 00:00:00') AS TABRAD_GILTIG_FOM,
    	COALESCE([TABRAD_GILTIG_TOM], '1899-12-31 00:00:00') AS TABRAD_GILTIG_TOM,
    	[TABRAD_ID] AS TABRAD_ID,
    	[TABRAD_ID_TEXT] AS TABRAD_ID_TEXT,
    	[TABRAD_PASSIV] AS TABRAD_PASSIV,
    	[TABRAD_TEXT] AS TABRAD_TEXT
    FROM [raindance_udp].[udp_100].[EK_DIM_OBJ_KTO]) y
    WHERE 1=1"""
    yield from read(query=query, env_var_name='RAINDANCE_2710')