from bollhav import Model, WriteMode
from bollhav.postgres import PostgresColumn, PostgresType
from bollhav.database import Database
from core import read, write
from roskarl.marshal import with_env_config, EnvConfig
from roskarl import env_var_dsn

config = Model(
    name="ek_dim_obj_kto",
    source_entity="EK_DIM_OBJ_KTO",
    table="ek_dim_obj_kto",
    schema="raindance_raw_1560",
    write_mode=WriteMode.TRUNCATE_INSERT,
    columns=[
        PostgresColumn(name="_data_modified", data_type=PostgresType.DATE),
        PostgresColumn(name="_metadata_modified", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="FRANGO_GILTIG_FOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="FRANGO_GILTIG_TOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="FRANGO_ID", data_type=PostgresType.TEXT),
        PostgresColumn(name="FRANGO_ID_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="FRANGO_PASSIV", data_type=PostgresType.BOOLEAN),
        PostgresColumn(name="FRANGO_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="KGRUPP_GILTIG_FOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="KGRUPP_GILTIG_TOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="KGRUPP_ID", data_type=PostgresType.TEXT),
        PostgresColumn(name="KGRUPP_ID_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="KGRUPP_PASSIV", data_type=PostgresType.BOOLEAN),
        PostgresColumn(name="KGRUPP_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="KK_GILTIG_FOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="KK_GILTIG_TOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="KK_ID", data_type=PostgresType.TEXT),
        PostgresColumn(name="KK_ID_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="KK_PASSIV", data_type=PostgresType.BOOLEAN),
        PostgresColumn(name="KK_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="KKGR_GILTIG_FOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="KKGR_GILTIG_TOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="KKGR_ID", data_type=PostgresType.TEXT),
        PostgresColumn(name="KKGR_ID_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="KKGR_PASSIV", data_type=PostgresType.BOOLEAN),
        PostgresColumn(name="KKGR_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="KKL_GILTIG_FOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="KKL_GILTIG_TOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="KKL_ID", data_type=PostgresType.TEXT),
        PostgresColumn(name="KKL_ID_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="KKL_PASSIV", data_type=PostgresType.BOOLEAN),
        PostgresColumn(name="KKL_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="KTO_GILTIG_FOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="KTO_GILTIG_TOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="KTO_ID", data_type=PostgresType.TEXT),
        PostgresColumn(name="KTO_ID_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="KTO_PASSIV", data_type=PostgresType.BOOLEAN),
        PostgresColumn(name="KTO_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="R3_GILTIG_FOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="R3_GILTIG_TOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="R3_ID", data_type=PostgresType.TEXT),
        PostgresColumn(name="R3_ID_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="R3_PASSIV", data_type=PostgresType.BOOLEAN),
        PostgresColumn(name="R3_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="R4_GILTIG_FOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="R4_GILTIG_TOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="R4_ID", data_type=PostgresType.TEXT),
        PostgresColumn(name="R4_ID_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="R4_PASSIV", data_type=PostgresType.BOOLEAN),
        PostgresColumn(name="R4_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="RRBR_GILTIG_FOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="RRBR_GILTIG_TOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="RRBR_ID", data_type=PostgresType.TEXT),
        PostgresColumn(name="RRBR_ID_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="RRBR_PASSIV", data_type=PostgresType.BOOLEAN),
        PostgresColumn(name="RRBR_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="STÖKGR_GILTIG_FOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="STÖKGR_GILTIG_TOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="STÖKGR_ID", data_type=PostgresType.TEXT),
        PostgresColumn(name="STÖKGR_ID_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="STÖKGR_PASSIV", data_type=PostgresType.BOOLEAN),
        PostgresColumn(name="STÖKGR_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="STÖKOD_GILTIG_FOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="STÖKOD_GILTIG_TOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="STÖKOD_ID", data_type=PostgresType.TEXT),
        PostgresColumn(name="STÖKOD_ID_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="STÖKOD_PASSIV", data_type=PostgresType.BOOLEAN),
        PostgresColumn(name="STÖKOD_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="TSIK_GILTIG_FOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="TSIK_GILTIG_TOM", data_type=PostgresType.TIMESTAMPTZ),
        PostgresColumn(name="TSIK_ID", data_type=PostgresType.TEXT),
        PostgresColumn(name="TSIK_ID_TEXT", data_type=PostgresType.TEXT),
        PostgresColumn(name="TSIK_PASSIV", data_type=PostgresType.BOOLEAN),
        PostgresColumn(name="TSIK_TEXT", data_type=PostgresType.TEXT),
    ],
    database=Database.POSTGRES,
    cron="0 6 * * *",
    tags=['pvn', 'raindance', 'raw'],
)

@with_env_config
def execute(env: EnvConfig, cfg=config):
    dest_dsn = env_var_dsn("BIG_EKONOMI_EXECUTION_PROD")
    query = """
    SELECT
	CAST(GETDATE() AS DATE) as _data_modified,
	CAST(GETDATE() AS DATETIME2) as _metadata_modified,
	COALESCE([FRANGO_GILTIG_FOM], '1899-12-31 00:00:00') AS FRANGO_GILTIG_FOM,
	COALESCE([FRANGO_GILTIG_TOM], '1899-12-31 00:00:00') AS FRANGO_GILTIG_TOM,
	[FRANGO_ID] AS FRANGO_ID,
	[FRANGO_ID_TEXT] AS FRANGO_ID_TEXT,
	[FRANGO_PASSIV] AS FRANGO_PASSIV,
	[FRANGO_TEXT] AS FRANGO_TEXT,
	COALESCE([KGRUPP_GILTIG_FOM], '1899-12-31 00:00:00') AS KGRUPP_GILTIG_FOM,
	COALESCE([KGRUPP_GILTIG_TOM], '1899-12-31 00:00:00') AS KGRUPP_GILTIG_TOM,
	[KGRUPP_ID] AS KGRUPP_ID,
	[KGRUPP_ID_TEXT] AS KGRUPP_ID_TEXT,
	[KGRUPP_PASSIV] AS KGRUPP_PASSIV,
	[KGRUPP_TEXT] AS KGRUPP_TEXT,
	COALESCE([KK_GILTIG_FOM], '1899-12-31 00:00:00') AS KK_GILTIG_FOM,
	COALESCE([KK_GILTIG_TOM], '1899-12-31 00:00:00') AS KK_GILTIG_TOM,
	[KK_ID] AS KK_ID,
	[KK_ID_TEXT] AS KK_ID_TEXT,
	[KK_PASSIV] AS KK_PASSIV,
	[KK_TEXT] AS KK_TEXT,
	COALESCE([KKGR_GILTIG_FOM], '1899-12-31 00:00:00') AS KKGR_GILTIG_FOM,
	COALESCE([KKGR_GILTIG_TOM], '1899-12-31 00:00:00') AS KKGR_GILTIG_TOM,
	[KKGR_ID] AS KKGR_ID,
	[KKGR_ID_TEXT] AS KKGR_ID_TEXT,
	[KKGR_PASSIV] AS KKGR_PASSIV,
	[KKGR_TEXT] AS KKGR_TEXT,
	COALESCE([KKL_GILTIG_FOM], '1899-12-31 00:00:00') AS KKL_GILTIG_FOM,
	COALESCE([KKL_GILTIG_TOM], '1899-12-31 00:00:00') AS KKL_GILTIG_TOM,
	[KKL_ID] AS KKL_ID,
	[KKL_ID_TEXT] AS KKL_ID_TEXT,
	[KKL_PASSIV] AS KKL_PASSIV,
	[KKL_TEXT] AS KKL_TEXT,
	COALESCE([KTO_GILTIG_FOM], '1899-12-31 00:00:00') AS KTO_GILTIG_FOM,
	COALESCE([KTO_GILTIG_TOM], '1899-12-31 00:00:00') AS KTO_GILTIG_TOM,
	[KTO_ID] AS KTO_ID,
	[KTO_ID_TEXT] AS KTO_ID_TEXT,
	[KTO_PASSIV] AS KTO_PASSIV,
	[KTO_TEXT] AS KTO_TEXT,
	COALESCE([R3_GILTIG_FOM], '1899-12-31 00:00:00') AS R3_GILTIG_FOM,
	COALESCE([R3_GILTIG_TOM], '1899-12-31 00:00:00') AS R3_GILTIG_TOM,
	[R3_ID] AS R3_ID,
	[R3_ID_TEXT] AS R3_ID_TEXT,
	[R3_PASSIV] AS R3_PASSIV,
	[R3_TEXT] AS R3_TEXT,
	COALESCE([R4_GILTIG_FOM], '1899-12-31 00:00:00') AS R4_GILTIG_FOM,
	COALESCE([R4_GILTIG_TOM], '1899-12-31 00:00:00') AS R4_GILTIG_TOM,
	[R4_ID] AS R4_ID,
	[R4_ID_TEXT] AS R4_ID_TEXT,
	[R4_PASSIV] AS R4_PASSIV,
	[R4_TEXT] AS R4_TEXT,
	COALESCE([RRBR_GILTIG_FOM], '1899-12-31 00:00:00') AS RRBR_GILTIG_FOM,
	COALESCE([RRBR_GILTIG_TOM], '1899-12-31 00:00:00') AS RRBR_GILTIG_TOM,
	[RRBR_ID] AS RRBR_ID,
	[RRBR_ID_TEXT] AS RRBR_ID_TEXT,
	[RRBR_PASSIV] AS RRBR_PASSIV,
	[RRBR_TEXT] AS RRBR_TEXT,
	COALESCE([STÖKGR_GILTIG_FOM], '1899-12-31 00:00:00') AS STÖKGR_GILTIG_FOM,
	COALESCE([STÖKGR_GILTIG_TOM], '1899-12-31 00:00:00') AS STÖKGR_GILTIG_TOM,
	[STÖKGR_ID] AS STÖKGR_ID,
	[STÖKGR_ID_TEXT] AS STÖKGR_ID_TEXT,
	[STÖKGR_PASSIV] AS STÖKGR_PASSIV,
	[STÖKGR_TEXT] AS STÖKGR_TEXT,
	COALESCE([STÖKOD_GILTIG_FOM], '1899-12-31 00:00:00') AS STÖKOD_GILTIG_FOM,
	COALESCE([STÖKOD_GILTIG_TOM], '1899-12-31 00:00:00') AS STÖKOD_GILTIG_TOM,
	[STÖKOD_ID] AS STÖKOD_ID,
	[STÖKOD_ID_TEXT] AS STÖKOD_ID_TEXT,
	[STÖKOD_PASSIV] AS STÖKOD_PASSIV,
	[STÖKOD_TEXT] AS STÖKOD_TEXT,
	COALESCE([TSIK_GILTIG_FOM], '1899-12-31 00:00:00') AS TSIK_GILTIG_FOM,
	COALESCE([TSIK_GILTIG_TOM], '1899-12-31 00:00:00') AS TSIK_GILTIG_TOM,
	[TSIK_ID] AS TSIK_ID,
	[TSIK_ID_TEXT] AS TSIK_ID_TEXT,
	[TSIK_PASSIV] AS TSIK_PASSIV,
	[TSIK_TEXT] AS TSIK_TEXT
    FROM [utdata].[utdata156].[EK_DIM_OBJ_KTO]

    """
    total_rows = 0
    first_batch = True
    for df in read("RAINDANCE_1560", query):
        if len(df) == 0:
            continue
        write(cfg, df, dest_dsn)
        if first_batch:
            cfg.write_mode = WriteMode.APPEND
            first_batch = False
        total_rows += len(df)
    print(f"  ✓ {cfg.name}: {total_rows:,} rows written" if total_rows else f"  ⏭ {cfg.name}: no data, skipping")